// Code generated by ent, DO NOT EDIT.

package useraffiliateledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the useraffiliateledger type in the database.
	Label = "user_affiliate_ledger"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldSourceUserID holds the string denoting the source_user_id field in the database.
	FieldSourceUserID = "source_user_id"
	// FieldSourceOrderID holds the string denoting the source_order_id field in the database.
	FieldSourceOrderID = "source_order_id"
	// FieldFrozenUntil holds the string denoting the frozen_until field in the database.
	FieldFrozenUntil = "frozen_until"
	// FieldBalanceAfter holds the string denoting the balance_after field in the database.
	FieldBalanceAfter = "balance_after"
	// FieldAffQuotaAfter holds the string denoting the aff_quota_after field in the database.
	FieldAffQuotaAfter = "aff_quota_after"
	// FieldAffFrozenQuotaAfter holds the string denoting the aff_frozen_quota_after field in the database.
	FieldAffFrozenQuotaAfter = "aff_frozen_quota_after"
	// FieldAffHistoryQuotaAfter holds the string denoting the aff_history_quota_after field in the database.
	FieldAffHistoryQuotaAfter = "aff_history_quota_after"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the useraffiliateledger in the database.
	Table = "user_affiliate_ledger"
)

// Columns holds all SQL columns for useraffiliateledger fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldAction,
	FieldAmount,
	FieldSourceUserID,
	FieldSourceOrderID,
	FieldFrozenUntil,
	FieldBalanceAfter,
	FieldAffQuotaAfter,
	FieldAffFrozenQuotaAfter,
	FieldAffHistoryQuotaAfter,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ActionValidator is a validator for the "action" field. It is called by the builders before save.
	ActionValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserAffiliateLedger queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// BySourceUserID orders the results by the source_user_id field.
func BySourceUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceUserID, opts...).ToFunc()
}

// BySourceOrderID orders the results by the source_order_id field.
func BySourceOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceOrderID, opts...).ToFunc()
}

// ByFrozenUntil orders the results by the frozen_until field.
func ByFrozenUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrozenUntil, opts...).ToFunc()
}

// ByBalanceAfter orders the results by the balance_after field.
func ByBalanceAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAfter, opts...).ToFunc()
}

// ByAffQuotaAfter orders the results by the aff_quota_after field.
func ByAffQuotaAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffQuotaAfter, opts...).ToFunc()
}

// ByAffFrozenQuotaAfter orders the results by the aff_frozen_quota_after field.
func ByAffFrozenQuotaAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffFrozenQuotaAfter, opts...).ToFunc()
}

// ByAffHistoryQuotaAfter orders the results by the aff_history_quota_after field.
func ByAffHistoryQuotaAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffHistoryQuotaAfter, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
