// Code generated by ent, DO NOT EDIT.

package useraffiliateledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldUserID, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldAction, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldAmount, v))
}

// SourceUserID applies equality check predicate on the "source_user_id" field. It's identical to SourceUserIDEQ.
func SourceUserID(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldSourceUserID, v))
}

// SourceOrderID applies equality check predicate on the "source_order_id" field. It's identical to SourceOrderIDEQ.
func SourceOrderID(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldSourceOrderID, v))
}

// FrozenUntil applies equality check predicate on the "frozen_until" field. It's identical to FrozenUntilEQ.
func FrozenUntil(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldFrozenUntil, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldBalanceAfter, v))
}

// AffQuotaAfter applies equality check predicate on the "aff_quota_after" field. It's identical to AffQuotaAfterEQ.
func AffQuotaAfter(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldAffQuotaAfter, v))
}

// AffFrozenQuotaAfter applies equality check predicate on the "aff_frozen_quota_after" field. It's identical to AffFrozenQuotaAfterEQ.
func AffFrozenQuotaAfter(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldAffFrozenQuotaAfter, v))
}

// AffHistoryQuotaAfter applies equality check predicate on the "aff_history_quota_after" field. It's identical to AffHistoryQuotaAfterEQ.
func AffHistoryQuotaAfter(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldAffHistoryQuotaAfter, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLTE(FieldUserID, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldContainsFold(FieldAction, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLTE(FieldAmount, v))
}

// SourceUserIDEQ applies the EQ predicate on the "source_user_id" field.
func SourceUserIDEQ(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldSourceUserID, v))
}

// SourceUserIDNEQ applies the NEQ predicate on the "source_user_id" field.
func SourceUserIDNEQ(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNEQ(FieldSourceUserID, v))
}

// SourceUserIDIn applies the In predicate on the "source_user_id" field.
func SourceUserIDIn(vs ...int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIn(FieldSourceUserID, vs...))
}

// SourceUserIDNotIn applies the NotIn predicate on the "source_user_id" field.
func SourceUserIDNotIn(vs ...int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotIn(FieldSourceUserID, vs...))
}

// SourceUserIDGT applies the GT predicate on the "source_user_id" field.
func SourceUserIDGT(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGT(FieldSourceUserID, v))
}

// SourceUserIDGTE applies the GTE predicate on the "source_user_id" field.
func SourceUserIDGTE(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGTE(FieldSourceUserID, v))
}

// SourceUserIDLT applies the LT predicate on the "source_user_id" field.
func SourceUserIDLT(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLT(FieldSourceUserID, v))
}

// SourceUserIDLTE applies the LTE predicate on the "source_user_id" field.
func SourceUserIDLTE(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLTE(FieldSourceUserID, v))
}

// SourceUserIDIsNil applies the IsNil predicate on the "source_user_id" field.
func SourceUserIDIsNil() predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIsNull(FieldSourceUserID))
}

// SourceUserIDNotNil applies the NotNil predicate on the "source_user_id" field.
func SourceUserIDNotNil() predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotNull(FieldSourceUserID))
}

// SourceOrderIDEQ applies the EQ predicate on the "source_order_id" field.
func SourceOrderIDEQ(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldSourceOrderID, v))
}

// SourceOrderIDNEQ applies the NEQ predicate on the "source_order_id" field.
func SourceOrderIDNEQ(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNEQ(FieldSourceOrderID, v))
}

// SourceOrderIDIn applies the In predicate on the "source_order_id" field.
func SourceOrderIDIn(vs ...int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIn(FieldSourceOrderID, vs...))
}

// SourceOrderIDNotIn applies the NotIn predicate on the "source_order_id" field.
func SourceOrderIDNotIn(vs ...int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotIn(FieldSourceOrderID, vs...))
}

// SourceOrderIDGT applies the GT predicate on the "source_order_id" field.
func SourceOrderIDGT(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGT(FieldSourceOrderID, v))
}

// SourceOrderIDGTE applies the GTE predicate on the "source_order_id" field.
func SourceOrderIDGTE(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGTE(FieldSourceOrderID, v))
}

// SourceOrderIDLT applies the LT predicate on the "source_order_id" field.
func SourceOrderIDLT(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLT(FieldSourceOrderID, v))
}

// SourceOrderIDLTE applies the LTE predicate on the "source_order_id" field.
func SourceOrderIDLTE(v int64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLTE(FieldSourceOrderID, v))
}

// SourceOrderIDIsNil applies the IsNil predicate on the "source_order_id" field.
func SourceOrderIDIsNil() predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIsNull(FieldSourceOrderID))
}

// SourceOrderIDNotNil applies the NotNil predicate on the "source_order_id" field.
func SourceOrderIDNotNil() predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotNull(FieldSourceOrderID))
}

// FrozenUntilEQ applies the EQ predicate on the "frozen_until" field.
func FrozenUntilEQ(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldFrozenUntil, v))
}

// FrozenUntilNEQ applies the NEQ predicate on the "frozen_until" field.
func FrozenUntilNEQ(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNEQ(FieldFrozenUntil, v))
}

// FrozenUntilIn applies the In predicate on the "frozen_until" field.
func FrozenUntilIn(vs ...time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIn(FieldFrozenUntil, vs...))
}

// FrozenUntilNotIn applies the NotIn predicate on the "frozen_until" field.
func FrozenUntilNotIn(vs ...time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotIn(FieldFrozenUntil, vs...))
}

// FrozenUntilGT applies the GT predicate on the "frozen_until" field.
func FrozenUntilGT(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGT(FieldFrozenUntil, v))
}

// FrozenUntilGTE applies the GTE predicate on the "frozen_until" field.
func FrozenUntilGTE(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGTE(FieldFrozenUntil, v))
}

// FrozenUntilLT applies the LT predicate on the "frozen_until" field.
func FrozenUntilLT(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLT(FieldFrozenUntil, v))
}

// FrozenUntilLTE applies the LTE predicate on the "frozen_until" field.
func FrozenUntilLTE(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLTE(FieldFrozenUntil, v))
}

// FrozenUntilIsNil applies the IsNil predicate on the "frozen_until" field.
func FrozenUntilIsNil() predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIsNull(FieldFrozenUntil))
}

// FrozenUntilNotNil applies the NotNil predicate on the "frozen_until" field.
func FrozenUntilNotNil() predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotNull(FieldFrozenUntil))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLTE(FieldBalanceAfter, v))
}

// BalanceAfterIsNil applies the IsNil predicate on the "balance_after" field.
func BalanceAfterIsNil() predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIsNull(FieldBalanceAfter))
}

// BalanceAfterNotNil applies the NotNil predicate on the "balance_after" field.
func BalanceAfterNotNil() predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotNull(FieldBalanceAfter))
}

// AffQuotaAfterEQ applies the EQ predicate on the "aff_quota_after" field.
func AffQuotaAfterEQ(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldAffQuotaAfter, v))
}

// AffQuotaAfterNEQ applies the NEQ predicate on the "aff_quota_after" field.
func AffQuotaAfterNEQ(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNEQ(FieldAffQuotaAfter, v))
}

// AffQuotaAfterIn applies the In predicate on the "aff_quota_after" field.
func AffQuotaAfterIn(vs ...float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIn(FieldAffQuotaAfter, vs...))
}

// AffQuotaAfterNotIn applies the NotIn predicate on the "aff_quota_after" field.
func AffQuotaAfterNotIn(vs ...float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotIn(FieldAffQuotaAfter, vs...))
}

// AffQuotaAfterGT applies the GT predicate on the "aff_quota_after" field.
func AffQuotaAfterGT(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGT(FieldAffQuotaAfter, v))
}

// AffQuotaAfterGTE applies the GTE predicate on the "aff_quota_after" field.
func AffQuotaAfterGTE(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGTE(FieldAffQuotaAfter, v))
}

// AffQuotaAfterLT applies the LT predicate on the "aff_quota_after" field.
func AffQuotaAfterLT(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLT(FieldAffQuotaAfter, v))
}

// AffQuotaAfterLTE applies the LTE predicate on the "aff_quota_after" field.
func AffQuotaAfterLTE(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLTE(FieldAffQuotaAfter, v))
}

// AffQuotaAfterIsNil applies the IsNil predicate on the "aff_quota_after" field.
func AffQuotaAfterIsNil() predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIsNull(FieldAffQuotaAfter))
}

// AffQuotaAfterNotNil applies the NotNil predicate on the "aff_quota_after" field.
func AffQuotaAfterNotNil() predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotNull(FieldAffQuotaAfter))
}

// AffFrozenQuotaAfterEQ applies the EQ predicate on the "aff_frozen_quota_after" field.
func AffFrozenQuotaAfterEQ(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldAffFrozenQuotaAfter, v))
}

// AffFrozenQuotaAfterNEQ applies the NEQ predicate on the "aff_frozen_quota_after" field.
func AffFrozenQuotaAfterNEQ(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNEQ(FieldAffFrozenQuotaAfter, v))
}

// AffFrozenQuotaAfterIn applies the In predicate on the "aff_frozen_quota_after" field.
func AffFrozenQuotaAfterIn(vs ...float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIn(FieldAffFrozenQuotaAfter, vs...))
}

// AffFrozenQuotaAfterNotIn applies the NotIn predicate on the "aff_frozen_quota_after" field.
func AffFrozenQuotaAfterNotIn(vs ...float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotIn(FieldAffFrozenQuotaAfter, vs...))
}

// AffFrozenQuotaAfterGT applies the GT predicate on the "aff_frozen_quota_after" field.
func AffFrozenQuotaAfterGT(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGT(FieldAffFrozenQuotaAfter, v))
}

// AffFrozenQuotaAfterGTE applies the GTE predicate on the "aff_frozen_quota_after" field.
func AffFrozenQuotaAfterGTE(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGTE(FieldAffFrozenQuotaAfter, v))
}

// AffFrozenQuotaAfterLT applies the LT predicate on the "aff_frozen_quota_after" field.
func AffFrozenQuotaAfterLT(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLT(FieldAffFrozenQuotaAfter, v))
}

// AffFrozenQuotaAfterLTE applies the LTE predicate on the "aff_frozen_quota_after" field.
func AffFrozenQuotaAfterLTE(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLTE(FieldAffFrozenQuotaAfter, v))
}

// AffFrozenQuotaAfterIsNil applies the IsNil predicate on the "aff_frozen_quota_after" field.
func AffFrozenQuotaAfterIsNil() predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIsNull(FieldAffFrozenQuotaAfter))
}

// AffFrozenQuotaAfterNotNil applies the NotNil predicate on the "aff_frozen_quota_after" field.
func AffFrozenQuotaAfterNotNil() predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotNull(FieldAffFrozenQuotaAfter))
}

// AffHistoryQuotaAfterEQ applies the EQ predicate on the "aff_history_quota_after" field.
func AffHistoryQuotaAfterEQ(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldAffHistoryQuotaAfter, v))
}

// AffHistoryQuotaAfterNEQ applies the NEQ predicate on the "aff_history_quota_after" field.
func AffHistoryQuotaAfterNEQ(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNEQ(FieldAffHistoryQuotaAfter, v))
}

// AffHistoryQuotaAfterIn applies the In predicate on the "aff_history_quota_after" field.
func AffHistoryQuotaAfterIn(vs ...float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIn(FieldAffHistoryQuotaAfter, vs...))
}

// AffHistoryQuotaAfterNotIn applies the NotIn predicate on the "aff_history_quota_after" field.
func AffHistoryQuotaAfterNotIn(vs ...float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotIn(FieldAffHistoryQuotaAfter, vs...))
}

// AffHistoryQuotaAfterGT applies the GT predicate on the "aff_history_quota_after" field.
func AffHistoryQuotaAfterGT(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGT(FieldAffHistoryQuotaAfter, v))
}

// AffHistoryQuotaAfterGTE applies the GTE predicate on the "aff_history_quota_after" field.
func AffHistoryQuotaAfterGTE(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGTE(FieldAffHistoryQuotaAfter, v))
}

// AffHistoryQuotaAfterLT applies the LT predicate on the "aff_history_quota_after" field.
func AffHistoryQuotaAfterLT(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLT(FieldAffHistoryQuotaAfter, v))
}

// AffHistoryQuotaAfterLTE applies the LTE predicate on the "aff_history_quota_after" field.
func AffHistoryQuotaAfterLTE(v float64) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLTE(FieldAffHistoryQuotaAfter, v))
}

// AffHistoryQuotaAfterIsNil applies the IsNil predicate on the "aff_history_quota_after" field.
func AffHistoryQuotaAfterIsNil() predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIsNull(FieldAffHistoryQuotaAfter))
}

// AffHistoryQuotaAfterNotNil applies the NotNil predicate on the "aff_history_quota_after" field.
func AffHistoryQuotaAfterNotNil() predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotNull(FieldAffHistoryQuotaAfter))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserAffiliateLedger) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserAffiliateLedger) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserAffiliateLedger) predicate.UserAffiliateLedger {
	return predicate.UserAffiliateLedger(sql.NotPredicates(p))
}
