// Code generated by ent, DO NOT EDIT.

package usersubscriptioncycle

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldUpdatedAt, v))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldSubscriptionID, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldStartsAt, v))
}

// EndsAt applies equality check predicate on the "ends_at" field. It's identical to EndsAtEQ.
func EndsAt(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldEndsAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldStatus, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldSourceType, v))
}

// SourceRef applies equality check predicate on the "source_ref" field. It's identical to SourceRefEQ.
func SourceRef(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldSourceRef, v))
}

// ManualBulkQuotaResetEnabled applies equality check predicate on the "manual_bulk_quota_reset_enabled" field. It's identical to ManualBulkQuotaResetEnabledEQ.
func ManualBulkQuotaResetEnabled(v bool) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldManualBulkQuotaResetEnabled, v))
}

// FinalUsageUsd applies equality check predicate on the "final_usage_usd" field. It's identical to FinalUsageUsdEQ.
func FinalUsageUsd(v float64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldFinalUsageUsd, v))
}

// FinalManualQuotaResetCount applies equality check predicate on the "final_manual_quota_reset_count" field. It's identical to FinalManualQuotaResetCountEQ.
func FinalManualQuotaResetCount(v int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldFinalManualQuotaResetCount, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLTE(FieldUpdatedAt, v))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLTE(FieldStartsAt, v))
}

// EndsAtEQ applies the EQ predicate on the "ends_at" field.
func EndsAtEQ(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldEndsAt, v))
}

// EndsAtNEQ applies the NEQ predicate on the "ends_at" field.
func EndsAtNEQ(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNEQ(FieldEndsAt, v))
}

// EndsAtIn applies the In predicate on the "ends_at" field.
func EndsAtIn(vs ...time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldIn(FieldEndsAt, vs...))
}

// EndsAtNotIn applies the NotIn predicate on the "ends_at" field.
func EndsAtNotIn(vs ...time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNotIn(FieldEndsAt, vs...))
}

// EndsAtGT applies the GT predicate on the "ends_at" field.
func EndsAtGT(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGT(FieldEndsAt, v))
}

// EndsAtGTE applies the GTE predicate on the "ends_at" field.
func EndsAtGTE(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGTE(FieldEndsAt, v))
}

// EndsAtLT applies the LT predicate on the "ends_at" field.
func EndsAtLT(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLT(FieldEndsAt, v))
}

// EndsAtLTE applies the LTE predicate on the "ends_at" field.
func EndsAtLTE(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLTE(FieldEndsAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldContainsFold(FieldStatus, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceRefEQ applies the EQ predicate on the "source_ref" field.
func SourceRefEQ(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldSourceRef, v))
}

// SourceRefNEQ applies the NEQ predicate on the "source_ref" field.
func SourceRefNEQ(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNEQ(FieldSourceRef, v))
}

// SourceRefIn applies the In predicate on the "source_ref" field.
func SourceRefIn(vs ...string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldIn(FieldSourceRef, vs...))
}

// SourceRefNotIn applies the NotIn predicate on the "source_ref" field.
func SourceRefNotIn(vs ...string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNotIn(FieldSourceRef, vs...))
}

// SourceRefGT applies the GT predicate on the "source_ref" field.
func SourceRefGT(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGT(FieldSourceRef, v))
}

// SourceRefGTE applies the GTE predicate on the "source_ref" field.
func SourceRefGTE(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGTE(FieldSourceRef, v))
}

// SourceRefLT applies the LT predicate on the "source_ref" field.
func SourceRefLT(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLT(FieldSourceRef, v))
}

// SourceRefLTE applies the LTE predicate on the "source_ref" field.
func SourceRefLTE(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLTE(FieldSourceRef, v))
}

// SourceRefContains applies the Contains predicate on the "source_ref" field.
func SourceRefContains(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldContains(FieldSourceRef, v))
}

// SourceRefHasPrefix applies the HasPrefix predicate on the "source_ref" field.
func SourceRefHasPrefix(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldHasPrefix(FieldSourceRef, v))
}

// SourceRefHasSuffix applies the HasSuffix predicate on the "source_ref" field.
func SourceRefHasSuffix(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldHasSuffix(FieldSourceRef, v))
}

// SourceRefIsNil applies the IsNil predicate on the "source_ref" field.
func SourceRefIsNil() predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldIsNull(FieldSourceRef))
}

// SourceRefNotNil applies the NotNil predicate on the "source_ref" field.
func SourceRefNotNil() predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNotNull(FieldSourceRef))
}

// SourceRefEqualFold applies the EqualFold predicate on the "source_ref" field.
func SourceRefEqualFold(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEqualFold(FieldSourceRef, v))
}

// SourceRefContainsFold applies the ContainsFold predicate on the "source_ref" field.
func SourceRefContainsFold(v string) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldContainsFold(FieldSourceRef, v))
}

// ManualBulkQuotaResetEnabledEQ applies the EQ predicate on the "manual_bulk_quota_reset_enabled" field.
func ManualBulkQuotaResetEnabledEQ(v bool) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldManualBulkQuotaResetEnabled, v))
}

// ManualBulkQuotaResetEnabledNEQ applies the NEQ predicate on the "manual_bulk_quota_reset_enabled" field.
func ManualBulkQuotaResetEnabledNEQ(v bool) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNEQ(FieldManualBulkQuotaResetEnabled, v))
}

// FinalUsageUsdEQ applies the EQ predicate on the "final_usage_usd" field.
func FinalUsageUsdEQ(v float64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldFinalUsageUsd, v))
}

// FinalUsageUsdNEQ applies the NEQ predicate on the "final_usage_usd" field.
func FinalUsageUsdNEQ(v float64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNEQ(FieldFinalUsageUsd, v))
}

// FinalUsageUsdIn applies the In predicate on the "final_usage_usd" field.
func FinalUsageUsdIn(vs ...float64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldIn(FieldFinalUsageUsd, vs...))
}

// FinalUsageUsdNotIn applies the NotIn predicate on the "final_usage_usd" field.
func FinalUsageUsdNotIn(vs ...float64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNotIn(FieldFinalUsageUsd, vs...))
}

// FinalUsageUsdGT applies the GT predicate on the "final_usage_usd" field.
func FinalUsageUsdGT(v float64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGT(FieldFinalUsageUsd, v))
}

// FinalUsageUsdGTE applies the GTE predicate on the "final_usage_usd" field.
func FinalUsageUsdGTE(v float64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGTE(FieldFinalUsageUsd, v))
}

// FinalUsageUsdLT applies the LT predicate on the "final_usage_usd" field.
func FinalUsageUsdLT(v float64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLT(FieldFinalUsageUsd, v))
}

// FinalUsageUsdLTE applies the LTE predicate on the "final_usage_usd" field.
func FinalUsageUsdLTE(v float64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLTE(FieldFinalUsageUsd, v))
}

// FinalManualQuotaResetCountEQ applies the EQ predicate on the "final_manual_quota_reset_count" field.
func FinalManualQuotaResetCountEQ(v int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldFinalManualQuotaResetCount, v))
}

// FinalManualQuotaResetCountNEQ applies the NEQ predicate on the "final_manual_quota_reset_count" field.
func FinalManualQuotaResetCountNEQ(v int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNEQ(FieldFinalManualQuotaResetCount, v))
}

// FinalManualQuotaResetCountIn applies the In predicate on the "final_manual_quota_reset_count" field.
func FinalManualQuotaResetCountIn(vs ...int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldIn(FieldFinalManualQuotaResetCount, vs...))
}

// FinalManualQuotaResetCountNotIn applies the NotIn predicate on the "final_manual_quota_reset_count" field.
func FinalManualQuotaResetCountNotIn(vs ...int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNotIn(FieldFinalManualQuotaResetCount, vs...))
}

// FinalManualQuotaResetCountGT applies the GT predicate on the "final_manual_quota_reset_count" field.
func FinalManualQuotaResetCountGT(v int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGT(FieldFinalManualQuotaResetCount, v))
}

// FinalManualQuotaResetCountGTE applies the GTE predicate on the "final_manual_quota_reset_count" field.
func FinalManualQuotaResetCountGTE(v int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGTE(FieldFinalManualQuotaResetCount, v))
}

// FinalManualQuotaResetCountLT applies the LT predicate on the "final_manual_quota_reset_count" field.
func FinalManualQuotaResetCountLT(v int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLT(FieldFinalManualQuotaResetCount, v))
}

// FinalManualQuotaResetCountLTE applies the LTE predicate on the "final_manual_quota_reset_count" field.
func FinalManualQuotaResetCountLTE(v int64) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLTE(FieldFinalManualQuotaResetCount, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.FieldNotNull(FieldCompletedAt))
}

// HasSubscription applies the HasEdge predicate on the "subscription" edge.
func HasSubscription() predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionWith applies the HasEdge predicate on the "subscription" edge with a given conditions (other predicates).
func HasSubscriptionWith(preds ...predicate.UserSubscription) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(func(s *sql.Selector) {
		step := newSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserSubscriptionCycle) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserSubscriptionCycle) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserSubscriptionCycle) predicate.UserSubscriptionCycle {
	return predicate.UserSubscriptionCycle(sql.NotPredicates(p))
}
