// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/useraffiliatereversal"
)

// UserAffiliateReversalCreate is the builder for creating a UserAffiliateReversal entity.
type UserAffiliateReversalCreate struct {
	config
	mutation *UserAffiliateReversalMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSourceLedgerID sets the "source_ledger_id" field.
func (_c *UserAffiliateReversalCreate) SetSourceLedgerID(v int64) *UserAffiliateReversalCreate {
	_c.mutation.SetSourceLedgerID(v)
	return _c
}

// SetNillableSourceLedgerID sets the "source_ledger_id" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableSourceLedgerID(v *int64) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetSourceLedgerID(*v)
	}
	return _c
}

// SetSourceOrderID sets the "source_order_id" field.
func (_c *UserAffiliateReversalCreate) SetSourceOrderID(v int64) *UserAffiliateReversalCreate {
	_c.mutation.SetSourceOrderID(v)
	return _c
}

// SetInviterUserID sets the "inviter_user_id" field.
func (_c *UserAffiliateReversalCreate) SetInviterUserID(v int64) *UserAffiliateReversalCreate {
	_c.mutation.SetInviterUserID(v)
	return _c
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (_c *UserAffiliateReversalCreate) SetInviteeUserID(v int64) *UserAffiliateReversalCreate {
	_c.mutation.SetInviteeUserID(v)
	return _c
}

// SetRebateAmount sets the "rebate_amount" field.
func (_c *UserAffiliateReversalCreate) SetRebateAmount(v float64) *UserAffiliateReversalCreate {
	_c.mutation.SetRebateAmount(v)
	return _c
}

// SetFrozenQuotaDeducted sets the "frozen_quota_deducted" field.
func (_c *UserAffiliateReversalCreate) SetFrozenQuotaDeducted(v float64) *UserAffiliateReversalCreate {
	_c.mutation.SetFrozenQuotaDeducted(v)
	return _c
}

// SetNillableFrozenQuotaDeducted sets the "frozen_quota_deducted" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableFrozenQuotaDeducted(v *float64) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetFrozenQuotaDeducted(*v)
	}
	return _c
}

// SetAvailableQuotaDeducted sets the "available_quota_deducted" field.
func (_c *UserAffiliateReversalCreate) SetAvailableQuotaDeducted(v float64) *UserAffiliateReversalCreate {
	_c.mutation.SetAvailableQuotaDeducted(v)
	return _c
}

// SetNillableAvailableQuotaDeducted sets the "available_quota_deducted" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableAvailableQuotaDeducted(v *float64) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetAvailableQuotaDeducted(*v)
	}
	return _c
}

// SetBalanceDeducted sets the "balance_deducted" field.
func (_c *UserAffiliateReversalCreate) SetBalanceDeducted(v float64) *UserAffiliateReversalCreate {
	_c.mutation.SetBalanceDeducted(v)
	return _c
}

// SetNillableBalanceDeducted sets the "balance_deducted" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableBalanceDeducted(v *float64) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetBalanceDeducted(*v)
	}
	return _c
}

// SetTotalRechargedDeducted sets the "total_recharged_deducted" field.
func (_c *UserAffiliateReversalCreate) SetTotalRechargedDeducted(v float64) *UserAffiliateReversalCreate {
	_c.mutation.SetTotalRechargedDeducted(v)
	return _c
}

// SetNillableTotalRechargedDeducted sets the "total_recharged_deducted" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableTotalRechargedDeducted(v *float64) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetTotalRechargedDeducted(*v)
	}
	return _c
}

// SetBalanceBefore sets the "balance_before" field.
func (_c *UserAffiliateReversalCreate) SetBalanceBefore(v float64) *UserAffiliateReversalCreate {
	_c.mutation.SetBalanceBefore(v)
	return _c
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableBalanceBefore(v *float64) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetBalanceBefore(*v)
	}
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *UserAffiliateReversalCreate) SetBalanceAfter(v float64) *UserAffiliateReversalCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableBalanceAfter(v *float64) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetBalanceAfter(*v)
	}
	return _c
}

// SetAffQuotaBefore sets the "aff_quota_before" field.
func (_c *UserAffiliateReversalCreate) SetAffQuotaBefore(v float64) *UserAffiliateReversalCreate {
	_c.mutation.SetAffQuotaBefore(v)
	return _c
}

// SetNillableAffQuotaBefore sets the "aff_quota_before" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableAffQuotaBefore(v *float64) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetAffQuotaBefore(*v)
	}
	return _c
}

// SetAffQuotaAfter sets the "aff_quota_after" field.
func (_c *UserAffiliateReversalCreate) SetAffQuotaAfter(v float64) *UserAffiliateReversalCreate {
	_c.mutation.SetAffQuotaAfter(v)
	return _c
}

// SetNillableAffQuotaAfter sets the "aff_quota_after" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableAffQuotaAfter(v *float64) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetAffQuotaAfter(*v)
	}
	return _c
}

// SetAffFrozenQuotaBefore sets the "aff_frozen_quota_before" field.
func (_c *UserAffiliateReversalCreate) SetAffFrozenQuotaBefore(v float64) *UserAffiliateReversalCreate {
	_c.mutation.SetAffFrozenQuotaBefore(v)
	return _c
}

// SetNillableAffFrozenQuotaBefore sets the "aff_frozen_quota_before" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableAffFrozenQuotaBefore(v *float64) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetAffFrozenQuotaBefore(*v)
	}
	return _c
}

// SetAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field.
func (_c *UserAffiliateReversalCreate) SetAffFrozenQuotaAfter(v float64) *UserAffiliateReversalCreate {
	_c.mutation.SetAffFrozenQuotaAfter(v)
	return _c
}

// SetNillableAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableAffFrozenQuotaAfter(v *float64) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetAffFrozenQuotaAfter(*v)
	}
	return _c
}

// SetAffHistoryQuotaBefore sets the "aff_history_quota_before" field.
func (_c *UserAffiliateReversalCreate) SetAffHistoryQuotaBefore(v float64) *UserAffiliateReversalCreate {
	_c.mutation.SetAffHistoryQuotaBefore(v)
	return _c
}

// SetNillableAffHistoryQuotaBefore sets the "aff_history_quota_before" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableAffHistoryQuotaBefore(v *float64) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetAffHistoryQuotaBefore(*v)
	}
	return _c
}

// SetAffHistoryQuotaAfter sets the "aff_history_quota_after" field.
func (_c *UserAffiliateReversalCreate) SetAffHistoryQuotaAfter(v float64) *UserAffiliateReversalCreate {
	_c.mutation.SetAffHistoryQuotaAfter(v)
	return _c
}

// SetNillableAffHistoryQuotaAfter sets the "aff_history_quota_after" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableAffHistoryQuotaAfter(v *float64) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetAffHistoryQuotaAfter(*v)
	}
	return _c
}

// SetTotalRechargedBefore sets the "total_recharged_before" field.
func (_c *UserAffiliateReversalCreate) SetTotalRechargedBefore(v float64) *UserAffiliateReversalCreate {
	_c.mutation.SetTotalRechargedBefore(v)
	return _c
}

// SetNillableTotalRechargedBefore sets the "total_recharged_before" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableTotalRechargedBefore(v *float64) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetTotalRechargedBefore(*v)
	}
	return _c
}

// SetTotalRechargedAfter sets the "total_recharged_after" field.
func (_c *UserAffiliateReversalCreate) SetTotalRechargedAfter(v float64) *UserAffiliateReversalCreate {
	_c.mutation.SetTotalRechargedAfter(v)
	return _c
}

// SetNillableTotalRechargedAfter sets the "total_recharged_after" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableTotalRechargedAfter(v *float64) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetTotalRechargedAfter(*v)
	}
	return _c
}

// SetSnapshotAvailable sets the "snapshot_available" field.
func (_c *UserAffiliateReversalCreate) SetSnapshotAvailable(v bool) *UserAffiliateReversalCreate {
	_c.mutation.SetSnapshotAvailable(v)
	return _c
}

// SetNillableSnapshotAvailable sets the "snapshot_available" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableSnapshotAvailable(v *bool) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetSnapshotAvailable(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *UserAffiliateReversalCreate) SetReason(v string) *UserAffiliateReversalCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_c *UserAffiliateReversalCreate) SetOperatorUserID(v int64) *UserAffiliateReversalCreate {
	_c.mutation.SetOperatorUserID(v)
	return _c
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableOperatorUserID(v *int64) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetOperatorUserID(*v)
	}
	return _c
}

// SetOperationKeyHash sets the "operation_key_hash" field.
func (_c *UserAffiliateReversalCreate) SetOperationKeyHash(v string) *UserAffiliateReversalCreate {
	_c.mutation.SetOperationKeyHash(v)
	return _c
}

// SetNillableOperationKeyHash sets the "operation_key_hash" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableOperationKeyHash(v *string) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetOperationKeyHash(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserAffiliateReversalCreate) SetCreatedAt(v time.Time) *UserAffiliateReversalCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableCreatedAt(v *time.Time) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserAffiliateReversalCreate) SetUpdatedAt(v time.Time) *UserAffiliateReversalCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserAffiliateReversalCreate) SetNillableUpdatedAt(v *time.Time) *UserAffiliateReversalCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the UserAffiliateReversalMutation object of the builder.
func (_c *UserAffiliateReversalCreate) Mutation() *UserAffiliateReversalMutation {
	return _c.mutation
}

// Save creates the UserAffiliateReversal in the database.
func (_c *UserAffiliateReversalCreate) Save(ctx context.Context) (*UserAffiliateReversal, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserAffiliateReversalCreate) SaveX(ctx context.Context) *UserAffiliateReversal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAffiliateReversalCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAffiliateReversalCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserAffiliateReversalCreate) defaults() {
	if _, ok := _c.mutation.SnapshotAvailable(); !ok {
		v := useraffiliatereversal.DefaultSnapshotAvailable
		_c.mutation.SetSnapshotAvailable(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := useraffiliatereversal.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := useraffiliatereversal.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserAffiliateReversalCreate) check() error {
	if _, ok := _c.mutation.SourceOrderID(); !ok {
		return &ValidationError{Name: "source_order_id", err: errors.New(`ent: missing required field "UserAffiliateReversal.source_order_id"`)}
	}
	if _, ok := _c.mutation.InviterUserID(); !ok {
		return &ValidationError{Name: "inviter_user_id", err: errors.New(`ent: missing required field "UserAffiliateReversal.inviter_user_id"`)}
	}
	if _, ok := _c.mutation.InviteeUserID(); !ok {
		return &ValidationError{Name: "invitee_user_id", err: errors.New(`ent: missing required field "UserAffiliateReversal.invitee_user_id"`)}
	}
	if _, ok := _c.mutation.RebateAmount(); !ok {
		return &ValidationError{Name: "rebate_amount", err: errors.New(`ent: missing required field "UserAffiliateReversal.rebate_amount"`)}
	}
	if _, ok := _c.mutation.SnapshotAvailable(); !ok {
		return &ValidationError{Name: "snapshot_available", err: errors.New(`ent: missing required field "UserAffiliateReversal.snapshot_available"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "UserAffiliateReversal.reason"`)}
	}
	if v, ok := _c.mutation.OperationKeyHash(); ok {
		if err := useraffiliatereversal.OperationKeyHashValidator(v); err != nil {
			return &ValidationError{Name: "operation_key_hash", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateReversal.operation_key_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserAffiliateReversal.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserAffiliateReversal.updated_at"`)}
	}
	return nil
}

func (_c *UserAffiliateReversalCreate) sqlSave(ctx context.Context) (*UserAffiliateReversal, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserAffiliateReversalCreate) createSpec() (*UserAffiliateReversal, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAffiliateReversal{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(useraffiliatereversal.Table, sqlgraph.NewFieldSpec(useraffiliatereversal.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SourceLedgerID(); ok {
		_spec.SetField(useraffiliatereversal.FieldSourceLedgerID, field.TypeInt64, value)
		_node.SourceLedgerID = &value
	}
	if value, ok := _c.mutation.SourceOrderID(); ok {
		_spec.SetField(useraffiliatereversal.FieldSourceOrderID, field.TypeInt64, value)
		_node.SourceOrderID = value
	}
	if value, ok := _c.mutation.InviterUserID(); ok {
		_spec.SetField(useraffiliatereversal.FieldInviterUserID, field.TypeInt64, value)
		_node.InviterUserID = value
	}
	if value, ok := _c.mutation.InviteeUserID(); ok {
		_spec.SetField(useraffiliatereversal.FieldInviteeUserID, field.TypeInt64, value)
		_node.InviteeUserID = value
	}
	if value, ok := _c.mutation.RebateAmount(); ok {
		_spec.SetField(useraffiliatereversal.FieldRebateAmount, field.TypeFloat64, value)
		_node.RebateAmount = value
	}
	if value, ok := _c.mutation.FrozenQuotaDeducted(); ok {
		_spec.SetField(useraffiliatereversal.FieldFrozenQuotaDeducted, field.TypeFloat64, value)
		_node.FrozenQuotaDeducted = &value
	}
	if value, ok := _c.mutation.AvailableQuotaDeducted(); ok {
		_spec.SetField(useraffiliatereversal.FieldAvailableQuotaDeducted, field.TypeFloat64, value)
		_node.AvailableQuotaDeducted = &value
	}
	if value, ok := _c.mutation.BalanceDeducted(); ok {
		_spec.SetField(useraffiliatereversal.FieldBalanceDeducted, field.TypeFloat64, value)
		_node.BalanceDeducted = &value
	}
	if value, ok := _c.mutation.TotalRechargedDeducted(); ok {
		_spec.SetField(useraffiliatereversal.FieldTotalRechargedDeducted, field.TypeFloat64, value)
		_node.TotalRechargedDeducted = &value
	}
	if value, ok := _c.mutation.BalanceBefore(); ok {
		_spec.SetField(useraffiliatereversal.FieldBalanceBefore, field.TypeFloat64, value)
		_node.BalanceBefore = &value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(useraffiliatereversal.FieldBalanceAfter, field.TypeFloat64, value)
		_node.BalanceAfter = &value
	}
	if value, ok := _c.mutation.AffQuotaBefore(); ok {
		_spec.SetField(useraffiliatereversal.FieldAffQuotaBefore, field.TypeFloat64, value)
		_node.AffQuotaBefore = &value
	}
	if value, ok := _c.mutation.AffQuotaAfter(); ok {
		_spec.SetField(useraffiliatereversal.FieldAffQuotaAfter, field.TypeFloat64, value)
		_node.AffQuotaAfter = &value
	}
	if value, ok := _c.mutation.AffFrozenQuotaBefore(); ok {
		_spec.SetField(useraffiliatereversal.FieldAffFrozenQuotaBefore, field.TypeFloat64, value)
		_node.AffFrozenQuotaBefore = &value
	}
	if value, ok := _c.mutation.AffFrozenQuotaAfter(); ok {
		_spec.SetField(useraffiliatereversal.FieldAffFrozenQuotaAfter, field.TypeFloat64, value)
		_node.AffFrozenQuotaAfter = &value
	}
	if value, ok := _c.mutation.AffHistoryQuotaBefore(); ok {
		_spec.SetField(useraffiliatereversal.FieldAffHistoryQuotaBefore, field.TypeFloat64, value)
		_node.AffHistoryQuotaBefore = &value
	}
	if value, ok := _c.mutation.AffHistoryQuotaAfter(); ok {
		_spec.SetField(useraffiliatereversal.FieldAffHistoryQuotaAfter, field.TypeFloat64, value)
		_node.AffHistoryQuotaAfter = &value
	}
	if value, ok := _c.mutation.TotalRechargedBefore(); ok {
		_spec.SetField(useraffiliatereversal.FieldTotalRechargedBefore, field.TypeFloat64, value)
		_node.TotalRechargedBefore = &value
	}
	if value, ok := _c.mutation.TotalRechargedAfter(); ok {
		_spec.SetField(useraffiliatereversal.FieldTotalRechargedAfter, field.TypeFloat64, value)
		_node.TotalRechargedAfter = &value
	}
	if value, ok := _c.mutation.SnapshotAvailable(); ok {
		_spec.SetField(useraffiliatereversal.FieldSnapshotAvailable, field.TypeBool, value)
		_node.SnapshotAvailable = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(useraffiliatereversal.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.OperatorUserID(); ok {
		_spec.SetField(useraffiliatereversal.FieldOperatorUserID, field.TypeInt64, value)
		_node.OperatorUserID = &value
	}
	if value, ok := _c.mutation.OperationKeyHash(); ok {
		_spec.SetField(useraffiliatereversal.FieldOperationKeyHash, field.TypeString, value)
		_node.OperationKeyHash = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(useraffiliatereversal.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(useraffiliatereversal.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserAffiliateReversal.Create().
//		SetSourceLedgerID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserAffiliateReversalUpsert) {
//			SetSourceLedgerID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserAffiliateReversalCreate) OnConflict(opts ...sql.ConflictOption) *UserAffiliateReversalUpsertOne {
	_c.conflict = opts
	return &UserAffiliateReversalUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserAffiliateReversal.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserAffiliateReversalCreate) OnConflictColumns(columns ...string) *UserAffiliateReversalUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserAffiliateReversalUpsertOne{
		create: _c,
	}
}

type (
	// UserAffiliateReversalUpsertOne is the builder for "upsert"-ing
	//  one UserAffiliateReversal node.
	UserAffiliateReversalUpsertOne struct {
		create *UserAffiliateReversalCreate
	}

	// UserAffiliateReversalUpsert is the "OnConflict" setter.
	UserAffiliateReversalUpsert struct {
		*sql.UpdateSet
	}
)

// SetSourceLedgerID sets the "source_ledger_id" field.
func (u *UserAffiliateReversalUpsert) SetSourceLedgerID(v int64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldSourceLedgerID, v)
	return u
}

// UpdateSourceLedgerID sets the "source_ledger_id" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateSourceLedgerID() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldSourceLedgerID)
	return u
}

// AddSourceLedgerID adds v to the "source_ledger_id" field.
func (u *UserAffiliateReversalUpsert) AddSourceLedgerID(v int64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldSourceLedgerID, v)
	return u
}

// ClearSourceLedgerID clears the value of the "source_ledger_id" field.
func (u *UserAffiliateReversalUpsert) ClearSourceLedgerID() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldSourceLedgerID)
	return u
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *UserAffiliateReversalUpsert) SetSourceOrderID(v int64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldSourceOrderID, v)
	return u
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateSourceOrderID() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldSourceOrderID)
	return u
}

// AddSourceOrderID adds v to the "source_order_id" field.
func (u *UserAffiliateReversalUpsert) AddSourceOrderID(v int64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldSourceOrderID, v)
	return u
}

// SetInviterUserID sets the "inviter_user_id" field.
func (u *UserAffiliateReversalUpsert) SetInviterUserID(v int64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldInviterUserID, v)
	return u
}

// UpdateInviterUserID sets the "inviter_user_id" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateInviterUserID() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldInviterUserID)
	return u
}

// AddInviterUserID adds v to the "inviter_user_id" field.
func (u *UserAffiliateReversalUpsert) AddInviterUserID(v int64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldInviterUserID, v)
	return u
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (u *UserAffiliateReversalUpsert) SetInviteeUserID(v int64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldInviteeUserID, v)
	return u
}

// UpdateInviteeUserID sets the "invitee_user_id" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateInviteeUserID() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldInviteeUserID)
	return u
}

// AddInviteeUserID adds v to the "invitee_user_id" field.
func (u *UserAffiliateReversalUpsert) AddInviteeUserID(v int64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldInviteeUserID, v)
	return u
}

// SetRebateAmount sets the "rebate_amount" field.
func (u *UserAffiliateReversalUpsert) SetRebateAmount(v float64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldRebateAmount, v)
	return u
}

// UpdateRebateAmount sets the "rebate_amount" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateRebateAmount() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldRebateAmount)
	return u
}

// AddRebateAmount adds v to the "rebate_amount" field.
func (u *UserAffiliateReversalUpsert) AddRebateAmount(v float64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldRebateAmount, v)
	return u
}

// SetFrozenQuotaDeducted sets the "frozen_quota_deducted" field.
func (u *UserAffiliateReversalUpsert) SetFrozenQuotaDeducted(v float64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldFrozenQuotaDeducted, v)
	return u
}

// UpdateFrozenQuotaDeducted sets the "frozen_quota_deducted" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateFrozenQuotaDeducted() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldFrozenQuotaDeducted)
	return u
}

// AddFrozenQuotaDeducted adds v to the "frozen_quota_deducted" field.
func (u *UserAffiliateReversalUpsert) AddFrozenQuotaDeducted(v float64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldFrozenQuotaDeducted, v)
	return u
}

// ClearFrozenQuotaDeducted clears the value of the "frozen_quota_deducted" field.
func (u *UserAffiliateReversalUpsert) ClearFrozenQuotaDeducted() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldFrozenQuotaDeducted)
	return u
}

// SetAvailableQuotaDeducted sets the "available_quota_deducted" field.
func (u *UserAffiliateReversalUpsert) SetAvailableQuotaDeducted(v float64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldAvailableQuotaDeducted, v)
	return u
}

// UpdateAvailableQuotaDeducted sets the "available_quota_deducted" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateAvailableQuotaDeducted() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldAvailableQuotaDeducted)
	return u
}

// AddAvailableQuotaDeducted adds v to the "available_quota_deducted" field.
func (u *UserAffiliateReversalUpsert) AddAvailableQuotaDeducted(v float64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldAvailableQuotaDeducted, v)
	return u
}

// ClearAvailableQuotaDeducted clears the value of the "available_quota_deducted" field.
func (u *UserAffiliateReversalUpsert) ClearAvailableQuotaDeducted() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldAvailableQuotaDeducted)
	return u
}

// SetBalanceDeducted sets the "balance_deducted" field.
func (u *UserAffiliateReversalUpsert) SetBalanceDeducted(v float64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldBalanceDeducted, v)
	return u
}

// UpdateBalanceDeducted sets the "balance_deducted" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateBalanceDeducted() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldBalanceDeducted)
	return u
}

// AddBalanceDeducted adds v to the "balance_deducted" field.
func (u *UserAffiliateReversalUpsert) AddBalanceDeducted(v float64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldBalanceDeducted, v)
	return u
}

// ClearBalanceDeducted clears the value of the "balance_deducted" field.
func (u *UserAffiliateReversalUpsert) ClearBalanceDeducted() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldBalanceDeducted)
	return u
}

// SetTotalRechargedDeducted sets the "total_recharged_deducted" field.
func (u *UserAffiliateReversalUpsert) SetTotalRechargedDeducted(v float64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldTotalRechargedDeducted, v)
	return u
}

// UpdateTotalRechargedDeducted sets the "total_recharged_deducted" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateTotalRechargedDeducted() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldTotalRechargedDeducted)
	return u
}

// AddTotalRechargedDeducted adds v to the "total_recharged_deducted" field.
func (u *UserAffiliateReversalUpsert) AddTotalRechargedDeducted(v float64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldTotalRechargedDeducted, v)
	return u
}

// ClearTotalRechargedDeducted clears the value of the "total_recharged_deducted" field.
func (u *UserAffiliateReversalUpsert) ClearTotalRechargedDeducted() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldTotalRechargedDeducted)
	return u
}

// SetBalanceBefore sets the "balance_before" field.
func (u *UserAffiliateReversalUpsert) SetBalanceBefore(v float64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldBalanceBefore, v)
	return u
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateBalanceBefore() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldBalanceBefore)
	return u
}

// AddBalanceBefore adds v to the "balance_before" field.
func (u *UserAffiliateReversalUpsert) AddBalanceBefore(v float64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldBalanceBefore, v)
	return u
}

// ClearBalanceBefore clears the value of the "balance_before" field.
func (u *UserAffiliateReversalUpsert) ClearBalanceBefore() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldBalanceBefore)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *UserAffiliateReversalUpsert) SetBalanceAfter(v float64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateBalanceAfter() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldBalanceAfter)
	return u
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *UserAffiliateReversalUpsert) AddBalanceAfter(v float64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldBalanceAfter, v)
	return u
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (u *UserAffiliateReversalUpsert) ClearBalanceAfter() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldBalanceAfter)
	return u
}

// SetAffQuotaBefore sets the "aff_quota_before" field.
func (u *UserAffiliateReversalUpsert) SetAffQuotaBefore(v float64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldAffQuotaBefore, v)
	return u
}

// UpdateAffQuotaBefore sets the "aff_quota_before" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateAffQuotaBefore() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldAffQuotaBefore)
	return u
}

// AddAffQuotaBefore adds v to the "aff_quota_before" field.
func (u *UserAffiliateReversalUpsert) AddAffQuotaBefore(v float64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldAffQuotaBefore, v)
	return u
}

// ClearAffQuotaBefore clears the value of the "aff_quota_before" field.
func (u *UserAffiliateReversalUpsert) ClearAffQuotaBefore() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldAffQuotaBefore)
	return u
}

// SetAffQuotaAfter sets the "aff_quota_after" field.
func (u *UserAffiliateReversalUpsert) SetAffQuotaAfter(v float64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldAffQuotaAfter, v)
	return u
}

// UpdateAffQuotaAfter sets the "aff_quota_after" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateAffQuotaAfter() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldAffQuotaAfter)
	return u
}

// AddAffQuotaAfter adds v to the "aff_quota_after" field.
func (u *UserAffiliateReversalUpsert) AddAffQuotaAfter(v float64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldAffQuotaAfter, v)
	return u
}

// ClearAffQuotaAfter clears the value of the "aff_quota_after" field.
func (u *UserAffiliateReversalUpsert) ClearAffQuotaAfter() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldAffQuotaAfter)
	return u
}

// SetAffFrozenQuotaBefore sets the "aff_frozen_quota_before" field.
func (u *UserAffiliateReversalUpsert) SetAffFrozenQuotaBefore(v float64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldAffFrozenQuotaBefore, v)
	return u
}

// UpdateAffFrozenQuotaBefore sets the "aff_frozen_quota_before" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateAffFrozenQuotaBefore() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldAffFrozenQuotaBefore)
	return u
}

// AddAffFrozenQuotaBefore adds v to the "aff_frozen_quota_before" field.
func (u *UserAffiliateReversalUpsert) AddAffFrozenQuotaBefore(v float64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldAffFrozenQuotaBefore, v)
	return u
}

// ClearAffFrozenQuotaBefore clears the value of the "aff_frozen_quota_before" field.
func (u *UserAffiliateReversalUpsert) ClearAffFrozenQuotaBefore() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldAffFrozenQuotaBefore)
	return u
}

// SetAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field.
func (u *UserAffiliateReversalUpsert) SetAffFrozenQuotaAfter(v float64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldAffFrozenQuotaAfter, v)
	return u
}

// UpdateAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateAffFrozenQuotaAfter() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldAffFrozenQuotaAfter)
	return u
}

// AddAffFrozenQuotaAfter adds v to the "aff_frozen_quota_after" field.
func (u *UserAffiliateReversalUpsert) AddAffFrozenQuotaAfter(v float64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldAffFrozenQuotaAfter, v)
	return u
}

// ClearAffFrozenQuotaAfter clears the value of the "aff_frozen_quota_after" field.
func (u *UserAffiliateReversalUpsert) ClearAffFrozenQuotaAfter() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldAffFrozenQuotaAfter)
	return u
}

// SetAffHistoryQuotaBefore sets the "aff_history_quota_before" field.
func (u *UserAffiliateReversalUpsert) SetAffHistoryQuotaBefore(v float64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldAffHistoryQuotaBefore, v)
	return u
}

// UpdateAffHistoryQuotaBefore sets the "aff_history_quota_before" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateAffHistoryQuotaBefore() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldAffHistoryQuotaBefore)
	return u
}

// AddAffHistoryQuotaBefore adds v to the "aff_history_quota_before" field.
func (u *UserAffiliateReversalUpsert) AddAffHistoryQuotaBefore(v float64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldAffHistoryQuotaBefore, v)
	return u
}

// ClearAffHistoryQuotaBefore clears the value of the "aff_history_quota_before" field.
func (u *UserAffiliateReversalUpsert) ClearAffHistoryQuotaBefore() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldAffHistoryQuotaBefore)
	return u
}

// SetAffHistoryQuotaAfter sets the "aff_history_quota_after" field.
func (u *UserAffiliateReversalUpsert) SetAffHistoryQuotaAfter(v float64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldAffHistoryQuotaAfter, v)
	return u
}

// UpdateAffHistoryQuotaAfter sets the "aff_history_quota_after" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateAffHistoryQuotaAfter() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldAffHistoryQuotaAfter)
	return u
}

// AddAffHistoryQuotaAfter adds v to the "aff_history_quota_after" field.
func (u *UserAffiliateReversalUpsert) AddAffHistoryQuotaAfter(v float64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldAffHistoryQuotaAfter, v)
	return u
}

// ClearAffHistoryQuotaAfter clears the value of the "aff_history_quota_after" field.
func (u *UserAffiliateReversalUpsert) ClearAffHistoryQuotaAfter() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldAffHistoryQuotaAfter)
	return u
}

// SetTotalRechargedBefore sets the "total_recharged_before" field.
func (u *UserAffiliateReversalUpsert) SetTotalRechargedBefore(v float64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldTotalRechargedBefore, v)
	return u
}

// UpdateTotalRechargedBefore sets the "total_recharged_before" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateTotalRechargedBefore() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldTotalRechargedBefore)
	return u
}

// AddTotalRechargedBefore adds v to the "total_recharged_before" field.
func (u *UserAffiliateReversalUpsert) AddTotalRechargedBefore(v float64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldTotalRechargedBefore, v)
	return u
}

// ClearTotalRechargedBefore clears the value of the "total_recharged_before" field.
func (u *UserAffiliateReversalUpsert) ClearTotalRechargedBefore() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldTotalRechargedBefore)
	return u
}

// SetTotalRechargedAfter sets the "total_recharged_after" field.
func (u *UserAffiliateReversalUpsert) SetTotalRechargedAfter(v float64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldTotalRechargedAfter, v)
	return u
}

// UpdateTotalRechargedAfter sets the "total_recharged_after" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateTotalRechargedAfter() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldTotalRechargedAfter)
	return u
}

// AddTotalRechargedAfter adds v to the "total_recharged_after" field.
func (u *UserAffiliateReversalUpsert) AddTotalRechargedAfter(v float64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldTotalRechargedAfter, v)
	return u
}

// ClearTotalRechargedAfter clears the value of the "total_recharged_after" field.
func (u *UserAffiliateReversalUpsert) ClearTotalRechargedAfter() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldTotalRechargedAfter)
	return u
}

// SetSnapshotAvailable sets the "snapshot_available" field.
func (u *UserAffiliateReversalUpsert) SetSnapshotAvailable(v bool) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldSnapshotAvailable, v)
	return u
}

// UpdateSnapshotAvailable sets the "snapshot_available" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateSnapshotAvailable() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldSnapshotAvailable)
	return u
}

// SetReason sets the "reason" field.
func (u *UserAffiliateReversalUpsert) SetReason(v string) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateReason() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldReason)
	return u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *UserAffiliateReversalUpsert) SetOperatorUserID(v int64) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldOperatorUserID, v)
	return u
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateOperatorUserID() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldOperatorUserID)
	return u
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *UserAffiliateReversalUpsert) AddOperatorUserID(v int64) *UserAffiliateReversalUpsert {
	u.Add(useraffiliatereversal.FieldOperatorUserID, v)
	return u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *UserAffiliateReversalUpsert) ClearOperatorUserID() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldOperatorUserID)
	return u
}

// SetOperationKeyHash sets the "operation_key_hash" field.
func (u *UserAffiliateReversalUpsert) SetOperationKeyHash(v string) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldOperationKeyHash, v)
	return u
}

// UpdateOperationKeyHash sets the "operation_key_hash" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateOperationKeyHash() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldOperationKeyHash)
	return u
}

// ClearOperationKeyHash clears the value of the "operation_key_hash" field.
func (u *UserAffiliateReversalUpsert) ClearOperationKeyHash() *UserAffiliateReversalUpsert {
	u.SetNull(useraffiliatereversal.FieldOperationKeyHash)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAffiliateReversalUpsert) SetUpdatedAt(v time.Time) *UserAffiliateReversalUpsert {
	u.Set(useraffiliatereversal.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsert) UpdateUpdatedAt() *UserAffiliateReversalUpsert {
	u.SetExcluded(useraffiliatereversal.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserAffiliateReversal.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserAffiliateReversalUpsertOne) UpdateNewValues() *UserAffiliateReversalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(useraffiliatereversal.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserAffiliateReversal.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserAffiliateReversalUpsertOne) Ignore() *UserAffiliateReversalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserAffiliateReversalUpsertOne) DoNothing() *UserAffiliateReversalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserAffiliateReversalCreate.OnConflict
// documentation for more info.
func (u *UserAffiliateReversalUpsertOne) Update(set func(*UserAffiliateReversalUpsert)) *UserAffiliateReversalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserAffiliateReversalUpsert{UpdateSet: update})
	}))
	return u
}

// SetSourceLedgerID sets the "source_ledger_id" field.
func (u *UserAffiliateReversalUpsertOne) SetSourceLedgerID(v int64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetSourceLedgerID(v)
	})
}

// AddSourceLedgerID adds v to the "source_ledger_id" field.
func (u *UserAffiliateReversalUpsertOne) AddSourceLedgerID(v int64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddSourceLedgerID(v)
	})
}

// UpdateSourceLedgerID sets the "source_ledger_id" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateSourceLedgerID() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateSourceLedgerID()
	})
}

// ClearSourceLedgerID clears the value of the "source_ledger_id" field.
func (u *UserAffiliateReversalUpsertOne) ClearSourceLedgerID() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearSourceLedgerID()
	})
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *UserAffiliateReversalUpsertOne) SetSourceOrderID(v int64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetSourceOrderID(v)
	})
}

// AddSourceOrderID adds v to the "source_order_id" field.
func (u *UserAffiliateReversalUpsertOne) AddSourceOrderID(v int64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddSourceOrderID(v)
	})
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateSourceOrderID() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateSourceOrderID()
	})
}

// SetInviterUserID sets the "inviter_user_id" field.
func (u *UserAffiliateReversalUpsertOne) SetInviterUserID(v int64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetInviterUserID(v)
	})
}

// AddInviterUserID adds v to the "inviter_user_id" field.
func (u *UserAffiliateReversalUpsertOne) AddInviterUserID(v int64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddInviterUserID(v)
	})
}

// UpdateInviterUserID sets the "inviter_user_id" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateInviterUserID() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateInviterUserID()
	})
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (u *UserAffiliateReversalUpsertOne) SetInviteeUserID(v int64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetInviteeUserID(v)
	})
}

// AddInviteeUserID adds v to the "invitee_user_id" field.
func (u *UserAffiliateReversalUpsertOne) AddInviteeUserID(v int64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddInviteeUserID(v)
	})
}

// UpdateInviteeUserID sets the "invitee_user_id" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateInviteeUserID() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateInviteeUserID()
	})
}

// SetRebateAmount sets the "rebate_amount" field.
func (u *UserAffiliateReversalUpsertOne) SetRebateAmount(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetRebateAmount(v)
	})
}

// AddRebateAmount adds v to the "rebate_amount" field.
func (u *UserAffiliateReversalUpsertOne) AddRebateAmount(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddRebateAmount(v)
	})
}

// UpdateRebateAmount sets the "rebate_amount" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateRebateAmount() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateRebateAmount()
	})
}

// SetFrozenQuotaDeducted sets the "frozen_quota_deducted" field.
func (u *UserAffiliateReversalUpsertOne) SetFrozenQuotaDeducted(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetFrozenQuotaDeducted(v)
	})
}

// AddFrozenQuotaDeducted adds v to the "frozen_quota_deducted" field.
func (u *UserAffiliateReversalUpsertOne) AddFrozenQuotaDeducted(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddFrozenQuotaDeducted(v)
	})
}

// UpdateFrozenQuotaDeducted sets the "frozen_quota_deducted" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateFrozenQuotaDeducted() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateFrozenQuotaDeducted()
	})
}

// ClearFrozenQuotaDeducted clears the value of the "frozen_quota_deducted" field.
func (u *UserAffiliateReversalUpsertOne) ClearFrozenQuotaDeducted() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearFrozenQuotaDeducted()
	})
}

// SetAvailableQuotaDeducted sets the "available_quota_deducted" field.
func (u *UserAffiliateReversalUpsertOne) SetAvailableQuotaDeducted(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetAvailableQuotaDeducted(v)
	})
}

// AddAvailableQuotaDeducted adds v to the "available_quota_deducted" field.
func (u *UserAffiliateReversalUpsertOne) AddAvailableQuotaDeducted(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddAvailableQuotaDeducted(v)
	})
}

// UpdateAvailableQuotaDeducted sets the "available_quota_deducted" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateAvailableQuotaDeducted() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateAvailableQuotaDeducted()
	})
}

// ClearAvailableQuotaDeducted clears the value of the "available_quota_deducted" field.
func (u *UserAffiliateReversalUpsertOne) ClearAvailableQuotaDeducted() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearAvailableQuotaDeducted()
	})
}

// SetBalanceDeducted sets the "balance_deducted" field.
func (u *UserAffiliateReversalUpsertOne) SetBalanceDeducted(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetBalanceDeducted(v)
	})
}

// AddBalanceDeducted adds v to the "balance_deducted" field.
func (u *UserAffiliateReversalUpsertOne) AddBalanceDeducted(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddBalanceDeducted(v)
	})
}

// UpdateBalanceDeducted sets the "balance_deducted" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateBalanceDeducted() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateBalanceDeducted()
	})
}

// ClearBalanceDeducted clears the value of the "balance_deducted" field.
func (u *UserAffiliateReversalUpsertOne) ClearBalanceDeducted() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearBalanceDeducted()
	})
}

// SetTotalRechargedDeducted sets the "total_recharged_deducted" field.
func (u *UserAffiliateReversalUpsertOne) SetTotalRechargedDeducted(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetTotalRechargedDeducted(v)
	})
}

// AddTotalRechargedDeducted adds v to the "total_recharged_deducted" field.
func (u *UserAffiliateReversalUpsertOne) AddTotalRechargedDeducted(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddTotalRechargedDeducted(v)
	})
}

// UpdateTotalRechargedDeducted sets the "total_recharged_deducted" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateTotalRechargedDeducted() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateTotalRechargedDeducted()
	})
}

// ClearTotalRechargedDeducted clears the value of the "total_recharged_deducted" field.
func (u *UserAffiliateReversalUpsertOne) ClearTotalRechargedDeducted() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearTotalRechargedDeducted()
	})
}

// SetBalanceBefore sets the "balance_before" field.
func (u *UserAffiliateReversalUpsertOne) SetBalanceBefore(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetBalanceBefore(v)
	})
}

// AddBalanceBefore adds v to the "balance_before" field.
func (u *UserAffiliateReversalUpsertOne) AddBalanceBefore(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddBalanceBefore(v)
	})
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateBalanceBefore() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateBalanceBefore()
	})
}

// ClearBalanceBefore clears the value of the "balance_before" field.
func (u *UserAffiliateReversalUpsertOne) ClearBalanceBefore() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearBalanceBefore()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *UserAffiliateReversalUpsertOne) SetBalanceAfter(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *UserAffiliateReversalUpsertOne) AddBalanceAfter(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateBalanceAfter() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateBalanceAfter()
	})
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (u *UserAffiliateReversalUpsertOne) ClearBalanceAfter() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearBalanceAfter()
	})
}

// SetAffQuotaBefore sets the "aff_quota_before" field.
func (u *UserAffiliateReversalUpsertOne) SetAffQuotaBefore(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetAffQuotaBefore(v)
	})
}

// AddAffQuotaBefore adds v to the "aff_quota_before" field.
func (u *UserAffiliateReversalUpsertOne) AddAffQuotaBefore(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddAffQuotaBefore(v)
	})
}

// UpdateAffQuotaBefore sets the "aff_quota_before" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateAffQuotaBefore() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateAffQuotaBefore()
	})
}

// ClearAffQuotaBefore clears the value of the "aff_quota_before" field.
func (u *UserAffiliateReversalUpsertOne) ClearAffQuotaBefore() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearAffQuotaBefore()
	})
}

// SetAffQuotaAfter sets the "aff_quota_after" field.
func (u *UserAffiliateReversalUpsertOne) SetAffQuotaAfter(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetAffQuotaAfter(v)
	})
}

// AddAffQuotaAfter adds v to the "aff_quota_after" field.
func (u *UserAffiliateReversalUpsertOne) AddAffQuotaAfter(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddAffQuotaAfter(v)
	})
}

// UpdateAffQuotaAfter sets the "aff_quota_after" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateAffQuotaAfter() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateAffQuotaAfter()
	})
}

// ClearAffQuotaAfter clears the value of the "aff_quota_after" field.
func (u *UserAffiliateReversalUpsertOne) ClearAffQuotaAfter() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearAffQuotaAfter()
	})
}

// SetAffFrozenQuotaBefore sets the "aff_frozen_quota_before" field.
func (u *UserAffiliateReversalUpsertOne) SetAffFrozenQuotaBefore(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetAffFrozenQuotaBefore(v)
	})
}

// AddAffFrozenQuotaBefore adds v to the "aff_frozen_quota_before" field.
func (u *UserAffiliateReversalUpsertOne) AddAffFrozenQuotaBefore(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddAffFrozenQuotaBefore(v)
	})
}

// UpdateAffFrozenQuotaBefore sets the "aff_frozen_quota_before" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateAffFrozenQuotaBefore() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateAffFrozenQuotaBefore()
	})
}

// ClearAffFrozenQuotaBefore clears the value of the "aff_frozen_quota_before" field.
func (u *UserAffiliateReversalUpsertOne) ClearAffFrozenQuotaBefore() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearAffFrozenQuotaBefore()
	})
}

// SetAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field.
func (u *UserAffiliateReversalUpsertOne) SetAffFrozenQuotaAfter(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetAffFrozenQuotaAfter(v)
	})
}

// AddAffFrozenQuotaAfter adds v to the "aff_frozen_quota_after" field.
func (u *UserAffiliateReversalUpsertOne) AddAffFrozenQuotaAfter(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddAffFrozenQuotaAfter(v)
	})
}

// UpdateAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateAffFrozenQuotaAfter() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateAffFrozenQuotaAfter()
	})
}

// ClearAffFrozenQuotaAfter clears the value of the "aff_frozen_quota_after" field.
func (u *UserAffiliateReversalUpsertOne) ClearAffFrozenQuotaAfter() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearAffFrozenQuotaAfter()
	})
}

// SetAffHistoryQuotaBefore sets the "aff_history_quota_before" field.
func (u *UserAffiliateReversalUpsertOne) SetAffHistoryQuotaBefore(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetAffHistoryQuotaBefore(v)
	})
}

// AddAffHistoryQuotaBefore adds v to the "aff_history_quota_before" field.
func (u *UserAffiliateReversalUpsertOne) AddAffHistoryQuotaBefore(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddAffHistoryQuotaBefore(v)
	})
}

// UpdateAffHistoryQuotaBefore sets the "aff_history_quota_before" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateAffHistoryQuotaBefore() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateAffHistoryQuotaBefore()
	})
}

// ClearAffHistoryQuotaBefore clears the value of the "aff_history_quota_before" field.
func (u *UserAffiliateReversalUpsertOne) ClearAffHistoryQuotaBefore() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearAffHistoryQuotaBefore()
	})
}

// SetAffHistoryQuotaAfter sets the "aff_history_quota_after" field.
func (u *UserAffiliateReversalUpsertOne) SetAffHistoryQuotaAfter(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetAffHistoryQuotaAfter(v)
	})
}

// AddAffHistoryQuotaAfter adds v to the "aff_history_quota_after" field.
func (u *UserAffiliateReversalUpsertOne) AddAffHistoryQuotaAfter(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddAffHistoryQuotaAfter(v)
	})
}

// UpdateAffHistoryQuotaAfter sets the "aff_history_quota_after" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateAffHistoryQuotaAfter() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateAffHistoryQuotaAfter()
	})
}

// ClearAffHistoryQuotaAfter clears the value of the "aff_history_quota_after" field.
func (u *UserAffiliateReversalUpsertOne) ClearAffHistoryQuotaAfter() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearAffHistoryQuotaAfter()
	})
}

// SetTotalRechargedBefore sets the "total_recharged_before" field.
func (u *UserAffiliateReversalUpsertOne) SetTotalRechargedBefore(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetTotalRechargedBefore(v)
	})
}

// AddTotalRechargedBefore adds v to the "total_recharged_before" field.
func (u *UserAffiliateReversalUpsertOne) AddTotalRechargedBefore(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddTotalRechargedBefore(v)
	})
}

// UpdateTotalRechargedBefore sets the "total_recharged_before" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateTotalRechargedBefore() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateTotalRechargedBefore()
	})
}

// ClearTotalRechargedBefore clears the value of the "total_recharged_before" field.
func (u *UserAffiliateReversalUpsertOne) ClearTotalRechargedBefore() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearTotalRechargedBefore()
	})
}

// SetTotalRechargedAfter sets the "total_recharged_after" field.
func (u *UserAffiliateReversalUpsertOne) SetTotalRechargedAfter(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetTotalRechargedAfter(v)
	})
}

// AddTotalRechargedAfter adds v to the "total_recharged_after" field.
func (u *UserAffiliateReversalUpsertOne) AddTotalRechargedAfter(v float64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddTotalRechargedAfter(v)
	})
}

// UpdateTotalRechargedAfter sets the "total_recharged_after" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateTotalRechargedAfter() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateTotalRechargedAfter()
	})
}

// ClearTotalRechargedAfter clears the value of the "total_recharged_after" field.
func (u *UserAffiliateReversalUpsertOne) ClearTotalRechargedAfter() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearTotalRechargedAfter()
	})
}

// SetSnapshotAvailable sets the "snapshot_available" field.
func (u *UserAffiliateReversalUpsertOne) SetSnapshotAvailable(v bool) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetSnapshotAvailable(v)
	})
}

// UpdateSnapshotAvailable sets the "snapshot_available" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateSnapshotAvailable() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateSnapshotAvailable()
	})
}

// SetReason sets the "reason" field.
func (u *UserAffiliateReversalUpsertOne) SetReason(v string) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateReason() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateReason()
	})
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *UserAffiliateReversalUpsertOne) SetOperatorUserID(v int64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetOperatorUserID(v)
	})
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *UserAffiliateReversalUpsertOne) AddOperatorUserID(v int64) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddOperatorUserID(v)
	})
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateOperatorUserID() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateOperatorUserID()
	})
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *UserAffiliateReversalUpsertOne) ClearOperatorUserID() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearOperatorUserID()
	})
}

// SetOperationKeyHash sets the "operation_key_hash" field.
func (u *UserAffiliateReversalUpsertOne) SetOperationKeyHash(v string) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetOperationKeyHash(v)
	})
}

// UpdateOperationKeyHash sets the "operation_key_hash" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateOperationKeyHash() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateOperationKeyHash()
	})
}

// ClearOperationKeyHash clears the value of the "operation_key_hash" field.
func (u *UserAffiliateReversalUpsertOne) ClearOperationKeyHash() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearOperationKeyHash()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAffiliateReversalUpsertOne) SetUpdatedAt(v time.Time) *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertOne) UpdateUpdatedAt() *UserAffiliateReversalUpsertOne {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserAffiliateReversalUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserAffiliateReversalCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserAffiliateReversalUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserAffiliateReversalUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserAffiliateReversalUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserAffiliateReversalCreateBulk is the builder for creating many UserAffiliateReversal entities in bulk.
type UserAffiliateReversalCreateBulk struct {
	config
	err      error
	builders []*UserAffiliateReversalCreate
	conflict []sql.ConflictOption
}

// Save creates the UserAffiliateReversal entities in the database.
func (_c *UserAffiliateReversalCreateBulk) Save(ctx context.Context) ([]*UserAffiliateReversal, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserAffiliateReversal, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAffiliateReversalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserAffiliateReversalCreateBulk) SaveX(ctx context.Context) []*UserAffiliateReversal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAffiliateReversalCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAffiliateReversalCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserAffiliateReversal.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserAffiliateReversalUpsert) {
//			SetSourceLedgerID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserAffiliateReversalCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserAffiliateReversalUpsertBulk {
	_c.conflict = opts
	return &UserAffiliateReversalUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserAffiliateReversal.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserAffiliateReversalCreateBulk) OnConflictColumns(columns ...string) *UserAffiliateReversalUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserAffiliateReversalUpsertBulk{
		create: _c,
	}
}

// UserAffiliateReversalUpsertBulk is the builder for "upsert"-ing
// a bulk of UserAffiliateReversal nodes.
type UserAffiliateReversalUpsertBulk struct {
	create *UserAffiliateReversalCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserAffiliateReversal.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserAffiliateReversalUpsertBulk) UpdateNewValues() *UserAffiliateReversalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(useraffiliatereversal.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserAffiliateReversal.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserAffiliateReversalUpsertBulk) Ignore() *UserAffiliateReversalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserAffiliateReversalUpsertBulk) DoNothing() *UserAffiliateReversalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserAffiliateReversalCreateBulk.OnConflict
// documentation for more info.
func (u *UserAffiliateReversalUpsertBulk) Update(set func(*UserAffiliateReversalUpsert)) *UserAffiliateReversalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserAffiliateReversalUpsert{UpdateSet: update})
	}))
	return u
}

// SetSourceLedgerID sets the "source_ledger_id" field.
func (u *UserAffiliateReversalUpsertBulk) SetSourceLedgerID(v int64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetSourceLedgerID(v)
	})
}

// AddSourceLedgerID adds v to the "source_ledger_id" field.
func (u *UserAffiliateReversalUpsertBulk) AddSourceLedgerID(v int64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddSourceLedgerID(v)
	})
}

// UpdateSourceLedgerID sets the "source_ledger_id" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateSourceLedgerID() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateSourceLedgerID()
	})
}

// ClearSourceLedgerID clears the value of the "source_ledger_id" field.
func (u *UserAffiliateReversalUpsertBulk) ClearSourceLedgerID() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearSourceLedgerID()
	})
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *UserAffiliateReversalUpsertBulk) SetSourceOrderID(v int64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetSourceOrderID(v)
	})
}

// AddSourceOrderID adds v to the "source_order_id" field.
func (u *UserAffiliateReversalUpsertBulk) AddSourceOrderID(v int64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddSourceOrderID(v)
	})
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateSourceOrderID() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateSourceOrderID()
	})
}

// SetInviterUserID sets the "inviter_user_id" field.
func (u *UserAffiliateReversalUpsertBulk) SetInviterUserID(v int64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetInviterUserID(v)
	})
}

// AddInviterUserID adds v to the "inviter_user_id" field.
func (u *UserAffiliateReversalUpsertBulk) AddInviterUserID(v int64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddInviterUserID(v)
	})
}

// UpdateInviterUserID sets the "inviter_user_id" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateInviterUserID() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateInviterUserID()
	})
}

// SetInviteeUserID sets the "invitee_user_id" field.
func (u *UserAffiliateReversalUpsertBulk) SetInviteeUserID(v int64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetInviteeUserID(v)
	})
}

// AddInviteeUserID adds v to the "invitee_user_id" field.
func (u *UserAffiliateReversalUpsertBulk) AddInviteeUserID(v int64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddInviteeUserID(v)
	})
}

// UpdateInviteeUserID sets the "invitee_user_id" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateInviteeUserID() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateInviteeUserID()
	})
}

// SetRebateAmount sets the "rebate_amount" field.
func (u *UserAffiliateReversalUpsertBulk) SetRebateAmount(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetRebateAmount(v)
	})
}

// AddRebateAmount adds v to the "rebate_amount" field.
func (u *UserAffiliateReversalUpsertBulk) AddRebateAmount(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddRebateAmount(v)
	})
}

// UpdateRebateAmount sets the "rebate_amount" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateRebateAmount() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateRebateAmount()
	})
}

// SetFrozenQuotaDeducted sets the "frozen_quota_deducted" field.
func (u *UserAffiliateReversalUpsertBulk) SetFrozenQuotaDeducted(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetFrozenQuotaDeducted(v)
	})
}

// AddFrozenQuotaDeducted adds v to the "frozen_quota_deducted" field.
func (u *UserAffiliateReversalUpsertBulk) AddFrozenQuotaDeducted(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddFrozenQuotaDeducted(v)
	})
}

// UpdateFrozenQuotaDeducted sets the "frozen_quota_deducted" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateFrozenQuotaDeducted() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateFrozenQuotaDeducted()
	})
}

// ClearFrozenQuotaDeducted clears the value of the "frozen_quota_deducted" field.
func (u *UserAffiliateReversalUpsertBulk) ClearFrozenQuotaDeducted() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearFrozenQuotaDeducted()
	})
}

// SetAvailableQuotaDeducted sets the "available_quota_deducted" field.
func (u *UserAffiliateReversalUpsertBulk) SetAvailableQuotaDeducted(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetAvailableQuotaDeducted(v)
	})
}

// AddAvailableQuotaDeducted adds v to the "available_quota_deducted" field.
func (u *UserAffiliateReversalUpsertBulk) AddAvailableQuotaDeducted(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddAvailableQuotaDeducted(v)
	})
}

// UpdateAvailableQuotaDeducted sets the "available_quota_deducted" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateAvailableQuotaDeducted() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateAvailableQuotaDeducted()
	})
}

// ClearAvailableQuotaDeducted clears the value of the "available_quota_deducted" field.
func (u *UserAffiliateReversalUpsertBulk) ClearAvailableQuotaDeducted() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearAvailableQuotaDeducted()
	})
}

// SetBalanceDeducted sets the "balance_deducted" field.
func (u *UserAffiliateReversalUpsertBulk) SetBalanceDeducted(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetBalanceDeducted(v)
	})
}

// AddBalanceDeducted adds v to the "balance_deducted" field.
func (u *UserAffiliateReversalUpsertBulk) AddBalanceDeducted(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddBalanceDeducted(v)
	})
}

// UpdateBalanceDeducted sets the "balance_deducted" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateBalanceDeducted() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateBalanceDeducted()
	})
}

// ClearBalanceDeducted clears the value of the "balance_deducted" field.
func (u *UserAffiliateReversalUpsertBulk) ClearBalanceDeducted() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearBalanceDeducted()
	})
}

// SetTotalRechargedDeducted sets the "total_recharged_deducted" field.
func (u *UserAffiliateReversalUpsertBulk) SetTotalRechargedDeducted(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetTotalRechargedDeducted(v)
	})
}

// AddTotalRechargedDeducted adds v to the "total_recharged_deducted" field.
func (u *UserAffiliateReversalUpsertBulk) AddTotalRechargedDeducted(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddTotalRechargedDeducted(v)
	})
}

// UpdateTotalRechargedDeducted sets the "total_recharged_deducted" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateTotalRechargedDeducted() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateTotalRechargedDeducted()
	})
}

// ClearTotalRechargedDeducted clears the value of the "total_recharged_deducted" field.
func (u *UserAffiliateReversalUpsertBulk) ClearTotalRechargedDeducted() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearTotalRechargedDeducted()
	})
}

// SetBalanceBefore sets the "balance_before" field.
func (u *UserAffiliateReversalUpsertBulk) SetBalanceBefore(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetBalanceBefore(v)
	})
}

// AddBalanceBefore adds v to the "balance_before" field.
func (u *UserAffiliateReversalUpsertBulk) AddBalanceBefore(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddBalanceBefore(v)
	})
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateBalanceBefore() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateBalanceBefore()
	})
}

// ClearBalanceBefore clears the value of the "balance_before" field.
func (u *UserAffiliateReversalUpsertBulk) ClearBalanceBefore() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearBalanceBefore()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *UserAffiliateReversalUpsertBulk) SetBalanceAfter(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *UserAffiliateReversalUpsertBulk) AddBalanceAfter(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateBalanceAfter() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateBalanceAfter()
	})
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (u *UserAffiliateReversalUpsertBulk) ClearBalanceAfter() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearBalanceAfter()
	})
}

// SetAffQuotaBefore sets the "aff_quota_before" field.
func (u *UserAffiliateReversalUpsertBulk) SetAffQuotaBefore(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetAffQuotaBefore(v)
	})
}

// AddAffQuotaBefore adds v to the "aff_quota_before" field.
func (u *UserAffiliateReversalUpsertBulk) AddAffQuotaBefore(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddAffQuotaBefore(v)
	})
}

// UpdateAffQuotaBefore sets the "aff_quota_before" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateAffQuotaBefore() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateAffQuotaBefore()
	})
}

// ClearAffQuotaBefore clears the value of the "aff_quota_before" field.
func (u *UserAffiliateReversalUpsertBulk) ClearAffQuotaBefore() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearAffQuotaBefore()
	})
}

// SetAffQuotaAfter sets the "aff_quota_after" field.
func (u *UserAffiliateReversalUpsertBulk) SetAffQuotaAfter(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetAffQuotaAfter(v)
	})
}

// AddAffQuotaAfter adds v to the "aff_quota_after" field.
func (u *UserAffiliateReversalUpsertBulk) AddAffQuotaAfter(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddAffQuotaAfter(v)
	})
}

// UpdateAffQuotaAfter sets the "aff_quota_after" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateAffQuotaAfter() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateAffQuotaAfter()
	})
}

// ClearAffQuotaAfter clears the value of the "aff_quota_after" field.
func (u *UserAffiliateReversalUpsertBulk) ClearAffQuotaAfter() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearAffQuotaAfter()
	})
}

// SetAffFrozenQuotaBefore sets the "aff_frozen_quota_before" field.
func (u *UserAffiliateReversalUpsertBulk) SetAffFrozenQuotaBefore(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetAffFrozenQuotaBefore(v)
	})
}

// AddAffFrozenQuotaBefore adds v to the "aff_frozen_quota_before" field.
func (u *UserAffiliateReversalUpsertBulk) AddAffFrozenQuotaBefore(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddAffFrozenQuotaBefore(v)
	})
}

// UpdateAffFrozenQuotaBefore sets the "aff_frozen_quota_before" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateAffFrozenQuotaBefore() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateAffFrozenQuotaBefore()
	})
}

// ClearAffFrozenQuotaBefore clears the value of the "aff_frozen_quota_before" field.
func (u *UserAffiliateReversalUpsertBulk) ClearAffFrozenQuotaBefore() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearAffFrozenQuotaBefore()
	})
}

// SetAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field.
func (u *UserAffiliateReversalUpsertBulk) SetAffFrozenQuotaAfter(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetAffFrozenQuotaAfter(v)
	})
}

// AddAffFrozenQuotaAfter adds v to the "aff_frozen_quota_after" field.
func (u *UserAffiliateReversalUpsertBulk) AddAffFrozenQuotaAfter(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddAffFrozenQuotaAfter(v)
	})
}

// UpdateAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateAffFrozenQuotaAfter() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateAffFrozenQuotaAfter()
	})
}

// ClearAffFrozenQuotaAfter clears the value of the "aff_frozen_quota_after" field.
func (u *UserAffiliateReversalUpsertBulk) ClearAffFrozenQuotaAfter() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearAffFrozenQuotaAfter()
	})
}

// SetAffHistoryQuotaBefore sets the "aff_history_quota_before" field.
func (u *UserAffiliateReversalUpsertBulk) SetAffHistoryQuotaBefore(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetAffHistoryQuotaBefore(v)
	})
}

// AddAffHistoryQuotaBefore adds v to the "aff_history_quota_before" field.
func (u *UserAffiliateReversalUpsertBulk) AddAffHistoryQuotaBefore(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddAffHistoryQuotaBefore(v)
	})
}

// UpdateAffHistoryQuotaBefore sets the "aff_history_quota_before" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateAffHistoryQuotaBefore() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateAffHistoryQuotaBefore()
	})
}

// ClearAffHistoryQuotaBefore clears the value of the "aff_history_quota_before" field.
func (u *UserAffiliateReversalUpsertBulk) ClearAffHistoryQuotaBefore() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearAffHistoryQuotaBefore()
	})
}

// SetAffHistoryQuotaAfter sets the "aff_history_quota_after" field.
func (u *UserAffiliateReversalUpsertBulk) SetAffHistoryQuotaAfter(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetAffHistoryQuotaAfter(v)
	})
}

// AddAffHistoryQuotaAfter adds v to the "aff_history_quota_after" field.
func (u *UserAffiliateReversalUpsertBulk) AddAffHistoryQuotaAfter(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddAffHistoryQuotaAfter(v)
	})
}

// UpdateAffHistoryQuotaAfter sets the "aff_history_quota_after" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateAffHistoryQuotaAfter() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateAffHistoryQuotaAfter()
	})
}

// ClearAffHistoryQuotaAfter clears the value of the "aff_history_quota_after" field.
func (u *UserAffiliateReversalUpsertBulk) ClearAffHistoryQuotaAfter() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearAffHistoryQuotaAfter()
	})
}

// SetTotalRechargedBefore sets the "total_recharged_before" field.
func (u *UserAffiliateReversalUpsertBulk) SetTotalRechargedBefore(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetTotalRechargedBefore(v)
	})
}

// AddTotalRechargedBefore adds v to the "total_recharged_before" field.
func (u *UserAffiliateReversalUpsertBulk) AddTotalRechargedBefore(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddTotalRechargedBefore(v)
	})
}

// UpdateTotalRechargedBefore sets the "total_recharged_before" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateTotalRechargedBefore() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateTotalRechargedBefore()
	})
}

// ClearTotalRechargedBefore clears the value of the "total_recharged_before" field.
func (u *UserAffiliateReversalUpsertBulk) ClearTotalRechargedBefore() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearTotalRechargedBefore()
	})
}

// SetTotalRechargedAfter sets the "total_recharged_after" field.
func (u *UserAffiliateReversalUpsertBulk) SetTotalRechargedAfter(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetTotalRechargedAfter(v)
	})
}

// AddTotalRechargedAfter adds v to the "total_recharged_after" field.
func (u *UserAffiliateReversalUpsertBulk) AddTotalRechargedAfter(v float64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddTotalRechargedAfter(v)
	})
}

// UpdateTotalRechargedAfter sets the "total_recharged_after" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateTotalRechargedAfter() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateTotalRechargedAfter()
	})
}

// ClearTotalRechargedAfter clears the value of the "total_recharged_after" field.
func (u *UserAffiliateReversalUpsertBulk) ClearTotalRechargedAfter() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearTotalRechargedAfter()
	})
}

// SetSnapshotAvailable sets the "snapshot_available" field.
func (u *UserAffiliateReversalUpsertBulk) SetSnapshotAvailable(v bool) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetSnapshotAvailable(v)
	})
}

// UpdateSnapshotAvailable sets the "snapshot_available" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateSnapshotAvailable() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateSnapshotAvailable()
	})
}

// SetReason sets the "reason" field.
func (u *UserAffiliateReversalUpsertBulk) SetReason(v string) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateReason() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateReason()
	})
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *UserAffiliateReversalUpsertBulk) SetOperatorUserID(v int64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetOperatorUserID(v)
	})
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *UserAffiliateReversalUpsertBulk) AddOperatorUserID(v int64) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.AddOperatorUserID(v)
	})
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateOperatorUserID() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateOperatorUserID()
	})
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *UserAffiliateReversalUpsertBulk) ClearOperatorUserID() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearOperatorUserID()
	})
}

// SetOperationKeyHash sets the "operation_key_hash" field.
func (u *UserAffiliateReversalUpsertBulk) SetOperationKeyHash(v string) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetOperationKeyHash(v)
	})
}

// UpdateOperationKeyHash sets the "operation_key_hash" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateOperationKeyHash() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateOperationKeyHash()
	})
}

// ClearOperationKeyHash clears the value of the "operation_key_hash" field.
func (u *UserAffiliateReversalUpsertBulk) ClearOperationKeyHash() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.ClearOperationKeyHash()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAffiliateReversalUpsertBulk) SetUpdatedAt(v time.Time) *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAffiliateReversalUpsertBulk) UpdateUpdatedAt() *UserAffiliateReversalUpsertBulk {
	return u.Update(func(s *UserAffiliateReversalUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserAffiliateReversalUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserAffiliateReversalCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserAffiliateReversalCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserAffiliateReversalUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
