// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usersubscriptioncycle"
)

// UserSubscriptionCycleDelete is the builder for deleting a UserSubscriptionCycle entity.
type UserSubscriptionCycleDelete struct {
	config
	hooks    []Hook
	mutation *UserSubscriptionCycleMutation
}

// Where appends a list predicates to the UserSubscriptionCycleDelete builder.
func (_d *UserSubscriptionCycleDelete) Where(ps ...predicate.UserSubscriptionCycle) *UserSubscriptionCycleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserSubscriptionCycleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserSubscriptionCycleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserSubscriptionCycleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usersubscriptioncycle.Table, sqlgraph.NewFieldSpec(usersubscriptioncycle.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserSubscriptionCycleDeleteOne is the builder for deleting a single UserSubscriptionCycle entity.
type UserSubscriptionCycleDeleteOne struct {
	_d *UserSubscriptionCycleDelete
}

// Where appends a list predicates to the UserSubscriptionCycleDelete builder.
func (_d *UserSubscriptionCycleDeleteOne) Where(ps ...predicate.UserSubscriptionCycle) *UserSubscriptionCycleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserSubscriptionCycleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usersubscriptioncycle.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserSubscriptionCycleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
