// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
	"github.com/Wei-Shaw/sub2api/ent/usersubscriptioncycle"
)

// UserSubscriptionCycle is the model entity for the UserSubscriptionCycle schema.
type UserSubscriptionCycle struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID int64 `json:"subscription_id,omitempty"`
	// StartsAt holds the value of the "starts_at" field.
	StartsAt time.Time `json:"starts_at,omitempty"`
	// EndsAt holds the value of the "ends_at" field.
	EndsAt time.Time `json:"ends_at,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType string `json:"source_type,omitempty"`
	// SourceRef holds the value of the "source_ref" field.
	SourceRef *string `json:"source_ref,omitempty"`
	// FinalUsageUsd holds the value of the "final_usage_usd" field.
	FinalUsageUsd float64 `json:"final_usage_usd,omitempty"`
	// FinalManualQuotaResetCount holds the value of the "final_manual_quota_reset_count" field.
	FinalManualQuotaResetCount int64 `json:"final_manual_quota_reset_count,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserSubscriptionCycleQuery when eager-loading is set.
	Edges        UserSubscriptionCycleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserSubscriptionCycleEdges holds the relations/edges for other nodes in the graph.
type UserSubscriptionCycleEdges struct {
	// Subscription holds the value of the subscription edge.
	Subscription *UserSubscription `json:"subscription,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserSubscriptionCycleEdges) SubscriptionOrErr() (*UserSubscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserSubscriptionCycle) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usersubscriptioncycle.FieldFinalUsageUsd:
			values[i] = new(sql.NullFloat64)
		case usersubscriptioncycle.FieldID, usersubscriptioncycle.FieldSubscriptionID, usersubscriptioncycle.FieldFinalManualQuotaResetCount:
			values[i] = new(sql.NullInt64)
		case usersubscriptioncycle.FieldStatus, usersubscriptioncycle.FieldSourceType, usersubscriptioncycle.FieldSourceRef:
			values[i] = new(sql.NullString)
		case usersubscriptioncycle.FieldCreatedAt, usersubscriptioncycle.FieldUpdatedAt, usersubscriptioncycle.FieldStartsAt, usersubscriptioncycle.FieldEndsAt, usersubscriptioncycle.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserSubscriptionCycle fields.
func (_m *UserSubscriptionCycle) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usersubscriptioncycle.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usersubscriptioncycle.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usersubscriptioncycle.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case usersubscriptioncycle.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = value.Int64
			}
		case usersubscriptioncycle.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = value.Time
			}
		case usersubscriptioncycle.FieldEndsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ends_at", values[i])
			} else if value.Valid {
				_m.EndsAt = value.Time
			}
		case usersubscriptioncycle.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case usersubscriptioncycle.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case usersubscriptioncycle.FieldSourceRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_ref", values[i])
			} else if value.Valid {
				_m.SourceRef = new(string)
				*_m.SourceRef = value.String
			}
		case usersubscriptioncycle.FieldFinalUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field final_usage_usd", values[i])
			} else if value.Valid {
				_m.FinalUsageUsd = value.Float64
			}
		case usersubscriptioncycle.FieldFinalManualQuotaResetCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field final_manual_quota_reset_count", values[i])
			} else if value.Valid {
				_m.FinalManualQuotaResetCount = value.Int64
			}
		case usersubscriptioncycle.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserSubscriptionCycle.
// This includes values selected through modifiers, order, etc.
func (_m *UserSubscriptionCycle) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySubscription queries the "subscription" edge of the UserSubscriptionCycle entity.
func (_m *UserSubscriptionCycle) QuerySubscription() *UserSubscriptionQuery {
	return NewUserSubscriptionCycleClient(_m.config).QuerySubscription(_m)
}

// Update returns a builder for updating this UserSubscriptionCycle.
// Note that you need to call UserSubscriptionCycle.Unwrap() before calling this method if this UserSubscriptionCycle
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserSubscriptionCycle) Update() *UserSubscriptionCycleUpdateOne {
	return NewUserSubscriptionCycleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserSubscriptionCycle entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserSubscriptionCycle) Unwrap() *UserSubscriptionCycle {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserSubscriptionCycle is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserSubscriptionCycle) String() string {
	var builder strings.Builder
	builder.WriteString("UserSubscriptionCycle(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("subscription_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionID))
	builder.WriteString(", ")
	builder.WriteString("starts_at=")
	builder.WriteString(_m.StartsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("ends_at=")
	builder.WriteString(_m.EndsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	if v := _m.SourceRef; v != nil {
		builder.WriteString("source_ref=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("final_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.FinalUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("final_manual_quota_reset_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FinalManualQuotaResetCount))
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UserSubscriptionCycles is a parsable slice of UserSubscriptionCycle.
type UserSubscriptionCycles []*UserSubscriptionCycle
