// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/useraffiliateledger"
)

// UserAffiliateLedgerCreate is the builder for creating a UserAffiliateLedger entity.
type UserAffiliateLedgerCreate struct {
	config
	mutation *UserAffiliateLedgerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserAffiliateLedgerCreate) SetUserID(v int64) *UserAffiliateLedgerCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *UserAffiliateLedgerCreate) SetAction(v string) *UserAffiliateLedgerCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *UserAffiliateLedgerCreate) SetAmount(v float64) *UserAffiliateLedgerCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetSourceUserID sets the "source_user_id" field.
func (_c *UserAffiliateLedgerCreate) SetSourceUserID(v int64) *UserAffiliateLedgerCreate {
	_c.mutation.SetSourceUserID(v)
	return _c
}

// SetNillableSourceUserID sets the "source_user_id" field if the given value is not nil.
func (_c *UserAffiliateLedgerCreate) SetNillableSourceUserID(v *int64) *UserAffiliateLedgerCreate {
	if v != nil {
		_c.SetSourceUserID(*v)
	}
	return _c
}

// SetSourceOrderID sets the "source_order_id" field.
func (_c *UserAffiliateLedgerCreate) SetSourceOrderID(v int64) *UserAffiliateLedgerCreate {
	_c.mutation.SetSourceOrderID(v)
	return _c
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_c *UserAffiliateLedgerCreate) SetNillableSourceOrderID(v *int64) *UserAffiliateLedgerCreate {
	if v != nil {
		_c.SetSourceOrderID(*v)
	}
	return _c
}

// SetFrozenUntil sets the "frozen_until" field.
func (_c *UserAffiliateLedgerCreate) SetFrozenUntil(v time.Time) *UserAffiliateLedgerCreate {
	_c.mutation.SetFrozenUntil(v)
	return _c
}

// SetNillableFrozenUntil sets the "frozen_until" field if the given value is not nil.
func (_c *UserAffiliateLedgerCreate) SetNillableFrozenUntil(v *time.Time) *UserAffiliateLedgerCreate {
	if v != nil {
		_c.SetFrozenUntil(*v)
	}
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *UserAffiliateLedgerCreate) SetBalanceAfter(v float64) *UserAffiliateLedgerCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_c *UserAffiliateLedgerCreate) SetNillableBalanceAfter(v *float64) *UserAffiliateLedgerCreate {
	if v != nil {
		_c.SetBalanceAfter(*v)
	}
	return _c
}

// SetAffQuotaAfter sets the "aff_quota_after" field.
func (_c *UserAffiliateLedgerCreate) SetAffQuotaAfter(v float64) *UserAffiliateLedgerCreate {
	_c.mutation.SetAffQuotaAfter(v)
	return _c
}

// SetNillableAffQuotaAfter sets the "aff_quota_after" field if the given value is not nil.
func (_c *UserAffiliateLedgerCreate) SetNillableAffQuotaAfter(v *float64) *UserAffiliateLedgerCreate {
	if v != nil {
		_c.SetAffQuotaAfter(*v)
	}
	return _c
}

// SetAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field.
func (_c *UserAffiliateLedgerCreate) SetAffFrozenQuotaAfter(v float64) *UserAffiliateLedgerCreate {
	_c.mutation.SetAffFrozenQuotaAfter(v)
	return _c
}

// SetNillableAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field if the given value is not nil.
func (_c *UserAffiliateLedgerCreate) SetNillableAffFrozenQuotaAfter(v *float64) *UserAffiliateLedgerCreate {
	if v != nil {
		_c.SetAffFrozenQuotaAfter(*v)
	}
	return _c
}

// SetAffHistoryQuotaAfter sets the "aff_history_quota_after" field.
func (_c *UserAffiliateLedgerCreate) SetAffHistoryQuotaAfter(v float64) *UserAffiliateLedgerCreate {
	_c.mutation.SetAffHistoryQuotaAfter(v)
	return _c
}

// SetNillableAffHistoryQuotaAfter sets the "aff_history_quota_after" field if the given value is not nil.
func (_c *UserAffiliateLedgerCreate) SetNillableAffHistoryQuotaAfter(v *float64) *UserAffiliateLedgerCreate {
	if v != nil {
		_c.SetAffHistoryQuotaAfter(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserAffiliateLedgerCreate) SetCreatedAt(v time.Time) *UserAffiliateLedgerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserAffiliateLedgerCreate) SetNillableCreatedAt(v *time.Time) *UserAffiliateLedgerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserAffiliateLedgerCreate) SetUpdatedAt(v time.Time) *UserAffiliateLedgerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserAffiliateLedgerCreate) SetNillableUpdatedAt(v *time.Time) *UserAffiliateLedgerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the UserAffiliateLedgerMutation object of the builder.
func (_c *UserAffiliateLedgerCreate) Mutation() *UserAffiliateLedgerMutation {
	return _c.mutation
}

// Save creates the UserAffiliateLedger in the database.
func (_c *UserAffiliateLedgerCreate) Save(ctx context.Context) (*UserAffiliateLedger, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserAffiliateLedgerCreate) SaveX(ctx context.Context) *UserAffiliateLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAffiliateLedgerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAffiliateLedgerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserAffiliateLedgerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := useraffiliateledger.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := useraffiliateledger.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserAffiliateLedgerCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserAffiliateLedger.user_id"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "UserAffiliateLedger.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := useraffiliateledger.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateLedger.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "UserAffiliateLedger.amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserAffiliateLedger.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserAffiliateLedger.updated_at"`)}
	}
	return nil
}

func (_c *UserAffiliateLedgerCreate) sqlSave(ctx context.Context) (*UserAffiliateLedger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserAffiliateLedgerCreate) createSpec() (*UserAffiliateLedger, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAffiliateLedger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(useraffiliateledger.Table, sqlgraph.NewFieldSpec(useraffiliateledger.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(useraffiliateledger.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(useraffiliateledger.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(useraffiliateledger.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.SourceUserID(); ok {
		_spec.SetField(useraffiliateledger.FieldSourceUserID, field.TypeInt64, value)
		_node.SourceUserID = &value
	}
	if value, ok := _c.mutation.SourceOrderID(); ok {
		_spec.SetField(useraffiliateledger.FieldSourceOrderID, field.TypeInt64, value)
		_node.SourceOrderID = &value
	}
	if value, ok := _c.mutation.FrozenUntil(); ok {
		_spec.SetField(useraffiliateledger.FieldFrozenUntil, field.TypeTime, value)
		_node.FrozenUntil = &value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(useraffiliateledger.FieldBalanceAfter, field.TypeFloat64, value)
		_node.BalanceAfter = &value
	}
	if value, ok := _c.mutation.AffQuotaAfter(); ok {
		_spec.SetField(useraffiliateledger.FieldAffQuotaAfter, field.TypeFloat64, value)
		_node.AffQuotaAfter = &value
	}
	if value, ok := _c.mutation.AffFrozenQuotaAfter(); ok {
		_spec.SetField(useraffiliateledger.FieldAffFrozenQuotaAfter, field.TypeFloat64, value)
		_node.AffFrozenQuotaAfter = &value
	}
	if value, ok := _c.mutation.AffHistoryQuotaAfter(); ok {
		_spec.SetField(useraffiliateledger.FieldAffHistoryQuotaAfter, field.TypeFloat64, value)
		_node.AffHistoryQuotaAfter = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(useraffiliateledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(useraffiliateledger.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserAffiliateLedger.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserAffiliateLedgerUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserAffiliateLedgerCreate) OnConflict(opts ...sql.ConflictOption) *UserAffiliateLedgerUpsertOne {
	_c.conflict = opts
	return &UserAffiliateLedgerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserAffiliateLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserAffiliateLedgerCreate) OnConflictColumns(columns ...string) *UserAffiliateLedgerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserAffiliateLedgerUpsertOne{
		create: _c,
	}
}

type (
	// UserAffiliateLedgerUpsertOne is the builder for "upsert"-ing
	//  one UserAffiliateLedger node.
	UserAffiliateLedgerUpsertOne struct {
		create *UserAffiliateLedgerCreate
	}

	// UserAffiliateLedgerUpsert is the "OnConflict" setter.
	UserAffiliateLedgerUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserAffiliateLedgerUpsert) SetUserID(v int64) *UserAffiliateLedgerUpsert {
	u.Set(useraffiliateledger.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsert) UpdateUserID() *UserAffiliateLedgerUpsert {
	u.SetExcluded(useraffiliateledger.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UserAffiliateLedgerUpsert) AddUserID(v int64) *UserAffiliateLedgerUpsert {
	u.Add(useraffiliateledger.FieldUserID, v)
	return u
}

// SetAction sets the "action" field.
func (u *UserAffiliateLedgerUpsert) SetAction(v string) *UserAffiliateLedgerUpsert {
	u.Set(useraffiliateledger.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsert) UpdateAction() *UserAffiliateLedgerUpsert {
	u.SetExcluded(useraffiliateledger.FieldAction)
	return u
}

// SetAmount sets the "amount" field.
func (u *UserAffiliateLedgerUpsert) SetAmount(v float64) *UserAffiliateLedgerUpsert {
	u.Set(useraffiliateledger.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsert) UpdateAmount() *UserAffiliateLedgerUpsert {
	u.SetExcluded(useraffiliateledger.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *UserAffiliateLedgerUpsert) AddAmount(v float64) *UserAffiliateLedgerUpsert {
	u.Add(useraffiliateledger.FieldAmount, v)
	return u
}

// SetSourceUserID sets the "source_user_id" field.
func (u *UserAffiliateLedgerUpsert) SetSourceUserID(v int64) *UserAffiliateLedgerUpsert {
	u.Set(useraffiliateledger.FieldSourceUserID, v)
	return u
}

// UpdateSourceUserID sets the "source_user_id" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsert) UpdateSourceUserID() *UserAffiliateLedgerUpsert {
	u.SetExcluded(useraffiliateledger.FieldSourceUserID)
	return u
}

// AddSourceUserID adds v to the "source_user_id" field.
func (u *UserAffiliateLedgerUpsert) AddSourceUserID(v int64) *UserAffiliateLedgerUpsert {
	u.Add(useraffiliateledger.FieldSourceUserID, v)
	return u
}

// ClearSourceUserID clears the value of the "source_user_id" field.
func (u *UserAffiliateLedgerUpsert) ClearSourceUserID() *UserAffiliateLedgerUpsert {
	u.SetNull(useraffiliateledger.FieldSourceUserID)
	return u
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *UserAffiliateLedgerUpsert) SetSourceOrderID(v int64) *UserAffiliateLedgerUpsert {
	u.Set(useraffiliateledger.FieldSourceOrderID, v)
	return u
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsert) UpdateSourceOrderID() *UserAffiliateLedgerUpsert {
	u.SetExcluded(useraffiliateledger.FieldSourceOrderID)
	return u
}

// AddSourceOrderID adds v to the "source_order_id" field.
func (u *UserAffiliateLedgerUpsert) AddSourceOrderID(v int64) *UserAffiliateLedgerUpsert {
	u.Add(useraffiliateledger.FieldSourceOrderID, v)
	return u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *UserAffiliateLedgerUpsert) ClearSourceOrderID() *UserAffiliateLedgerUpsert {
	u.SetNull(useraffiliateledger.FieldSourceOrderID)
	return u
}

// SetFrozenUntil sets the "frozen_until" field.
func (u *UserAffiliateLedgerUpsert) SetFrozenUntil(v time.Time) *UserAffiliateLedgerUpsert {
	u.Set(useraffiliateledger.FieldFrozenUntil, v)
	return u
}

// UpdateFrozenUntil sets the "frozen_until" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsert) UpdateFrozenUntil() *UserAffiliateLedgerUpsert {
	u.SetExcluded(useraffiliateledger.FieldFrozenUntil)
	return u
}

// ClearFrozenUntil clears the value of the "frozen_until" field.
func (u *UserAffiliateLedgerUpsert) ClearFrozenUntil() *UserAffiliateLedgerUpsert {
	u.SetNull(useraffiliateledger.FieldFrozenUntil)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *UserAffiliateLedgerUpsert) SetBalanceAfter(v float64) *UserAffiliateLedgerUpsert {
	u.Set(useraffiliateledger.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsert) UpdateBalanceAfter() *UserAffiliateLedgerUpsert {
	u.SetExcluded(useraffiliateledger.FieldBalanceAfter)
	return u
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *UserAffiliateLedgerUpsert) AddBalanceAfter(v float64) *UserAffiliateLedgerUpsert {
	u.Add(useraffiliateledger.FieldBalanceAfter, v)
	return u
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (u *UserAffiliateLedgerUpsert) ClearBalanceAfter() *UserAffiliateLedgerUpsert {
	u.SetNull(useraffiliateledger.FieldBalanceAfter)
	return u
}

// SetAffQuotaAfter sets the "aff_quota_after" field.
func (u *UserAffiliateLedgerUpsert) SetAffQuotaAfter(v float64) *UserAffiliateLedgerUpsert {
	u.Set(useraffiliateledger.FieldAffQuotaAfter, v)
	return u
}

// UpdateAffQuotaAfter sets the "aff_quota_after" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsert) UpdateAffQuotaAfter() *UserAffiliateLedgerUpsert {
	u.SetExcluded(useraffiliateledger.FieldAffQuotaAfter)
	return u
}

// AddAffQuotaAfter adds v to the "aff_quota_after" field.
func (u *UserAffiliateLedgerUpsert) AddAffQuotaAfter(v float64) *UserAffiliateLedgerUpsert {
	u.Add(useraffiliateledger.FieldAffQuotaAfter, v)
	return u
}

// ClearAffQuotaAfter clears the value of the "aff_quota_after" field.
func (u *UserAffiliateLedgerUpsert) ClearAffQuotaAfter() *UserAffiliateLedgerUpsert {
	u.SetNull(useraffiliateledger.FieldAffQuotaAfter)
	return u
}

// SetAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field.
func (u *UserAffiliateLedgerUpsert) SetAffFrozenQuotaAfter(v float64) *UserAffiliateLedgerUpsert {
	u.Set(useraffiliateledger.FieldAffFrozenQuotaAfter, v)
	return u
}

// UpdateAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsert) UpdateAffFrozenQuotaAfter() *UserAffiliateLedgerUpsert {
	u.SetExcluded(useraffiliateledger.FieldAffFrozenQuotaAfter)
	return u
}

// AddAffFrozenQuotaAfter adds v to the "aff_frozen_quota_after" field.
func (u *UserAffiliateLedgerUpsert) AddAffFrozenQuotaAfter(v float64) *UserAffiliateLedgerUpsert {
	u.Add(useraffiliateledger.FieldAffFrozenQuotaAfter, v)
	return u
}

// ClearAffFrozenQuotaAfter clears the value of the "aff_frozen_quota_after" field.
func (u *UserAffiliateLedgerUpsert) ClearAffFrozenQuotaAfter() *UserAffiliateLedgerUpsert {
	u.SetNull(useraffiliateledger.FieldAffFrozenQuotaAfter)
	return u
}

// SetAffHistoryQuotaAfter sets the "aff_history_quota_after" field.
func (u *UserAffiliateLedgerUpsert) SetAffHistoryQuotaAfter(v float64) *UserAffiliateLedgerUpsert {
	u.Set(useraffiliateledger.FieldAffHistoryQuotaAfter, v)
	return u
}

// UpdateAffHistoryQuotaAfter sets the "aff_history_quota_after" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsert) UpdateAffHistoryQuotaAfter() *UserAffiliateLedgerUpsert {
	u.SetExcluded(useraffiliateledger.FieldAffHistoryQuotaAfter)
	return u
}

// AddAffHistoryQuotaAfter adds v to the "aff_history_quota_after" field.
func (u *UserAffiliateLedgerUpsert) AddAffHistoryQuotaAfter(v float64) *UserAffiliateLedgerUpsert {
	u.Add(useraffiliateledger.FieldAffHistoryQuotaAfter, v)
	return u
}

// ClearAffHistoryQuotaAfter clears the value of the "aff_history_quota_after" field.
func (u *UserAffiliateLedgerUpsert) ClearAffHistoryQuotaAfter() *UserAffiliateLedgerUpsert {
	u.SetNull(useraffiliateledger.FieldAffHistoryQuotaAfter)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAffiliateLedgerUpsert) SetUpdatedAt(v time.Time) *UserAffiliateLedgerUpsert {
	u.Set(useraffiliateledger.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsert) UpdateUpdatedAt() *UserAffiliateLedgerUpsert {
	u.SetExcluded(useraffiliateledger.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserAffiliateLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserAffiliateLedgerUpsertOne) UpdateNewValues() *UserAffiliateLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(useraffiliateledger.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserAffiliateLedger.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserAffiliateLedgerUpsertOne) Ignore() *UserAffiliateLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserAffiliateLedgerUpsertOne) DoNothing() *UserAffiliateLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserAffiliateLedgerCreate.OnConflict
// documentation for more info.
func (u *UserAffiliateLedgerUpsertOne) Update(set func(*UserAffiliateLedgerUpsert)) *UserAffiliateLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserAffiliateLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserAffiliateLedgerUpsertOne) SetUserID(v int64) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserAffiliateLedgerUpsertOne) AddUserID(v int64) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertOne) UpdateUserID() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateUserID()
	})
}

// SetAction sets the "action" field.
func (u *UserAffiliateLedgerUpsertOne) SetAction(v string) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertOne) UpdateAction() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateAction()
	})
}

// SetAmount sets the "amount" field.
func (u *UserAffiliateLedgerUpsertOne) SetAmount(v float64) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *UserAffiliateLedgerUpsertOne) AddAmount(v float64) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertOne) UpdateAmount() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateAmount()
	})
}

// SetSourceUserID sets the "source_user_id" field.
func (u *UserAffiliateLedgerUpsertOne) SetSourceUserID(v int64) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetSourceUserID(v)
	})
}

// AddSourceUserID adds v to the "source_user_id" field.
func (u *UserAffiliateLedgerUpsertOne) AddSourceUserID(v int64) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.AddSourceUserID(v)
	})
}

// UpdateSourceUserID sets the "source_user_id" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertOne) UpdateSourceUserID() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateSourceUserID()
	})
}

// ClearSourceUserID clears the value of the "source_user_id" field.
func (u *UserAffiliateLedgerUpsertOne) ClearSourceUserID() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.ClearSourceUserID()
	})
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *UserAffiliateLedgerUpsertOne) SetSourceOrderID(v int64) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetSourceOrderID(v)
	})
}

// AddSourceOrderID adds v to the "source_order_id" field.
func (u *UserAffiliateLedgerUpsertOne) AddSourceOrderID(v int64) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.AddSourceOrderID(v)
	})
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertOne) UpdateSourceOrderID() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateSourceOrderID()
	})
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *UserAffiliateLedgerUpsertOne) ClearSourceOrderID() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.ClearSourceOrderID()
	})
}

// SetFrozenUntil sets the "frozen_until" field.
func (u *UserAffiliateLedgerUpsertOne) SetFrozenUntil(v time.Time) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetFrozenUntil(v)
	})
}

// UpdateFrozenUntil sets the "frozen_until" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertOne) UpdateFrozenUntil() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateFrozenUntil()
	})
}

// ClearFrozenUntil clears the value of the "frozen_until" field.
func (u *UserAffiliateLedgerUpsertOne) ClearFrozenUntil() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.ClearFrozenUntil()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *UserAffiliateLedgerUpsertOne) SetBalanceAfter(v float64) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *UserAffiliateLedgerUpsertOne) AddBalanceAfter(v float64) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertOne) UpdateBalanceAfter() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateBalanceAfter()
	})
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (u *UserAffiliateLedgerUpsertOne) ClearBalanceAfter() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.ClearBalanceAfter()
	})
}

// SetAffQuotaAfter sets the "aff_quota_after" field.
func (u *UserAffiliateLedgerUpsertOne) SetAffQuotaAfter(v float64) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetAffQuotaAfter(v)
	})
}

// AddAffQuotaAfter adds v to the "aff_quota_after" field.
func (u *UserAffiliateLedgerUpsertOne) AddAffQuotaAfter(v float64) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.AddAffQuotaAfter(v)
	})
}

// UpdateAffQuotaAfter sets the "aff_quota_after" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertOne) UpdateAffQuotaAfter() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateAffQuotaAfter()
	})
}

// ClearAffQuotaAfter clears the value of the "aff_quota_after" field.
func (u *UserAffiliateLedgerUpsertOne) ClearAffQuotaAfter() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.ClearAffQuotaAfter()
	})
}

// SetAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field.
func (u *UserAffiliateLedgerUpsertOne) SetAffFrozenQuotaAfter(v float64) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetAffFrozenQuotaAfter(v)
	})
}

// AddAffFrozenQuotaAfter adds v to the "aff_frozen_quota_after" field.
func (u *UserAffiliateLedgerUpsertOne) AddAffFrozenQuotaAfter(v float64) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.AddAffFrozenQuotaAfter(v)
	})
}

// UpdateAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertOne) UpdateAffFrozenQuotaAfter() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateAffFrozenQuotaAfter()
	})
}

// ClearAffFrozenQuotaAfter clears the value of the "aff_frozen_quota_after" field.
func (u *UserAffiliateLedgerUpsertOne) ClearAffFrozenQuotaAfter() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.ClearAffFrozenQuotaAfter()
	})
}

// SetAffHistoryQuotaAfter sets the "aff_history_quota_after" field.
func (u *UserAffiliateLedgerUpsertOne) SetAffHistoryQuotaAfter(v float64) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetAffHistoryQuotaAfter(v)
	})
}

// AddAffHistoryQuotaAfter adds v to the "aff_history_quota_after" field.
func (u *UserAffiliateLedgerUpsertOne) AddAffHistoryQuotaAfter(v float64) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.AddAffHistoryQuotaAfter(v)
	})
}

// UpdateAffHistoryQuotaAfter sets the "aff_history_quota_after" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertOne) UpdateAffHistoryQuotaAfter() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateAffHistoryQuotaAfter()
	})
}

// ClearAffHistoryQuotaAfter clears the value of the "aff_history_quota_after" field.
func (u *UserAffiliateLedgerUpsertOne) ClearAffHistoryQuotaAfter() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.ClearAffHistoryQuotaAfter()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAffiliateLedgerUpsertOne) SetUpdatedAt(v time.Time) *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertOne) UpdateUpdatedAt() *UserAffiliateLedgerUpsertOne {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserAffiliateLedgerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserAffiliateLedgerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserAffiliateLedgerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserAffiliateLedgerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserAffiliateLedgerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserAffiliateLedgerCreateBulk is the builder for creating many UserAffiliateLedger entities in bulk.
type UserAffiliateLedgerCreateBulk struct {
	config
	err      error
	builders []*UserAffiliateLedgerCreate
	conflict []sql.ConflictOption
}

// Save creates the UserAffiliateLedger entities in the database.
func (_c *UserAffiliateLedgerCreateBulk) Save(ctx context.Context) ([]*UserAffiliateLedger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserAffiliateLedger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAffiliateLedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserAffiliateLedgerCreateBulk) SaveX(ctx context.Context) []*UserAffiliateLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAffiliateLedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAffiliateLedgerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserAffiliateLedger.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserAffiliateLedgerUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserAffiliateLedgerCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserAffiliateLedgerUpsertBulk {
	_c.conflict = opts
	return &UserAffiliateLedgerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserAffiliateLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserAffiliateLedgerCreateBulk) OnConflictColumns(columns ...string) *UserAffiliateLedgerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserAffiliateLedgerUpsertBulk{
		create: _c,
	}
}

// UserAffiliateLedgerUpsertBulk is the builder for "upsert"-ing
// a bulk of UserAffiliateLedger nodes.
type UserAffiliateLedgerUpsertBulk struct {
	create *UserAffiliateLedgerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserAffiliateLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserAffiliateLedgerUpsertBulk) UpdateNewValues() *UserAffiliateLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(useraffiliateledger.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserAffiliateLedger.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserAffiliateLedgerUpsertBulk) Ignore() *UserAffiliateLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserAffiliateLedgerUpsertBulk) DoNothing() *UserAffiliateLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserAffiliateLedgerCreateBulk.OnConflict
// documentation for more info.
func (u *UserAffiliateLedgerUpsertBulk) Update(set func(*UserAffiliateLedgerUpsert)) *UserAffiliateLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserAffiliateLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserAffiliateLedgerUpsertBulk) SetUserID(v int64) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserAffiliateLedgerUpsertBulk) AddUserID(v int64) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertBulk) UpdateUserID() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateUserID()
	})
}

// SetAction sets the "action" field.
func (u *UserAffiliateLedgerUpsertBulk) SetAction(v string) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertBulk) UpdateAction() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateAction()
	})
}

// SetAmount sets the "amount" field.
func (u *UserAffiliateLedgerUpsertBulk) SetAmount(v float64) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *UserAffiliateLedgerUpsertBulk) AddAmount(v float64) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertBulk) UpdateAmount() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateAmount()
	})
}

// SetSourceUserID sets the "source_user_id" field.
func (u *UserAffiliateLedgerUpsertBulk) SetSourceUserID(v int64) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetSourceUserID(v)
	})
}

// AddSourceUserID adds v to the "source_user_id" field.
func (u *UserAffiliateLedgerUpsertBulk) AddSourceUserID(v int64) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.AddSourceUserID(v)
	})
}

// UpdateSourceUserID sets the "source_user_id" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertBulk) UpdateSourceUserID() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateSourceUserID()
	})
}

// ClearSourceUserID clears the value of the "source_user_id" field.
func (u *UserAffiliateLedgerUpsertBulk) ClearSourceUserID() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.ClearSourceUserID()
	})
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *UserAffiliateLedgerUpsertBulk) SetSourceOrderID(v int64) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetSourceOrderID(v)
	})
}

// AddSourceOrderID adds v to the "source_order_id" field.
func (u *UserAffiliateLedgerUpsertBulk) AddSourceOrderID(v int64) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.AddSourceOrderID(v)
	})
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertBulk) UpdateSourceOrderID() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateSourceOrderID()
	})
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *UserAffiliateLedgerUpsertBulk) ClearSourceOrderID() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.ClearSourceOrderID()
	})
}

// SetFrozenUntil sets the "frozen_until" field.
func (u *UserAffiliateLedgerUpsertBulk) SetFrozenUntil(v time.Time) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetFrozenUntil(v)
	})
}

// UpdateFrozenUntil sets the "frozen_until" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertBulk) UpdateFrozenUntil() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateFrozenUntil()
	})
}

// ClearFrozenUntil clears the value of the "frozen_until" field.
func (u *UserAffiliateLedgerUpsertBulk) ClearFrozenUntil() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.ClearFrozenUntil()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *UserAffiliateLedgerUpsertBulk) SetBalanceAfter(v float64) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *UserAffiliateLedgerUpsertBulk) AddBalanceAfter(v float64) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertBulk) UpdateBalanceAfter() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateBalanceAfter()
	})
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (u *UserAffiliateLedgerUpsertBulk) ClearBalanceAfter() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.ClearBalanceAfter()
	})
}

// SetAffQuotaAfter sets the "aff_quota_after" field.
func (u *UserAffiliateLedgerUpsertBulk) SetAffQuotaAfter(v float64) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetAffQuotaAfter(v)
	})
}

// AddAffQuotaAfter adds v to the "aff_quota_after" field.
func (u *UserAffiliateLedgerUpsertBulk) AddAffQuotaAfter(v float64) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.AddAffQuotaAfter(v)
	})
}

// UpdateAffQuotaAfter sets the "aff_quota_after" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertBulk) UpdateAffQuotaAfter() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateAffQuotaAfter()
	})
}

// ClearAffQuotaAfter clears the value of the "aff_quota_after" field.
func (u *UserAffiliateLedgerUpsertBulk) ClearAffQuotaAfter() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.ClearAffQuotaAfter()
	})
}

// SetAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field.
func (u *UserAffiliateLedgerUpsertBulk) SetAffFrozenQuotaAfter(v float64) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetAffFrozenQuotaAfter(v)
	})
}

// AddAffFrozenQuotaAfter adds v to the "aff_frozen_quota_after" field.
func (u *UserAffiliateLedgerUpsertBulk) AddAffFrozenQuotaAfter(v float64) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.AddAffFrozenQuotaAfter(v)
	})
}

// UpdateAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertBulk) UpdateAffFrozenQuotaAfter() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateAffFrozenQuotaAfter()
	})
}

// ClearAffFrozenQuotaAfter clears the value of the "aff_frozen_quota_after" field.
func (u *UserAffiliateLedgerUpsertBulk) ClearAffFrozenQuotaAfter() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.ClearAffFrozenQuotaAfter()
	})
}

// SetAffHistoryQuotaAfter sets the "aff_history_quota_after" field.
func (u *UserAffiliateLedgerUpsertBulk) SetAffHistoryQuotaAfter(v float64) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetAffHistoryQuotaAfter(v)
	})
}

// AddAffHistoryQuotaAfter adds v to the "aff_history_quota_after" field.
func (u *UserAffiliateLedgerUpsertBulk) AddAffHistoryQuotaAfter(v float64) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.AddAffHistoryQuotaAfter(v)
	})
}

// UpdateAffHistoryQuotaAfter sets the "aff_history_quota_after" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertBulk) UpdateAffHistoryQuotaAfter() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateAffHistoryQuotaAfter()
	})
}

// ClearAffHistoryQuotaAfter clears the value of the "aff_history_quota_after" field.
func (u *UserAffiliateLedgerUpsertBulk) ClearAffHistoryQuotaAfter() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.ClearAffHistoryQuotaAfter()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAffiliateLedgerUpsertBulk) SetUpdatedAt(v time.Time) *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAffiliateLedgerUpsertBulk) UpdateUpdatedAt() *UserAffiliateLedgerUpsertBulk {
	return u.Update(func(s *UserAffiliateLedgerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserAffiliateLedgerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserAffiliateLedgerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserAffiliateLedgerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserAffiliateLedgerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
