// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/useraffiliateledger"
)

// UserAffiliateLedger is the model entity for the UserAffiliateLedger schema.
type UserAffiliateLedger struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// SourceUserID holds the value of the "source_user_id" field.
	SourceUserID *int64 `json:"source_user_id,omitempty"`
	// SourceOrderID holds the value of the "source_order_id" field.
	SourceOrderID *int64 `json:"source_order_id,omitempty"`
	// FrozenUntil holds the value of the "frozen_until" field.
	FrozenUntil *time.Time `json:"frozen_until,omitempty"`
	// BalanceAfter holds the value of the "balance_after" field.
	BalanceAfter *float64 `json:"balance_after,omitempty"`
	// AffQuotaAfter holds the value of the "aff_quota_after" field.
	AffQuotaAfter *float64 `json:"aff_quota_after,omitempty"`
	// AffFrozenQuotaAfter holds the value of the "aff_frozen_quota_after" field.
	AffFrozenQuotaAfter *float64 `json:"aff_frozen_quota_after,omitempty"`
	// AffHistoryQuotaAfter holds the value of the "aff_history_quota_after" field.
	AffHistoryQuotaAfter *float64 `json:"aff_history_quota_after,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserAffiliateLedger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case useraffiliateledger.FieldAmount, useraffiliateledger.FieldBalanceAfter, useraffiliateledger.FieldAffQuotaAfter, useraffiliateledger.FieldAffFrozenQuotaAfter, useraffiliateledger.FieldAffHistoryQuotaAfter:
			values[i] = new(sql.NullFloat64)
		case useraffiliateledger.FieldID, useraffiliateledger.FieldUserID, useraffiliateledger.FieldSourceUserID, useraffiliateledger.FieldSourceOrderID:
			values[i] = new(sql.NullInt64)
		case useraffiliateledger.FieldAction:
			values[i] = new(sql.NullString)
		case useraffiliateledger.FieldFrozenUntil, useraffiliateledger.FieldCreatedAt, useraffiliateledger.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserAffiliateLedger fields.
func (_m *UserAffiliateLedger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case useraffiliateledger.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case useraffiliateledger.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case useraffiliateledger.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case useraffiliateledger.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case useraffiliateledger.FieldSourceUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_user_id", values[i])
			} else if value.Valid {
				_m.SourceUserID = new(int64)
				*_m.SourceUserID = value.Int64
			}
		case useraffiliateledger.FieldSourceOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_order_id", values[i])
			} else if value.Valid {
				_m.SourceOrderID = new(int64)
				*_m.SourceOrderID = value.Int64
			}
		case useraffiliateledger.FieldFrozenUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field frozen_until", values[i])
			} else if value.Valid {
				_m.FrozenUntil = new(time.Time)
				*_m.FrozenUntil = value.Time
			}
		case useraffiliateledger.FieldBalanceAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after", values[i])
			} else if value.Valid {
				_m.BalanceAfter = new(float64)
				*_m.BalanceAfter = value.Float64
			}
		case useraffiliateledger.FieldAffQuotaAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field aff_quota_after", values[i])
			} else if value.Valid {
				_m.AffQuotaAfter = new(float64)
				*_m.AffQuotaAfter = value.Float64
			}
		case useraffiliateledger.FieldAffFrozenQuotaAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field aff_frozen_quota_after", values[i])
			} else if value.Valid {
				_m.AffFrozenQuotaAfter = new(float64)
				*_m.AffFrozenQuotaAfter = value.Float64
			}
		case useraffiliateledger.FieldAffHistoryQuotaAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field aff_history_quota_after", values[i])
			} else if value.Valid {
				_m.AffHistoryQuotaAfter = new(float64)
				*_m.AffHistoryQuotaAfter = value.Float64
			}
		case useraffiliateledger.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case useraffiliateledger.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserAffiliateLedger.
// This includes values selected through modifiers, order, etc.
func (_m *UserAffiliateLedger) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserAffiliateLedger.
// Note that you need to call UserAffiliateLedger.Unwrap() before calling this method if this UserAffiliateLedger
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserAffiliateLedger) Update() *UserAffiliateLedgerUpdateOne {
	return NewUserAffiliateLedgerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserAffiliateLedger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserAffiliateLedger) Unwrap() *UserAffiliateLedger {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserAffiliateLedger is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserAffiliateLedger) String() string {
	var builder strings.Builder
	builder.WriteString("UserAffiliateLedger(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	if v := _m.SourceUserID; v != nil {
		builder.WriteString("source_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SourceOrderID; v != nil {
		builder.WriteString("source_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.FrozenUntil; v != nil {
		builder.WriteString("frozen_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.BalanceAfter; v != nil {
		builder.WriteString("balance_after=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AffQuotaAfter; v != nil {
		builder.WriteString("aff_quota_after=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AffFrozenQuotaAfter; v != nil {
		builder.WriteString("aff_frozen_quota_after=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AffHistoryQuotaAfter; v != nil {
		builder.WriteString("aff_history_quota_after=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserAffiliateLedgers is a parsable slice of UserAffiliateLedger.
type UserAffiliateLedgers []*UserAffiliateLedger
