// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/useraffiliateledger"
)

// UserAffiliateLedgerDelete is the builder for deleting a UserAffiliateLedger entity.
type UserAffiliateLedgerDelete struct {
	config
	hooks    []Hook
	mutation *UserAffiliateLedgerMutation
}

// Where appends a list predicates to the UserAffiliateLedgerDelete builder.
func (_d *UserAffiliateLedgerDelete) Where(ps ...predicate.UserAffiliateLedger) *UserAffiliateLedgerDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserAffiliateLedgerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserAffiliateLedgerDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserAffiliateLedgerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(useraffiliateledger.Table, sqlgraph.NewFieldSpec(useraffiliateledger.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserAffiliateLedgerDeleteOne is the builder for deleting a single UserAffiliateLedger entity.
type UserAffiliateLedgerDeleteOne struct {
	_d *UserAffiliateLedgerDelete
}

// Where appends a list predicates to the UserAffiliateLedgerDelete builder.
func (_d *UserAffiliateLedgerDeleteOne) Where(ps ...predicate.UserAffiliateLedger) *UserAffiliateLedgerDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserAffiliateLedgerDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{useraffiliateledger.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserAffiliateLedgerDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
