// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/useraffiliatereversal"
)

// UserAffiliateReversal is the model entity for the UserAffiliateReversal schema.
type UserAffiliateReversal struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SourceLedgerID holds the value of the "source_ledger_id" field.
	SourceLedgerID *int64 `json:"source_ledger_id,omitempty"`
	// SourceOrderID holds the value of the "source_order_id" field.
	SourceOrderID int64 `json:"source_order_id,omitempty"`
	// InviterUserID holds the value of the "inviter_user_id" field.
	InviterUserID int64 `json:"inviter_user_id,omitempty"`
	// InviteeUserID holds the value of the "invitee_user_id" field.
	InviteeUserID int64 `json:"invitee_user_id,omitempty"`
	// RebateAmount holds the value of the "rebate_amount" field.
	RebateAmount float64 `json:"rebate_amount,omitempty"`
	// FrozenQuotaDeducted holds the value of the "frozen_quota_deducted" field.
	FrozenQuotaDeducted *float64 `json:"frozen_quota_deducted,omitempty"`
	// AvailableQuotaDeducted holds the value of the "available_quota_deducted" field.
	AvailableQuotaDeducted *float64 `json:"available_quota_deducted,omitempty"`
	// BalanceDeducted holds the value of the "balance_deducted" field.
	BalanceDeducted *float64 `json:"balance_deducted,omitempty"`
	// TotalRechargedDeducted holds the value of the "total_recharged_deducted" field.
	TotalRechargedDeducted *float64 `json:"total_recharged_deducted,omitempty"`
	// BalanceBefore holds the value of the "balance_before" field.
	BalanceBefore *float64 `json:"balance_before,omitempty"`
	// BalanceAfter holds the value of the "balance_after" field.
	BalanceAfter *float64 `json:"balance_after,omitempty"`
	// AffQuotaBefore holds the value of the "aff_quota_before" field.
	AffQuotaBefore *float64 `json:"aff_quota_before,omitempty"`
	// AffQuotaAfter holds the value of the "aff_quota_after" field.
	AffQuotaAfter *float64 `json:"aff_quota_after,omitempty"`
	// AffFrozenQuotaBefore holds the value of the "aff_frozen_quota_before" field.
	AffFrozenQuotaBefore *float64 `json:"aff_frozen_quota_before,omitempty"`
	// AffFrozenQuotaAfter holds the value of the "aff_frozen_quota_after" field.
	AffFrozenQuotaAfter *float64 `json:"aff_frozen_quota_after,omitempty"`
	// AffHistoryQuotaBefore holds the value of the "aff_history_quota_before" field.
	AffHistoryQuotaBefore *float64 `json:"aff_history_quota_before,omitempty"`
	// AffHistoryQuotaAfter holds the value of the "aff_history_quota_after" field.
	AffHistoryQuotaAfter *float64 `json:"aff_history_quota_after,omitempty"`
	// TotalRechargedBefore holds the value of the "total_recharged_before" field.
	TotalRechargedBefore *float64 `json:"total_recharged_before,omitempty"`
	// TotalRechargedAfter holds the value of the "total_recharged_after" field.
	TotalRechargedAfter *float64 `json:"total_recharged_after,omitempty"`
	// SnapshotAvailable holds the value of the "snapshot_available" field.
	SnapshotAvailable bool `json:"snapshot_available,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// OperatorUserID holds the value of the "operator_user_id" field.
	OperatorUserID *int64 `json:"operator_user_id,omitempty"`
	// OperationKeyHash holds the value of the "operation_key_hash" field.
	OperationKeyHash *string `json:"operation_key_hash,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserAffiliateReversal) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case useraffiliatereversal.FieldSnapshotAvailable:
			values[i] = new(sql.NullBool)
		case useraffiliatereversal.FieldRebateAmount, useraffiliatereversal.FieldFrozenQuotaDeducted, useraffiliatereversal.FieldAvailableQuotaDeducted, useraffiliatereversal.FieldBalanceDeducted, useraffiliatereversal.FieldTotalRechargedDeducted, useraffiliatereversal.FieldBalanceBefore, useraffiliatereversal.FieldBalanceAfter, useraffiliatereversal.FieldAffQuotaBefore, useraffiliatereversal.FieldAffQuotaAfter, useraffiliatereversal.FieldAffFrozenQuotaBefore, useraffiliatereversal.FieldAffFrozenQuotaAfter, useraffiliatereversal.FieldAffHistoryQuotaBefore, useraffiliatereversal.FieldAffHistoryQuotaAfter, useraffiliatereversal.FieldTotalRechargedBefore, useraffiliatereversal.FieldTotalRechargedAfter:
			values[i] = new(sql.NullFloat64)
		case useraffiliatereversal.FieldID, useraffiliatereversal.FieldSourceLedgerID, useraffiliatereversal.FieldSourceOrderID, useraffiliatereversal.FieldInviterUserID, useraffiliatereversal.FieldInviteeUserID, useraffiliatereversal.FieldOperatorUserID:
			values[i] = new(sql.NullInt64)
		case useraffiliatereversal.FieldReason, useraffiliatereversal.FieldOperationKeyHash:
			values[i] = new(sql.NullString)
		case useraffiliatereversal.FieldCreatedAt, useraffiliatereversal.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserAffiliateReversal fields.
func (_m *UserAffiliateReversal) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case useraffiliatereversal.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case useraffiliatereversal.FieldSourceLedgerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_ledger_id", values[i])
			} else if value.Valid {
				_m.SourceLedgerID = new(int64)
				*_m.SourceLedgerID = value.Int64
			}
		case useraffiliatereversal.FieldSourceOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_order_id", values[i])
			} else if value.Valid {
				_m.SourceOrderID = value.Int64
			}
		case useraffiliatereversal.FieldInviterUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field inviter_user_id", values[i])
			} else if value.Valid {
				_m.InviterUserID = value.Int64
			}
		case useraffiliatereversal.FieldInviteeUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_user_id", values[i])
			} else if value.Valid {
				_m.InviteeUserID = value.Int64
			}
		case useraffiliatereversal.FieldRebateAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rebate_amount", values[i])
			} else if value.Valid {
				_m.RebateAmount = value.Float64
			}
		case useraffiliatereversal.FieldFrozenQuotaDeducted:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field frozen_quota_deducted", values[i])
			} else if value.Valid {
				_m.FrozenQuotaDeducted = new(float64)
				*_m.FrozenQuotaDeducted = value.Float64
			}
		case useraffiliatereversal.FieldAvailableQuotaDeducted:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field available_quota_deducted", values[i])
			} else if value.Valid {
				_m.AvailableQuotaDeducted = new(float64)
				*_m.AvailableQuotaDeducted = value.Float64
			}
		case useraffiliatereversal.FieldBalanceDeducted:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_deducted", values[i])
			} else if value.Valid {
				_m.BalanceDeducted = new(float64)
				*_m.BalanceDeducted = value.Float64
			}
		case useraffiliatereversal.FieldTotalRechargedDeducted:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_recharged_deducted", values[i])
			} else if value.Valid {
				_m.TotalRechargedDeducted = new(float64)
				*_m.TotalRechargedDeducted = value.Float64
			}
		case useraffiliatereversal.FieldBalanceBefore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_before", values[i])
			} else if value.Valid {
				_m.BalanceBefore = new(float64)
				*_m.BalanceBefore = value.Float64
			}
		case useraffiliatereversal.FieldBalanceAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after", values[i])
			} else if value.Valid {
				_m.BalanceAfter = new(float64)
				*_m.BalanceAfter = value.Float64
			}
		case useraffiliatereversal.FieldAffQuotaBefore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field aff_quota_before", values[i])
			} else if value.Valid {
				_m.AffQuotaBefore = new(float64)
				*_m.AffQuotaBefore = value.Float64
			}
		case useraffiliatereversal.FieldAffQuotaAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field aff_quota_after", values[i])
			} else if value.Valid {
				_m.AffQuotaAfter = new(float64)
				*_m.AffQuotaAfter = value.Float64
			}
		case useraffiliatereversal.FieldAffFrozenQuotaBefore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field aff_frozen_quota_before", values[i])
			} else if value.Valid {
				_m.AffFrozenQuotaBefore = new(float64)
				*_m.AffFrozenQuotaBefore = value.Float64
			}
		case useraffiliatereversal.FieldAffFrozenQuotaAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field aff_frozen_quota_after", values[i])
			} else if value.Valid {
				_m.AffFrozenQuotaAfter = new(float64)
				*_m.AffFrozenQuotaAfter = value.Float64
			}
		case useraffiliatereversal.FieldAffHistoryQuotaBefore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field aff_history_quota_before", values[i])
			} else if value.Valid {
				_m.AffHistoryQuotaBefore = new(float64)
				*_m.AffHistoryQuotaBefore = value.Float64
			}
		case useraffiliatereversal.FieldAffHistoryQuotaAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field aff_history_quota_after", values[i])
			} else if value.Valid {
				_m.AffHistoryQuotaAfter = new(float64)
				*_m.AffHistoryQuotaAfter = value.Float64
			}
		case useraffiliatereversal.FieldTotalRechargedBefore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_recharged_before", values[i])
			} else if value.Valid {
				_m.TotalRechargedBefore = new(float64)
				*_m.TotalRechargedBefore = value.Float64
			}
		case useraffiliatereversal.FieldTotalRechargedAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_recharged_after", values[i])
			} else if value.Valid {
				_m.TotalRechargedAfter = new(float64)
				*_m.TotalRechargedAfter = value.Float64
			}
		case useraffiliatereversal.FieldSnapshotAvailable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot_available", values[i])
			} else if value.Valid {
				_m.SnapshotAvailable = value.Bool
			}
		case useraffiliatereversal.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case useraffiliatereversal.FieldOperatorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_user_id", values[i])
			} else if value.Valid {
				_m.OperatorUserID = new(int64)
				*_m.OperatorUserID = value.Int64
			}
		case useraffiliatereversal.FieldOperationKeyHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation_key_hash", values[i])
			} else if value.Valid {
				_m.OperationKeyHash = new(string)
				*_m.OperationKeyHash = value.String
			}
		case useraffiliatereversal.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case useraffiliatereversal.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserAffiliateReversal.
// This includes values selected through modifiers, order, etc.
func (_m *UserAffiliateReversal) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserAffiliateReversal.
// Note that you need to call UserAffiliateReversal.Unwrap() before calling this method if this UserAffiliateReversal
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserAffiliateReversal) Update() *UserAffiliateReversalUpdateOne {
	return NewUserAffiliateReversalClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserAffiliateReversal entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserAffiliateReversal) Unwrap() *UserAffiliateReversal {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserAffiliateReversal is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserAffiliateReversal) String() string {
	var builder strings.Builder
	builder.WriteString("UserAffiliateReversal(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.SourceLedgerID; v != nil {
		builder.WriteString("source_ledger_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("source_order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceOrderID))
	builder.WriteString(", ")
	builder.WriteString("inviter_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviterUserID))
	builder.WriteString(", ")
	builder.WriteString("invitee_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviteeUserID))
	builder.WriteString(", ")
	builder.WriteString("rebate_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RebateAmount))
	builder.WriteString(", ")
	if v := _m.FrozenQuotaDeducted; v != nil {
		builder.WriteString("frozen_quota_deducted=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AvailableQuotaDeducted; v != nil {
		builder.WriteString("available_quota_deducted=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.BalanceDeducted; v != nil {
		builder.WriteString("balance_deducted=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TotalRechargedDeducted; v != nil {
		builder.WriteString("total_recharged_deducted=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.BalanceBefore; v != nil {
		builder.WriteString("balance_before=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.BalanceAfter; v != nil {
		builder.WriteString("balance_after=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AffQuotaBefore; v != nil {
		builder.WriteString("aff_quota_before=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AffQuotaAfter; v != nil {
		builder.WriteString("aff_quota_after=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AffFrozenQuotaBefore; v != nil {
		builder.WriteString("aff_frozen_quota_before=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AffFrozenQuotaAfter; v != nil {
		builder.WriteString("aff_frozen_quota_after=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AffHistoryQuotaBefore; v != nil {
		builder.WriteString("aff_history_quota_before=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AffHistoryQuotaAfter; v != nil {
		builder.WriteString("aff_history_quota_after=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TotalRechargedBefore; v != nil {
		builder.WriteString("total_recharged_before=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TotalRechargedAfter; v != nil {
		builder.WriteString("total_recharged_after=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("snapshot_available=")
	builder.WriteString(fmt.Sprintf("%v", _m.SnapshotAvailable))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	if v := _m.OperatorUserID; v != nil {
		builder.WriteString("operator_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OperationKeyHash; v != nil {
		builder.WriteString("operation_key_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserAffiliateReversals is a parsable slice of UserAffiliateReversal.
type UserAffiliateReversals []*UserAffiliateReversal
