// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/useraffiliate"
)

// UserAffiliateUpdate is the builder for updating UserAffiliate entities.
type UserAffiliateUpdate struct {
	config
	hooks    []Hook
	mutation *UserAffiliateMutation
}

// Where appends a list predicates to the UserAffiliateUpdate builder.
func (_u *UserAffiliateUpdate) Where(ps ...predicate.UserAffiliate) *UserAffiliateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAffCode sets the "aff_code" field.
func (_u *UserAffiliateUpdate) SetAffCode(v string) *UserAffiliateUpdate {
	_u.mutation.SetAffCode(v)
	return _u
}

// SetNillableAffCode sets the "aff_code" field if the given value is not nil.
func (_u *UserAffiliateUpdate) SetNillableAffCode(v *string) *UserAffiliateUpdate {
	if v != nil {
		_u.SetAffCode(*v)
	}
	return _u
}

// SetAffCodeCustom sets the "aff_code_custom" field.
func (_u *UserAffiliateUpdate) SetAffCodeCustom(v bool) *UserAffiliateUpdate {
	_u.mutation.SetAffCodeCustom(v)
	return _u
}

// SetNillableAffCodeCustom sets the "aff_code_custom" field if the given value is not nil.
func (_u *UserAffiliateUpdate) SetNillableAffCodeCustom(v *bool) *UserAffiliateUpdate {
	if v != nil {
		_u.SetAffCodeCustom(*v)
	}
	return _u
}

// SetAffRebateRatePercent sets the "aff_rebate_rate_percent" field.
func (_u *UserAffiliateUpdate) SetAffRebateRatePercent(v float64) *UserAffiliateUpdate {
	_u.mutation.ResetAffRebateRatePercent()
	_u.mutation.SetAffRebateRatePercent(v)
	return _u
}

// SetNillableAffRebateRatePercent sets the "aff_rebate_rate_percent" field if the given value is not nil.
func (_u *UserAffiliateUpdate) SetNillableAffRebateRatePercent(v *float64) *UserAffiliateUpdate {
	if v != nil {
		_u.SetAffRebateRatePercent(*v)
	}
	return _u
}

// AddAffRebateRatePercent adds value to the "aff_rebate_rate_percent" field.
func (_u *UserAffiliateUpdate) AddAffRebateRatePercent(v float64) *UserAffiliateUpdate {
	_u.mutation.AddAffRebateRatePercent(v)
	return _u
}

// ClearAffRebateRatePercent clears the value of the "aff_rebate_rate_percent" field.
func (_u *UserAffiliateUpdate) ClearAffRebateRatePercent() *UserAffiliateUpdate {
	_u.mutation.ClearAffRebateRatePercent()
	return _u
}

// SetInviterID sets the "inviter_id" field.
func (_u *UserAffiliateUpdate) SetInviterID(v int64) *UserAffiliateUpdate {
	_u.mutation.ResetInviterID()
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *UserAffiliateUpdate) SetNillableInviterID(v *int64) *UserAffiliateUpdate {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// AddInviterID adds value to the "inviter_id" field.
func (_u *UserAffiliateUpdate) AddInviterID(v int64) *UserAffiliateUpdate {
	_u.mutation.AddInviterID(v)
	return _u
}

// ClearInviterID clears the value of the "inviter_id" field.
func (_u *UserAffiliateUpdate) ClearInviterID() *UserAffiliateUpdate {
	_u.mutation.ClearInviterID()
	return _u
}

// SetAffCount sets the "aff_count" field.
func (_u *UserAffiliateUpdate) SetAffCount(v int) *UserAffiliateUpdate {
	_u.mutation.ResetAffCount()
	_u.mutation.SetAffCount(v)
	return _u
}

// SetNillableAffCount sets the "aff_count" field if the given value is not nil.
func (_u *UserAffiliateUpdate) SetNillableAffCount(v *int) *UserAffiliateUpdate {
	if v != nil {
		_u.SetAffCount(*v)
	}
	return _u
}

// AddAffCount adds value to the "aff_count" field.
func (_u *UserAffiliateUpdate) AddAffCount(v int) *UserAffiliateUpdate {
	_u.mutation.AddAffCount(v)
	return _u
}

// SetAffQuota sets the "aff_quota" field.
func (_u *UserAffiliateUpdate) SetAffQuota(v float64) *UserAffiliateUpdate {
	_u.mutation.ResetAffQuota()
	_u.mutation.SetAffQuota(v)
	return _u
}

// SetNillableAffQuota sets the "aff_quota" field if the given value is not nil.
func (_u *UserAffiliateUpdate) SetNillableAffQuota(v *float64) *UserAffiliateUpdate {
	if v != nil {
		_u.SetAffQuota(*v)
	}
	return _u
}

// AddAffQuota adds value to the "aff_quota" field.
func (_u *UserAffiliateUpdate) AddAffQuota(v float64) *UserAffiliateUpdate {
	_u.mutation.AddAffQuota(v)
	return _u
}

// SetAffFrozenQuota sets the "aff_frozen_quota" field.
func (_u *UserAffiliateUpdate) SetAffFrozenQuota(v float64) *UserAffiliateUpdate {
	_u.mutation.ResetAffFrozenQuota()
	_u.mutation.SetAffFrozenQuota(v)
	return _u
}

// SetNillableAffFrozenQuota sets the "aff_frozen_quota" field if the given value is not nil.
func (_u *UserAffiliateUpdate) SetNillableAffFrozenQuota(v *float64) *UserAffiliateUpdate {
	if v != nil {
		_u.SetAffFrozenQuota(*v)
	}
	return _u
}

// AddAffFrozenQuota adds value to the "aff_frozen_quota" field.
func (_u *UserAffiliateUpdate) AddAffFrozenQuota(v float64) *UserAffiliateUpdate {
	_u.mutation.AddAffFrozenQuota(v)
	return _u
}

// SetAffHistoryQuota sets the "aff_history_quota" field.
func (_u *UserAffiliateUpdate) SetAffHistoryQuota(v float64) *UserAffiliateUpdate {
	_u.mutation.ResetAffHistoryQuota()
	_u.mutation.SetAffHistoryQuota(v)
	return _u
}

// SetNillableAffHistoryQuota sets the "aff_history_quota" field if the given value is not nil.
func (_u *UserAffiliateUpdate) SetNillableAffHistoryQuota(v *float64) *UserAffiliateUpdate {
	if v != nil {
		_u.SetAffHistoryQuota(*v)
	}
	return _u
}

// AddAffHistoryQuota adds value to the "aff_history_quota" field.
func (_u *UserAffiliateUpdate) AddAffHistoryQuota(v float64) *UserAffiliateUpdate {
	_u.mutation.AddAffHistoryQuota(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAffiliateUpdate) SetUpdatedAt(v time.Time) *UserAffiliateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserAffiliateMutation object of the builder.
func (_u *UserAffiliateUpdate) Mutation() *UserAffiliateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAffiliateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAffiliateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAffiliateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAffiliateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAffiliateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useraffiliate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAffiliateUpdate) check() error {
	if v, ok := _u.mutation.AffCode(); ok {
		if err := useraffiliate.AffCodeValidator(v); err != nil {
			return &ValidationError{Name: "aff_code", err: fmt.Errorf(`ent: validator failed for field "UserAffiliate.aff_code": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAffiliateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraffiliate.Table, useraffiliate.Columns, sqlgraph.NewFieldSpec(useraffiliate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AffCode(); ok {
		_spec.SetField(useraffiliate.FieldAffCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.AffCodeCustom(); ok {
		_spec.SetField(useraffiliate.FieldAffCodeCustom, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AffRebateRatePercent(); ok {
		_spec.SetField(useraffiliate.FieldAffRebateRatePercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAffRebateRatePercent(); ok {
		_spec.AddField(useraffiliate.FieldAffRebateRatePercent, field.TypeFloat64, value)
	}
	if _u.mutation.AffRebateRatePercentCleared() {
		_spec.ClearField(useraffiliate.FieldAffRebateRatePercent, field.TypeFloat64)
	}
	if value, ok := _u.mutation.InviterID(); ok {
		_spec.SetField(useraffiliate.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviterID(); ok {
		_spec.AddField(useraffiliate.FieldInviterID, field.TypeInt64, value)
	}
	if _u.mutation.InviterIDCleared() {
		_spec.ClearField(useraffiliate.FieldInviterID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AffCount(); ok {
		_spec.SetField(useraffiliate.FieldAffCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAffCount(); ok {
		_spec.AddField(useraffiliate.FieldAffCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AffQuota(); ok {
		_spec.SetField(useraffiliate.FieldAffQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAffQuota(); ok {
		_spec.AddField(useraffiliate.FieldAffQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AffFrozenQuota(); ok {
		_spec.SetField(useraffiliate.FieldAffFrozenQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAffFrozenQuota(); ok {
		_spec.AddField(useraffiliate.FieldAffFrozenQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AffHistoryQuota(); ok {
		_spec.SetField(useraffiliate.FieldAffHistoryQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAffHistoryQuota(); ok {
		_spec.AddField(useraffiliate.FieldAffHistoryQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useraffiliate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraffiliate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAffiliateUpdateOne is the builder for updating a single UserAffiliate entity.
type UserAffiliateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAffiliateMutation
}

// SetAffCode sets the "aff_code" field.
func (_u *UserAffiliateUpdateOne) SetAffCode(v string) *UserAffiliateUpdateOne {
	_u.mutation.SetAffCode(v)
	return _u
}

// SetNillableAffCode sets the "aff_code" field if the given value is not nil.
func (_u *UserAffiliateUpdateOne) SetNillableAffCode(v *string) *UserAffiliateUpdateOne {
	if v != nil {
		_u.SetAffCode(*v)
	}
	return _u
}

// SetAffCodeCustom sets the "aff_code_custom" field.
func (_u *UserAffiliateUpdateOne) SetAffCodeCustom(v bool) *UserAffiliateUpdateOne {
	_u.mutation.SetAffCodeCustom(v)
	return _u
}

// SetNillableAffCodeCustom sets the "aff_code_custom" field if the given value is not nil.
func (_u *UserAffiliateUpdateOne) SetNillableAffCodeCustom(v *bool) *UserAffiliateUpdateOne {
	if v != nil {
		_u.SetAffCodeCustom(*v)
	}
	return _u
}

// SetAffRebateRatePercent sets the "aff_rebate_rate_percent" field.
func (_u *UserAffiliateUpdateOne) SetAffRebateRatePercent(v float64) *UserAffiliateUpdateOne {
	_u.mutation.ResetAffRebateRatePercent()
	_u.mutation.SetAffRebateRatePercent(v)
	return _u
}

// SetNillableAffRebateRatePercent sets the "aff_rebate_rate_percent" field if the given value is not nil.
func (_u *UserAffiliateUpdateOne) SetNillableAffRebateRatePercent(v *float64) *UserAffiliateUpdateOne {
	if v != nil {
		_u.SetAffRebateRatePercent(*v)
	}
	return _u
}

// AddAffRebateRatePercent adds value to the "aff_rebate_rate_percent" field.
func (_u *UserAffiliateUpdateOne) AddAffRebateRatePercent(v float64) *UserAffiliateUpdateOne {
	_u.mutation.AddAffRebateRatePercent(v)
	return _u
}

// ClearAffRebateRatePercent clears the value of the "aff_rebate_rate_percent" field.
func (_u *UserAffiliateUpdateOne) ClearAffRebateRatePercent() *UserAffiliateUpdateOne {
	_u.mutation.ClearAffRebateRatePercent()
	return _u
}

// SetInviterID sets the "inviter_id" field.
func (_u *UserAffiliateUpdateOne) SetInviterID(v int64) *UserAffiliateUpdateOne {
	_u.mutation.ResetInviterID()
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *UserAffiliateUpdateOne) SetNillableInviterID(v *int64) *UserAffiliateUpdateOne {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// AddInviterID adds value to the "inviter_id" field.
func (_u *UserAffiliateUpdateOne) AddInviterID(v int64) *UserAffiliateUpdateOne {
	_u.mutation.AddInviterID(v)
	return _u
}

// ClearInviterID clears the value of the "inviter_id" field.
func (_u *UserAffiliateUpdateOne) ClearInviterID() *UserAffiliateUpdateOne {
	_u.mutation.ClearInviterID()
	return _u
}

// SetAffCount sets the "aff_count" field.
func (_u *UserAffiliateUpdateOne) SetAffCount(v int) *UserAffiliateUpdateOne {
	_u.mutation.ResetAffCount()
	_u.mutation.SetAffCount(v)
	return _u
}

// SetNillableAffCount sets the "aff_count" field if the given value is not nil.
func (_u *UserAffiliateUpdateOne) SetNillableAffCount(v *int) *UserAffiliateUpdateOne {
	if v != nil {
		_u.SetAffCount(*v)
	}
	return _u
}

// AddAffCount adds value to the "aff_count" field.
func (_u *UserAffiliateUpdateOne) AddAffCount(v int) *UserAffiliateUpdateOne {
	_u.mutation.AddAffCount(v)
	return _u
}

// SetAffQuota sets the "aff_quota" field.
func (_u *UserAffiliateUpdateOne) SetAffQuota(v float64) *UserAffiliateUpdateOne {
	_u.mutation.ResetAffQuota()
	_u.mutation.SetAffQuota(v)
	return _u
}

// SetNillableAffQuota sets the "aff_quota" field if the given value is not nil.
func (_u *UserAffiliateUpdateOne) SetNillableAffQuota(v *float64) *UserAffiliateUpdateOne {
	if v != nil {
		_u.SetAffQuota(*v)
	}
	return _u
}

// AddAffQuota adds value to the "aff_quota" field.
func (_u *UserAffiliateUpdateOne) AddAffQuota(v float64) *UserAffiliateUpdateOne {
	_u.mutation.AddAffQuota(v)
	return _u
}

// SetAffFrozenQuota sets the "aff_frozen_quota" field.
func (_u *UserAffiliateUpdateOne) SetAffFrozenQuota(v float64) *UserAffiliateUpdateOne {
	_u.mutation.ResetAffFrozenQuota()
	_u.mutation.SetAffFrozenQuota(v)
	return _u
}

// SetNillableAffFrozenQuota sets the "aff_frozen_quota" field if the given value is not nil.
func (_u *UserAffiliateUpdateOne) SetNillableAffFrozenQuota(v *float64) *UserAffiliateUpdateOne {
	if v != nil {
		_u.SetAffFrozenQuota(*v)
	}
	return _u
}

// AddAffFrozenQuota adds value to the "aff_frozen_quota" field.
func (_u *UserAffiliateUpdateOne) AddAffFrozenQuota(v float64) *UserAffiliateUpdateOne {
	_u.mutation.AddAffFrozenQuota(v)
	return _u
}

// SetAffHistoryQuota sets the "aff_history_quota" field.
func (_u *UserAffiliateUpdateOne) SetAffHistoryQuota(v float64) *UserAffiliateUpdateOne {
	_u.mutation.ResetAffHistoryQuota()
	_u.mutation.SetAffHistoryQuota(v)
	return _u
}

// SetNillableAffHistoryQuota sets the "aff_history_quota" field if the given value is not nil.
func (_u *UserAffiliateUpdateOne) SetNillableAffHistoryQuota(v *float64) *UserAffiliateUpdateOne {
	if v != nil {
		_u.SetAffHistoryQuota(*v)
	}
	return _u
}

// AddAffHistoryQuota adds value to the "aff_history_quota" field.
func (_u *UserAffiliateUpdateOne) AddAffHistoryQuota(v float64) *UserAffiliateUpdateOne {
	_u.mutation.AddAffHistoryQuota(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAffiliateUpdateOne) SetUpdatedAt(v time.Time) *UserAffiliateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserAffiliateMutation object of the builder.
func (_u *UserAffiliateUpdateOne) Mutation() *UserAffiliateMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserAffiliateUpdate builder.
func (_u *UserAffiliateUpdateOne) Where(ps ...predicate.UserAffiliate) *UserAffiliateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAffiliateUpdateOne) Select(field string, fields ...string) *UserAffiliateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserAffiliate entity.
func (_u *UserAffiliateUpdateOne) Save(ctx context.Context) (*UserAffiliate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAffiliateUpdateOne) SaveX(ctx context.Context) *UserAffiliate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAffiliateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAffiliateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAffiliateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useraffiliate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAffiliateUpdateOne) check() error {
	if v, ok := _u.mutation.AffCode(); ok {
		if err := useraffiliate.AffCodeValidator(v); err != nil {
			return &ValidationError{Name: "aff_code", err: fmt.Errorf(`ent: validator failed for field "UserAffiliate.aff_code": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAffiliateUpdateOne) sqlSave(ctx context.Context) (_node *UserAffiliate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraffiliate.Table, useraffiliate.Columns, sqlgraph.NewFieldSpec(useraffiliate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAffiliate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useraffiliate.FieldID)
		for _, f := range fields {
			if !useraffiliate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useraffiliate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AffCode(); ok {
		_spec.SetField(useraffiliate.FieldAffCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.AffCodeCustom(); ok {
		_spec.SetField(useraffiliate.FieldAffCodeCustom, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AffRebateRatePercent(); ok {
		_spec.SetField(useraffiliate.FieldAffRebateRatePercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAffRebateRatePercent(); ok {
		_spec.AddField(useraffiliate.FieldAffRebateRatePercent, field.TypeFloat64, value)
	}
	if _u.mutation.AffRebateRatePercentCleared() {
		_spec.ClearField(useraffiliate.FieldAffRebateRatePercent, field.TypeFloat64)
	}
	if value, ok := _u.mutation.InviterID(); ok {
		_spec.SetField(useraffiliate.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviterID(); ok {
		_spec.AddField(useraffiliate.FieldInviterID, field.TypeInt64, value)
	}
	if _u.mutation.InviterIDCleared() {
		_spec.ClearField(useraffiliate.FieldInviterID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AffCount(); ok {
		_spec.SetField(useraffiliate.FieldAffCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAffCount(); ok {
		_spec.AddField(useraffiliate.FieldAffCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AffQuota(); ok {
		_spec.SetField(useraffiliate.FieldAffQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAffQuota(); ok {
		_spec.AddField(useraffiliate.FieldAffQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AffFrozenQuota(); ok {
		_spec.SetField(useraffiliate.FieldAffFrozenQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAffFrozenQuota(); ok {
		_spec.AddField(useraffiliate.FieldAffFrozenQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AffHistoryQuota(); ok {
		_spec.SetField(useraffiliate.FieldAffHistoryQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAffHistoryQuota(); ok {
		_spec.AddField(useraffiliate.FieldAffHistoryQuota, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useraffiliate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UserAffiliate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraffiliate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
