// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/useraffiliateledger"
)

// UserAffiliateLedgerUpdate is the builder for updating UserAffiliateLedger entities.
type UserAffiliateLedgerUpdate struct {
	config
	hooks    []Hook
	mutation *UserAffiliateLedgerMutation
}

// Where appends a list predicates to the UserAffiliateLedgerUpdate builder.
func (_u *UserAffiliateLedgerUpdate) Where(ps ...predicate.UserAffiliateLedger) *UserAffiliateLedgerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserAffiliateLedgerUpdate) SetUserID(v int64) *UserAffiliateLedgerUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdate) SetNillableUserID(v *int64) *UserAffiliateLedgerUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserAffiliateLedgerUpdate) AddUserID(v int64) *UserAffiliateLedgerUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAction sets the "action" field.
func (_u *UserAffiliateLedgerUpdate) SetAction(v string) *UserAffiliateLedgerUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdate) SetNillableAction(v *string) *UserAffiliateLedgerUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *UserAffiliateLedgerUpdate) SetAmount(v float64) *UserAffiliateLedgerUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdate) SetNillableAmount(v *float64) *UserAffiliateLedgerUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *UserAffiliateLedgerUpdate) AddAmount(v float64) *UserAffiliateLedgerUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetSourceUserID sets the "source_user_id" field.
func (_u *UserAffiliateLedgerUpdate) SetSourceUserID(v int64) *UserAffiliateLedgerUpdate {
	_u.mutation.ResetSourceUserID()
	_u.mutation.SetSourceUserID(v)
	return _u
}

// SetNillableSourceUserID sets the "source_user_id" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdate) SetNillableSourceUserID(v *int64) *UserAffiliateLedgerUpdate {
	if v != nil {
		_u.SetSourceUserID(*v)
	}
	return _u
}

// AddSourceUserID adds value to the "source_user_id" field.
func (_u *UserAffiliateLedgerUpdate) AddSourceUserID(v int64) *UserAffiliateLedgerUpdate {
	_u.mutation.AddSourceUserID(v)
	return _u
}

// ClearSourceUserID clears the value of the "source_user_id" field.
func (_u *UserAffiliateLedgerUpdate) ClearSourceUserID() *UserAffiliateLedgerUpdate {
	_u.mutation.ClearSourceUserID()
	return _u
}

// SetSourceOrderID sets the "source_order_id" field.
func (_u *UserAffiliateLedgerUpdate) SetSourceOrderID(v int64) *UserAffiliateLedgerUpdate {
	_u.mutation.ResetSourceOrderID()
	_u.mutation.SetSourceOrderID(v)
	return _u
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdate) SetNillableSourceOrderID(v *int64) *UserAffiliateLedgerUpdate {
	if v != nil {
		_u.SetSourceOrderID(*v)
	}
	return _u
}

// AddSourceOrderID adds value to the "source_order_id" field.
func (_u *UserAffiliateLedgerUpdate) AddSourceOrderID(v int64) *UserAffiliateLedgerUpdate {
	_u.mutation.AddSourceOrderID(v)
	return _u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (_u *UserAffiliateLedgerUpdate) ClearSourceOrderID() *UserAffiliateLedgerUpdate {
	_u.mutation.ClearSourceOrderID()
	return _u
}

// SetFrozenUntil sets the "frozen_until" field.
func (_u *UserAffiliateLedgerUpdate) SetFrozenUntil(v time.Time) *UserAffiliateLedgerUpdate {
	_u.mutation.SetFrozenUntil(v)
	return _u
}

// SetNillableFrozenUntil sets the "frozen_until" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdate) SetNillableFrozenUntil(v *time.Time) *UserAffiliateLedgerUpdate {
	if v != nil {
		_u.SetFrozenUntil(*v)
	}
	return _u
}

// ClearFrozenUntil clears the value of the "frozen_until" field.
func (_u *UserAffiliateLedgerUpdate) ClearFrozenUntil() *UserAffiliateLedgerUpdate {
	_u.mutation.ClearFrozenUntil()
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *UserAffiliateLedgerUpdate) SetBalanceAfter(v float64) *UserAffiliateLedgerUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdate) SetNillableBalanceAfter(v *float64) *UserAffiliateLedgerUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *UserAffiliateLedgerUpdate) AddBalanceAfter(v float64) *UserAffiliateLedgerUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (_u *UserAffiliateLedgerUpdate) ClearBalanceAfter() *UserAffiliateLedgerUpdate {
	_u.mutation.ClearBalanceAfter()
	return _u
}

// SetAffQuotaAfter sets the "aff_quota_after" field.
func (_u *UserAffiliateLedgerUpdate) SetAffQuotaAfter(v float64) *UserAffiliateLedgerUpdate {
	_u.mutation.ResetAffQuotaAfter()
	_u.mutation.SetAffQuotaAfter(v)
	return _u
}

// SetNillableAffQuotaAfter sets the "aff_quota_after" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdate) SetNillableAffQuotaAfter(v *float64) *UserAffiliateLedgerUpdate {
	if v != nil {
		_u.SetAffQuotaAfter(*v)
	}
	return _u
}

// AddAffQuotaAfter adds value to the "aff_quota_after" field.
func (_u *UserAffiliateLedgerUpdate) AddAffQuotaAfter(v float64) *UserAffiliateLedgerUpdate {
	_u.mutation.AddAffQuotaAfter(v)
	return _u
}

// ClearAffQuotaAfter clears the value of the "aff_quota_after" field.
func (_u *UserAffiliateLedgerUpdate) ClearAffQuotaAfter() *UserAffiliateLedgerUpdate {
	_u.mutation.ClearAffQuotaAfter()
	return _u
}

// SetAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field.
func (_u *UserAffiliateLedgerUpdate) SetAffFrozenQuotaAfter(v float64) *UserAffiliateLedgerUpdate {
	_u.mutation.ResetAffFrozenQuotaAfter()
	_u.mutation.SetAffFrozenQuotaAfter(v)
	return _u
}

// SetNillableAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdate) SetNillableAffFrozenQuotaAfter(v *float64) *UserAffiliateLedgerUpdate {
	if v != nil {
		_u.SetAffFrozenQuotaAfter(*v)
	}
	return _u
}

// AddAffFrozenQuotaAfter adds value to the "aff_frozen_quota_after" field.
func (_u *UserAffiliateLedgerUpdate) AddAffFrozenQuotaAfter(v float64) *UserAffiliateLedgerUpdate {
	_u.mutation.AddAffFrozenQuotaAfter(v)
	return _u
}

// ClearAffFrozenQuotaAfter clears the value of the "aff_frozen_quota_after" field.
func (_u *UserAffiliateLedgerUpdate) ClearAffFrozenQuotaAfter() *UserAffiliateLedgerUpdate {
	_u.mutation.ClearAffFrozenQuotaAfter()
	return _u
}

// SetAffHistoryQuotaAfter sets the "aff_history_quota_after" field.
func (_u *UserAffiliateLedgerUpdate) SetAffHistoryQuotaAfter(v float64) *UserAffiliateLedgerUpdate {
	_u.mutation.ResetAffHistoryQuotaAfter()
	_u.mutation.SetAffHistoryQuotaAfter(v)
	return _u
}

// SetNillableAffHistoryQuotaAfter sets the "aff_history_quota_after" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdate) SetNillableAffHistoryQuotaAfter(v *float64) *UserAffiliateLedgerUpdate {
	if v != nil {
		_u.SetAffHistoryQuotaAfter(*v)
	}
	return _u
}

// AddAffHistoryQuotaAfter adds value to the "aff_history_quota_after" field.
func (_u *UserAffiliateLedgerUpdate) AddAffHistoryQuotaAfter(v float64) *UserAffiliateLedgerUpdate {
	_u.mutation.AddAffHistoryQuotaAfter(v)
	return _u
}

// ClearAffHistoryQuotaAfter clears the value of the "aff_history_quota_after" field.
func (_u *UserAffiliateLedgerUpdate) ClearAffHistoryQuotaAfter() *UserAffiliateLedgerUpdate {
	_u.mutation.ClearAffHistoryQuotaAfter()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAffiliateLedgerUpdate) SetUpdatedAt(v time.Time) *UserAffiliateLedgerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserAffiliateLedgerMutation object of the builder.
func (_u *UserAffiliateLedgerUpdate) Mutation() *UserAffiliateLedgerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAffiliateLedgerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAffiliateLedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAffiliateLedgerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAffiliateLedgerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAffiliateLedgerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useraffiliateledger.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAffiliateLedgerUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := useraffiliateledger.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateLedger.action": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAffiliateLedgerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraffiliateledger.Table, useraffiliateledger.Columns, sqlgraph.NewFieldSpec(useraffiliateledger.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(useraffiliateledger.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(useraffiliateledger.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(useraffiliateledger.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(useraffiliateledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(useraffiliateledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SourceUserID(); ok {
		_spec.SetField(useraffiliateledger.FieldSourceUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceUserID(); ok {
		_spec.AddField(useraffiliateledger.FieldSourceUserID, field.TypeInt64, value)
	}
	if _u.mutation.SourceUserIDCleared() {
		_spec.ClearField(useraffiliateledger.FieldSourceUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceOrderID(); ok {
		_spec.SetField(useraffiliateledger.FieldSourceOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceOrderID(); ok {
		_spec.AddField(useraffiliateledger.FieldSourceOrderID, field.TypeInt64, value)
	}
	if _u.mutation.SourceOrderIDCleared() {
		_spec.ClearField(useraffiliateledger.FieldSourceOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.FrozenUntil(); ok {
		_spec.SetField(useraffiliateledger.FieldFrozenUntil, field.TypeTime, value)
	}
	if _u.mutation.FrozenUntilCleared() {
		_spec.ClearField(useraffiliateledger.FieldFrozenUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(useraffiliateledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(useraffiliateledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceAfterCleared() {
		_spec.ClearField(useraffiliateledger.FieldBalanceAfter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AffQuotaAfter(); ok {
		_spec.SetField(useraffiliateledger.FieldAffQuotaAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAffQuotaAfter(); ok {
		_spec.AddField(useraffiliateledger.FieldAffQuotaAfter, field.TypeFloat64, value)
	}
	if _u.mutation.AffQuotaAfterCleared() {
		_spec.ClearField(useraffiliateledger.FieldAffQuotaAfter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AffFrozenQuotaAfter(); ok {
		_spec.SetField(useraffiliateledger.FieldAffFrozenQuotaAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAffFrozenQuotaAfter(); ok {
		_spec.AddField(useraffiliateledger.FieldAffFrozenQuotaAfter, field.TypeFloat64, value)
	}
	if _u.mutation.AffFrozenQuotaAfterCleared() {
		_spec.ClearField(useraffiliateledger.FieldAffFrozenQuotaAfter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AffHistoryQuotaAfter(); ok {
		_spec.SetField(useraffiliateledger.FieldAffHistoryQuotaAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAffHistoryQuotaAfter(); ok {
		_spec.AddField(useraffiliateledger.FieldAffHistoryQuotaAfter, field.TypeFloat64, value)
	}
	if _u.mutation.AffHistoryQuotaAfterCleared() {
		_spec.ClearField(useraffiliateledger.FieldAffHistoryQuotaAfter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useraffiliateledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraffiliateledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAffiliateLedgerUpdateOne is the builder for updating a single UserAffiliateLedger entity.
type UserAffiliateLedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAffiliateLedgerMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserAffiliateLedgerUpdateOne) SetUserID(v int64) *UserAffiliateLedgerUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdateOne) SetNillableUserID(v *int64) *UserAffiliateLedgerUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserAffiliateLedgerUpdateOne) AddUserID(v int64) *UserAffiliateLedgerUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAction sets the "action" field.
func (_u *UserAffiliateLedgerUpdateOne) SetAction(v string) *UserAffiliateLedgerUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdateOne) SetNillableAction(v *string) *UserAffiliateLedgerUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *UserAffiliateLedgerUpdateOne) SetAmount(v float64) *UserAffiliateLedgerUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdateOne) SetNillableAmount(v *float64) *UserAffiliateLedgerUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *UserAffiliateLedgerUpdateOne) AddAmount(v float64) *UserAffiliateLedgerUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetSourceUserID sets the "source_user_id" field.
func (_u *UserAffiliateLedgerUpdateOne) SetSourceUserID(v int64) *UserAffiliateLedgerUpdateOne {
	_u.mutation.ResetSourceUserID()
	_u.mutation.SetSourceUserID(v)
	return _u
}

// SetNillableSourceUserID sets the "source_user_id" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdateOne) SetNillableSourceUserID(v *int64) *UserAffiliateLedgerUpdateOne {
	if v != nil {
		_u.SetSourceUserID(*v)
	}
	return _u
}

// AddSourceUserID adds value to the "source_user_id" field.
func (_u *UserAffiliateLedgerUpdateOne) AddSourceUserID(v int64) *UserAffiliateLedgerUpdateOne {
	_u.mutation.AddSourceUserID(v)
	return _u
}

// ClearSourceUserID clears the value of the "source_user_id" field.
func (_u *UserAffiliateLedgerUpdateOne) ClearSourceUserID() *UserAffiliateLedgerUpdateOne {
	_u.mutation.ClearSourceUserID()
	return _u
}

// SetSourceOrderID sets the "source_order_id" field.
func (_u *UserAffiliateLedgerUpdateOne) SetSourceOrderID(v int64) *UserAffiliateLedgerUpdateOne {
	_u.mutation.ResetSourceOrderID()
	_u.mutation.SetSourceOrderID(v)
	return _u
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdateOne) SetNillableSourceOrderID(v *int64) *UserAffiliateLedgerUpdateOne {
	if v != nil {
		_u.SetSourceOrderID(*v)
	}
	return _u
}

// AddSourceOrderID adds value to the "source_order_id" field.
func (_u *UserAffiliateLedgerUpdateOne) AddSourceOrderID(v int64) *UserAffiliateLedgerUpdateOne {
	_u.mutation.AddSourceOrderID(v)
	return _u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (_u *UserAffiliateLedgerUpdateOne) ClearSourceOrderID() *UserAffiliateLedgerUpdateOne {
	_u.mutation.ClearSourceOrderID()
	return _u
}

// SetFrozenUntil sets the "frozen_until" field.
func (_u *UserAffiliateLedgerUpdateOne) SetFrozenUntil(v time.Time) *UserAffiliateLedgerUpdateOne {
	_u.mutation.SetFrozenUntil(v)
	return _u
}

// SetNillableFrozenUntil sets the "frozen_until" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdateOne) SetNillableFrozenUntil(v *time.Time) *UserAffiliateLedgerUpdateOne {
	if v != nil {
		_u.SetFrozenUntil(*v)
	}
	return _u
}

// ClearFrozenUntil clears the value of the "frozen_until" field.
func (_u *UserAffiliateLedgerUpdateOne) ClearFrozenUntil() *UserAffiliateLedgerUpdateOne {
	_u.mutation.ClearFrozenUntil()
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *UserAffiliateLedgerUpdateOne) SetBalanceAfter(v float64) *UserAffiliateLedgerUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdateOne) SetNillableBalanceAfter(v *float64) *UserAffiliateLedgerUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *UserAffiliateLedgerUpdateOne) AddBalanceAfter(v float64) *UserAffiliateLedgerUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (_u *UserAffiliateLedgerUpdateOne) ClearBalanceAfter() *UserAffiliateLedgerUpdateOne {
	_u.mutation.ClearBalanceAfter()
	return _u
}

// SetAffQuotaAfter sets the "aff_quota_after" field.
func (_u *UserAffiliateLedgerUpdateOne) SetAffQuotaAfter(v float64) *UserAffiliateLedgerUpdateOne {
	_u.mutation.ResetAffQuotaAfter()
	_u.mutation.SetAffQuotaAfter(v)
	return _u
}

// SetNillableAffQuotaAfter sets the "aff_quota_after" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdateOne) SetNillableAffQuotaAfter(v *float64) *UserAffiliateLedgerUpdateOne {
	if v != nil {
		_u.SetAffQuotaAfter(*v)
	}
	return _u
}

// AddAffQuotaAfter adds value to the "aff_quota_after" field.
func (_u *UserAffiliateLedgerUpdateOne) AddAffQuotaAfter(v float64) *UserAffiliateLedgerUpdateOne {
	_u.mutation.AddAffQuotaAfter(v)
	return _u
}

// ClearAffQuotaAfter clears the value of the "aff_quota_after" field.
func (_u *UserAffiliateLedgerUpdateOne) ClearAffQuotaAfter() *UserAffiliateLedgerUpdateOne {
	_u.mutation.ClearAffQuotaAfter()
	return _u
}

// SetAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field.
func (_u *UserAffiliateLedgerUpdateOne) SetAffFrozenQuotaAfter(v float64) *UserAffiliateLedgerUpdateOne {
	_u.mutation.ResetAffFrozenQuotaAfter()
	_u.mutation.SetAffFrozenQuotaAfter(v)
	return _u
}

// SetNillableAffFrozenQuotaAfter sets the "aff_frozen_quota_after" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdateOne) SetNillableAffFrozenQuotaAfter(v *float64) *UserAffiliateLedgerUpdateOne {
	if v != nil {
		_u.SetAffFrozenQuotaAfter(*v)
	}
	return _u
}

// AddAffFrozenQuotaAfter adds value to the "aff_frozen_quota_after" field.
func (_u *UserAffiliateLedgerUpdateOne) AddAffFrozenQuotaAfter(v float64) *UserAffiliateLedgerUpdateOne {
	_u.mutation.AddAffFrozenQuotaAfter(v)
	return _u
}

// ClearAffFrozenQuotaAfter clears the value of the "aff_frozen_quota_after" field.
func (_u *UserAffiliateLedgerUpdateOne) ClearAffFrozenQuotaAfter() *UserAffiliateLedgerUpdateOne {
	_u.mutation.ClearAffFrozenQuotaAfter()
	return _u
}

// SetAffHistoryQuotaAfter sets the "aff_history_quota_after" field.
func (_u *UserAffiliateLedgerUpdateOne) SetAffHistoryQuotaAfter(v float64) *UserAffiliateLedgerUpdateOne {
	_u.mutation.ResetAffHistoryQuotaAfter()
	_u.mutation.SetAffHistoryQuotaAfter(v)
	return _u
}

// SetNillableAffHistoryQuotaAfter sets the "aff_history_quota_after" field if the given value is not nil.
func (_u *UserAffiliateLedgerUpdateOne) SetNillableAffHistoryQuotaAfter(v *float64) *UserAffiliateLedgerUpdateOne {
	if v != nil {
		_u.SetAffHistoryQuotaAfter(*v)
	}
	return _u
}

// AddAffHistoryQuotaAfter adds value to the "aff_history_quota_after" field.
func (_u *UserAffiliateLedgerUpdateOne) AddAffHistoryQuotaAfter(v float64) *UserAffiliateLedgerUpdateOne {
	_u.mutation.AddAffHistoryQuotaAfter(v)
	return _u
}

// ClearAffHistoryQuotaAfter clears the value of the "aff_history_quota_after" field.
func (_u *UserAffiliateLedgerUpdateOne) ClearAffHistoryQuotaAfter() *UserAffiliateLedgerUpdateOne {
	_u.mutation.ClearAffHistoryQuotaAfter()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAffiliateLedgerUpdateOne) SetUpdatedAt(v time.Time) *UserAffiliateLedgerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserAffiliateLedgerMutation object of the builder.
func (_u *UserAffiliateLedgerUpdateOne) Mutation() *UserAffiliateLedgerMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserAffiliateLedgerUpdate builder.
func (_u *UserAffiliateLedgerUpdateOne) Where(ps ...predicate.UserAffiliateLedger) *UserAffiliateLedgerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAffiliateLedgerUpdateOne) Select(field string, fields ...string) *UserAffiliateLedgerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserAffiliateLedger entity.
func (_u *UserAffiliateLedgerUpdateOne) Save(ctx context.Context) (*UserAffiliateLedger, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAffiliateLedgerUpdateOne) SaveX(ctx context.Context) *UserAffiliateLedger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAffiliateLedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAffiliateLedgerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAffiliateLedgerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useraffiliateledger.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAffiliateLedgerUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := useraffiliateledger.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "UserAffiliateLedger.action": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAffiliateLedgerUpdateOne) sqlSave(ctx context.Context) (_node *UserAffiliateLedger, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraffiliateledger.Table, useraffiliateledger.Columns, sqlgraph.NewFieldSpec(useraffiliateledger.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAffiliateLedger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useraffiliateledger.FieldID)
		for _, f := range fields {
			if !useraffiliateledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useraffiliateledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(useraffiliateledger.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(useraffiliateledger.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(useraffiliateledger.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(useraffiliateledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(useraffiliateledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SourceUserID(); ok {
		_spec.SetField(useraffiliateledger.FieldSourceUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceUserID(); ok {
		_spec.AddField(useraffiliateledger.FieldSourceUserID, field.TypeInt64, value)
	}
	if _u.mutation.SourceUserIDCleared() {
		_spec.ClearField(useraffiliateledger.FieldSourceUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceOrderID(); ok {
		_spec.SetField(useraffiliateledger.FieldSourceOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceOrderID(); ok {
		_spec.AddField(useraffiliateledger.FieldSourceOrderID, field.TypeInt64, value)
	}
	if _u.mutation.SourceOrderIDCleared() {
		_spec.ClearField(useraffiliateledger.FieldSourceOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.FrozenUntil(); ok {
		_spec.SetField(useraffiliateledger.FieldFrozenUntil, field.TypeTime, value)
	}
	if _u.mutation.FrozenUntilCleared() {
		_spec.ClearField(useraffiliateledger.FieldFrozenUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(useraffiliateledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(useraffiliateledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceAfterCleared() {
		_spec.ClearField(useraffiliateledger.FieldBalanceAfter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AffQuotaAfter(); ok {
		_spec.SetField(useraffiliateledger.FieldAffQuotaAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAffQuotaAfter(); ok {
		_spec.AddField(useraffiliateledger.FieldAffQuotaAfter, field.TypeFloat64, value)
	}
	if _u.mutation.AffQuotaAfterCleared() {
		_spec.ClearField(useraffiliateledger.FieldAffQuotaAfter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AffFrozenQuotaAfter(); ok {
		_spec.SetField(useraffiliateledger.FieldAffFrozenQuotaAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAffFrozenQuotaAfter(); ok {
		_spec.AddField(useraffiliateledger.FieldAffFrozenQuotaAfter, field.TypeFloat64, value)
	}
	if _u.mutation.AffFrozenQuotaAfterCleared() {
		_spec.ClearField(useraffiliateledger.FieldAffFrozenQuotaAfter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AffHistoryQuotaAfter(); ok {
		_spec.SetField(useraffiliateledger.FieldAffHistoryQuotaAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAffHistoryQuotaAfter(); ok {
		_spec.AddField(useraffiliateledger.FieldAffHistoryQuotaAfter, field.TypeFloat64, value)
	}
	if _u.mutation.AffHistoryQuotaAfterCleared() {
		_spec.ClearField(useraffiliateledger.FieldAffHistoryQuotaAfter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useraffiliateledger.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UserAffiliateLedger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraffiliateledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
