// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
	"github.com/Wei-Shaw/sub2api/ent/usersubscriptioncycle"
)

// UserSubscriptionCycleCreate is the builder for creating a UserSubscriptionCycle entity.
type UserSubscriptionCycleCreate struct {
	config
	mutation *UserSubscriptionCycleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserSubscriptionCycleCreate) SetCreatedAt(v time.Time) *UserSubscriptionCycleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserSubscriptionCycleCreate) SetNillableCreatedAt(v *time.Time) *UserSubscriptionCycleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserSubscriptionCycleCreate) SetUpdatedAt(v time.Time) *UserSubscriptionCycleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserSubscriptionCycleCreate) SetNillableUpdatedAt(v *time.Time) *UserSubscriptionCycleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *UserSubscriptionCycleCreate) SetSubscriptionID(v int64) *UserSubscriptionCycleCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *UserSubscriptionCycleCreate) SetStartsAt(v time.Time) *UserSubscriptionCycleCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetEndsAt sets the "ends_at" field.
func (_c *UserSubscriptionCycleCreate) SetEndsAt(v time.Time) *UserSubscriptionCycleCreate {
	_c.mutation.SetEndsAt(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserSubscriptionCycleCreate) SetStatus(v string) *UserSubscriptionCycleCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserSubscriptionCycleCreate) SetNillableStatus(v *string) *UserSubscriptionCycleCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *UserSubscriptionCycleCreate) SetSourceType(v string) *UserSubscriptionCycleCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_c *UserSubscriptionCycleCreate) SetNillableSourceType(v *string) *UserSubscriptionCycleCreate {
	if v != nil {
		_c.SetSourceType(*v)
	}
	return _c
}

// SetSourceRef sets the "source_ref" field.
func (_c *UserSubscriptionCycleCreate) SetSourceRef(v string) *UserSubscriptionCycleCreate {
	_c.mutation.SetSourceRef(v)
	return _c
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_c *UserSubscriptionCycleCreate) SetNillableSourceRef(v *string) *UserSubscriptionCycleCreate {
	if v != nil {
		_c.SetSourceRef(*v)
	}
	return _c
}

// SetManualBulkQuotaResetEnabled sets the "manual_bulk_quota_reset_enabled" field.
func (_c *UserSubscriptionCycleCreate) SetManualBulkQuotaResetEnabled(v bool) *UserSubscriptionCycleCreate {
	_c.mutation.SetManualBulkQuotaResetEnabled(v)
	return _c
}

// SetNillableManualBulkQuotaResetEnabled sets the "manual_bulk_quota_reset_enabled" field if the given value is not nil.
func (_c *UserSubscriptionCycleCreate) SetNillableManualBulkQuotaResetEnabled(v *bool) *UserSubscriptionCycleCreate {
	if v != nil {
		_c.SetManualBulkQuotaResetEnabled(*v)
	}
	return _c
}

// SetFinalUsageUsd sets the "final_usage_usd" field.
func (_c *UserSubscriptionCycleCreate) SetFinalUsageUsd(v float64) *UserSubscriptionCycleCreate {
	_c.mutation.SetFinalUsageUsd(v)
	return _c
}

// SetNillableFinalUsageUsd sets the "final_usage_usd" field if the given value is not nil.
func (_c *UserSubscriptionCycleCreate) SetNillableFinalUsageUsd(v *float64) *UserSubscriptionCycleCreate {
	if v != nil {
		_c.SetFinalUsageUsd(*v)
	}
	return _c
}

// SetFinalManualQuotaResetCount sets the "final_manual_quota_reset_count" field.
func (_c *UserSubscriptionCycleCreate) SetFinalManualQuotaResetCount(v int64) *UserSubscriptionCycleCreate {
	_c.mutation.SetFinalManualQuotaResetCount(v)
	return _c
}

// SetNillableFinalManualQuotaResetCount sets the "final_manual_quota_reset_count" field if the given value is not nil.
func (_c *UserSubscriptionCycleCreate) SetNillableFinalManualQuotaResetCount(v *int64) *UserSubscriptionCycleCreate {
	if v != nil {
		_c.SetFinalManualQuotaResetCount(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *UserSubscriptionCycleCreate) SetCompletedAt(v time.Time) *UserSubscriptionCycleCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *UserSubscriptionCycleCreate) SetNillableCompletedAt(v *time.Time) *UserSubscriptionCycleCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_c *UserSubscriptionCycleCreate) SetSubscription(v *UserSubscription) *UserSubscriptionCycleCreate {
	return _c.SetSubscriptionID(v.ID)
}

// Mutation returns the UserSubscriptionCycleMutation object of the builder.
func (_c *UserSubscriptionCycleCreate) Mutation() *UserSubscriptionCycleMutation {
	return _c.mutation
}

// Save creates the UserSubscriptionCycle in the database.
func (_c *UserSubscriptionCycleCreate) Save(ctx context.Context) (*UserSubscriptionCycle, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserSubscriptionCycleCreate) SaveX(ctx context.Context) *UserSubscriptionCycle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSubscriptionCycleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSubscriptionCycleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserSubscriptionCycleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usersubscriptioncycle.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usersubscriptioncycle.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := usersubscriptioncycle.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		v := usersubscriptioncycle.DefaultSourceType
		_c.mutation.SetSourceType(v)
	}
	if _, ok := _c.mutation.ManualBulkQuotaResetEnabled(); !ok {
		v := usersubscriptioncycle.DefaultManualBulkQuotaResetEnabled
		_c.mutation.SetManualBulkQuotaResetEnabled(v)
	}
	if _, ok := _c.mutation.FinalUsageUsd(); !ok {
		v := usersubscriptioncycle.DefaultFinalUsageUsd
		_c.mutation.SetFinalUsageUsd(v)
	}
	if _, ok := _c.mutation.FinalManualQuotaResetCount(); !ok {
		v := usersubscriptioncycle.DefaultFinalManualQuotaResetCount
		_c.mutation.SetFinalManualQuotaResetCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserSubscriptionCycleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserSubscriptionCycle.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserSubscriptionCycle.updated_at"`)}
	}
	if _, ok := _c.mutation.SubscriptionID(); !ok {
		return &ValidationError{Name: "subscription_id", err: errors.New(`ent: missing required field "UserSubscriptionCycle.subscription_id"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "UserSubscriptionCycle.starts_at"`)}
	}
	if _, ok := _c.mutation.EndsAt(); !ok {
		return &ValidationError{Name: "ends_at", err: errors.New(`ent: missing required field "UserSubscriptionCycle.ends_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserSubscriptionCycle.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := usersubscriptioncycle.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserSubscriptionCycle.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "UserSubscriptionCycle.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := usersubscriptioncycle.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "UserSubscriptionCycle.source_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SourceRef(); ok {
		if err := usersubscriptioncycle.SourceRefValidator(v); err != nil {
			return &ValidationError{Name: "source_ref", err: fmt.Errorf(`ent: validator failed for field "UserSubscriptionCycle.source_ref": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ManualBulkQuotaResetEnabled(); !ok {
		return &ValidationError{Name: "manual_bulk_quota_reset_enabled", err: errors.New(`ent: missing required field "UserSubscriptionCycle.manual_bulk_quota_reset_enabled"`)}
	}
	if _, ok := _c.mutation.FinalUsageUsd(); !ok {
		return &ValidationError{Name: "final_usage_usd", err: errors.New(`ent: missing required field "UserSubscriptionCycle.final_usage_usd"`)}
	}
	if _, ok := _c.mutation.FinalManualQuotaResetCount(); !ok {
		return &ValidationError{Name: "final_manual_quota_reset_count", err: errors.New(`ent: missing required field "UserSubscriptionCycle.final_manual_quota_reset_count"`)}
	}
	if len(_c.mutation.SubscriptionIDs()) == 0 {
		return &ValidationError{Name: "subscription", err: errors.New(`ent: missing required edge "UserSubscriptionCycle.subscription"`)}
	}
	return nil
}

func (_c *UserSubscriptionCycleCreate) sqlSave(ctx context.Context) (*UserSubscriptionCycle, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserSubscriptionCycleCreate) createSpec() (*UserSubscriptionCycle, *sqlgraph.CreateSpec) {
	var (
		_node = &UserSubscriptionCycle{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usersubscriptioncycle.Table, sqlgraph.NewFieldSpec(usersubscriptioncycle.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usersubscriptioncycle.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usersubscriptioncycle.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(usersubscriptioncycle.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.EndsAt(); ok {
		_spec.SetField(usersubscriptioncycle.FieldEndsAt, field.TypeTime, value)
		_node.EndsAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(usersubscriptioncycle.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(usersubscriptioncycle.FieldSourceType, field.TypeString, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.SourceRef(); ok {
		_spec.SetField(usersubscriptioncycle.FieldSourceRef, field.TypeString, value)
		_node.SourceRef = &value
	}
	if value, ok := _c.mutation.ManualBulkQuotaResetEnabled(); ok {
		_spec.SetField(usersubscriptioncycle.FieldManualBulkQuotaResetEnabled, field.TypeBool, value)
		_node.ManualBulkQuotaResetEnabled = value
	}
	if value, ok := _c.mutation.FinalUsageUsd(); ok {
		_spec.SetField(usersubscriptioncycle.FieldFinalUsageUsd, field.TypeFloat64, value)
		_node.FinalUsageUsd = value
	}
	if value, ok := _c.mutation.FinalManualQuotaResetCount(); ok {
		_spec.SetField(usersubscriptioncycle.FieldFinalManualQuotaResetCount, field.TypeInt64, value)
		_node.FinalManualQuotaResetCount = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(usersubscriptioncycle.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if nodes := _c.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptioncycle.SubscriptionTable,
			Columns: []string{usersubscriptioncycle.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SubscriptionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserSubscriptionCycle.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserSubscriptionCycleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserSubscriptionCycleCreate) OnConflict(opts ...sql.ConflictOption) *UserSubscriptionCycleUpsertOne {
	_c.conflict = opts
	return &UserSubscriptionCycleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserSubscriptionCycle.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserSubscriptionCycleCreate) OnConflictColumns(columns ...string) *UserSubscriptionCycleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserSubscriptionCycleUpsertOne{
		create: _c,
	}
}

type (
	// UserSubscriptionCycleUpsertOne is the builder for "upsert"-ing
	//  one UserSubscriptionCycle node.
	UserSubscriptionCycleUpsertOne struct {
		create *UserSubscriptionCycleCreate
	}

	// UserSubscriptionCycleUpsert is the "OnConflict" setter.
	UserSubscriptionCycleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserSubscriptionCycleUpsert) SetUpdatedAt(v time.Time) *UserSubscriptionCycleUpsert {
	u.Set(usersubscriptioncycle.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsert) UpdateUpdatedAt() *UserSubscriptionCycleUpsert {
	u.SetExcluded(usersubscriptioncycle.FieldUpdatedAt)
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *UserSubscriptionCycleUpsert) SetSubscriptionID(v int64) *UserSubscriptionCycleUpsert {
	u.Set(usersubscriptioncycle.FieldSubscriptionID, v)
	return u
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsert) UpdateSubscriptionID() *UserSubscriptionCycleUpsert {
	u.SetExcluded(usersubscriptioncycle.FieldSubscriptionID)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *UserSubscriptionCycleUpsert) SetStartsAt(v time.Time) *UserSubscriptionCycleUpsert {
	u.Set(usersubscriptioncycle.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsert) UpdateStartsAt() *UserSubscriptionCycleUpsert {
	u.SetExcluded(usersubscriptioncycle.FieldStartsAt)
	return u
}

// SetEndsAt sets the "ends_at" field.
func (u *UserSubscriptionCycleUpsert) SetEndsAt(v time.Time) *UserSubscriptionCycleUpsert {
	u.Set(usersubscriptioncycle.FieldEndsAt, v)
	return u
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsert) UpdateEndsAt() *UserSubscriptionCycleUpsert {
	u.SetExcluded(usersubscriptioncycle.FieldEndsAt)
	return u
}

// SetStatus sets the "status" field.
func (u *UserSubscriptionCycleUpsert) SetStatus(v string) *UserSubscriptionCycleUpsert {
	u.Set(usersubscriptioncycle.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsert) UpdateStatus() *UserSubscriptionCycleUpsert {
	u.SetExcluded(usersubscriptioncycle.FieldStatus)
	return u
}

// SetSourceType sets the "source_type" field.
func (u *UserSubscriptionCycleUpsert) SetSourceType(v string) *UserSubscriptionCycleUpsert {
	u.Set(usersubscriptioncycle.FieldSourceType, v)
	return u
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsert) UpdateSourceType() *UserSubscriptionCycleUpsert {
	u.SetExcluded(usersubscriptioncycle.FieldSourceType)
	return u
}

// SetSourceRef sets the "source_ref" field.
func (u *UserSubscriptionCycleUpsert) SetSourceRef(v string) *UserSubscriptionCycleUpsert {
	u.Set(usersubscriptioncycle.FieldSourceRef, v)
	return u
}

// UpdateSourceRef sets the "source_ref" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsert) UpdateSourceRef() *UserSubscriptionCycleUpsert {
	u.SetExcluded(usersubscriptioncycle.FieldSourceRef)
	return u
}

// ClearSourceRef clears the value of the "source_ref" field.
func (u *UserSubscriptionCycleUpsert) ClearSourceRef() *UserSubscriptionCycleUpsert {
	u.SetNull(usersubscriptioncycle.FieldSourceRef)
	return u
}

// SetManualBulkQuotaResetEnabled sets the "manual_bulk_quota_reset_enabled" field.
func (u *UserSubscriptionCycleUpsert) SetManualBulkQuotaResetEnabled(v bool) *UserSubscriptionCycleUpsert {
	u.Set(usersubscriptioncycle.FieldManualBulkQuotaResetEnabled, v)
	return u
}

// UpdateManualBulkQuotaResetEnabled sets the "manual_bulk_quota_reset_enabled" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsert) UpdateManualBulkQuotaResetEnabled() *UserSubscriptionCycleUpsert {
	u.SetExcluded(usersubscriptioncycle.FieldManualBulkQuotaResetEnabled)
	return u
}

// SetFinalUsageUsd sets the "final_usage_usd" field.
func (u *UserSubscriptionCycleUpsert) SetFinalUsageUsd(v float64) *UserSubscriptionCycleUpsert {
	u.Set(usersubscriptioncycle.FieldFinalUsageUsd, v)
	return u
}

// UpdateFinalUsageUsd sets the "final_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsert) UpdateFinalUsageUsd() *UserSubscriptionCycleUpsert {
	u.SetExcluded(usersubscriptioncycle.FieldFinalUsageUsd)
	return u
}

// AddFinalUsageUsd adds v to the "final_usage_usd" field.
func (u *UserSubscriptionCycleUpsert) AddFinalUsageUsd(v float64) *UserSubscriptionCycleUpsert {
	u.Add(usersubscriptioncycle.FieldFinalUsageUsd, v)
	return u
}

// SetFinalManualQuotaResetCount sets the "final_manual_quota_reset_count" field.
func (u *UserSubscriptionCycleUpsert) SetFinalManualQuotaResetCount(v int64) *UserSubscriptionCycleUpsert {
	u.Set(usersubscriptioncycle.FieldFinalManualQuotaResetCount, v)
	return u
}

// UpdateFinalManualQuotaResetCount sets the "final_manual_quota_reset_count" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsert) UpdateFinalManualQuotaResetCount() *UserSubscriptionCycleUpsert {
	u.SetExcluded(usersubscriptioncycle.FieldFinalManualQuotaResetCount)
	return u
}

// AddFinalManualQuotaResetCount adds v to the "final_manual_quota_reset_count" field.
func (u *UserSubscriptionCycleUpsert) AddFinalManualQuotaResetCount(v int64) *UserSubscriptionCycleUpsert {
	u.Add(usersubscriptioncycle.FieldFinalManualQuotaResetCount, v)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *UserSubscriptionCycleUpsert) SetCompletedAt(v time.Time) *UserSubscriptionCycleUpsert {
	u.Set(usersubscriptioncycle.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsert) UpdateCompletedAt() *UserSubscriptionCycleUpsert {
	u.SetExcluded(usersubscriptioncycle.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *UserSubscriptionCycleUpsert) ClearCompletedAt() *UserSubscriptionCycleUpsert {
	u.SetNull(usersubscriptioncycle.FieldCompletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserSubscriptionCycle.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserSubscriptionCycleUpsertOne) UpdateNewValues() *UserSubscriptionCycleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usersubscriptioncycle.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserSubscriptionCycle.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserSubscriptionCycleUpsertOne) Ignore() *UserSubscriptionCycleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserSubscriptionCycleUpsertOne) DoNothing() *UserSubscriptionCycleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserSubscriptionCycleCreate.OnConflict
// documentation for more info.
func (u *UserSubscriptionCycleUpsertOne) Update(set func(*UserSubscriptionCycleUpsert)) *UserSubscriptionCycleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserSubscriptionCycleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserSubscriptionCycleUpsertOne) SetUpdatedAt(v time.Time) *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertOne) UpdateUpdatedAt() *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *UserSubscriptionCycleUpsertOne) SetSubscriptionID(v int64) *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertOne) UpdateSubscriptionID() *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserSubscriptionCycleUpsertOne) SetStartsAt(v time.Time) *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertOne) UpdateStartsAt() *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *UserSubscriptionCycleUpsertOne) SetEndsAt(v time.Time) *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertOne) UpdateEndsAt() *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateEndsAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserSubscriptionCycleUpsertOne) SetStatus(v string) *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertOne) UpdateStatus() *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateStatus()
	})
}

// SetSourceType sets the "source_type" field.
func (u *UserSubscriptionCycleUpsertOne) SetSourceType(v string) *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertOne) UpdateSourceType() *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceRef sets the "source_ref" field.
func (u *UserSubscriptionCycleUpsertOne) SetSourceRef(v string) *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetSourceRef(v)
	})
}

// UpdateSourceRef sets the "source_ref" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertOne) UpdateSourceRef() *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateSourceRef()
	})
}

// ClearSourceRef clears the value of the "source_ref" field.
func (u *UserSubscriptionCycleUpsertOne) ClearSourceRef() *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.ClearSourceRef()
	})
}

// SetManualBulkQuotaResetEnabled sets the "manual_bulk_quota_reset_enabled" field.
func (u *UserSubscriptionCycleUpsertOne) SetManualBulkQuotaResetEnabled(v bool) *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetManualBulkQuotaResetEnabled(v)
	})
}

// UpdateManualBulkQuotaResetEnabled sets the "manual_bulk_quota_reset_enabled" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertOne) UpdateManualBulkQuotaResetEnabled() *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateManualBulkQuotaResetEnabled()
	})
}

// SetFinalUsageUsd sets the "final_usage_usd" field.
func (u *UserSubscriptionCycleUpsertOne) SetFinalUsageUsd(v float64) *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetFinalUsageUsd(v)
	})
}

// AddFinalUsageUsd adds v to the "final_usage_usd" field.
func (u *UserSubscriptionCycleUpsertOne) AddFinalUsageUsd(v float64) *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.AddFinalUsageUsd(v)
	})
}

// UpdateFinalUsageUsd sets the "final_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertOne) UpdateFinalUsageUsd() *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateFinalUsageUsd()
	})
}

// SetFinalManualQuotaResetCount sets the "final_manual_quota_reset_count" field.
func (u *UserSubscriptionCycleUpsertOne) SetFinalManualQuotaResetCount(v int64) *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetFinalManualQuotaResetCount(v)
	})
}

// AddFinalManualQuotaResetCount adds v to the "final_manual_quota_reset_count" field.
func (u *UserSubscriptionCycleUpsertOne) AddFinalManualQuotaResetCount(v int64) *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.AddFinalManualQuotaResetCount(v)
	})
}

// UpdateFinalManualQuotaResetCount sets the "final_manual_quota_reset_count" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertOne) UpdateFinalManualQuotaResetCount() *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateFinalManualQuotaResetCount()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *UserSubscriptionCycleUpsertOne) SetCompletedAt(v time.Time) *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertOne) UpdateCompletedAt() *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *UserSubscriptionCycleUpsertOne) ClearCompletedAt() *UserSubscriptionCycleUpsertOne {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *UserSubscriptionCycleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserSubscriptionCycleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserSubscriptionCycleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserSubscriptionCycleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserSubscriptionCycleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserSubscriptionCycleCreateBulk is the builder for creating many UserSubscriptionCycle entities in bulk.
type UserSubscriptionCycleCreateBulk struct {
	config
	err      error
	builders []*UserSubscriptionCycleCreate
	conflict []sql.ConflictOption
}

// Save creates the UserSubscriptionCycle entities in the database.
func (_c *UserSubscriptionCycleCreateBulk) Save(ctx context.Context) ([]*UserSubscriptionCycle, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserSubscriptionCycle, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserSubscriptionCycleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserSubscriptionCycleCreateBulk) SaveX(ctx context.Context) []*UserSubscriptionCycle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSubscriptionCycleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSubscriptionCycleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserSubscriptionCycle.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserSubscriptionCycleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserSubscriptionCycleCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserSubscriptionCycleUpsertBulk {
	_c.conflict = opts
	return &UserSubscriptionCycleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserSubscriptionCycle.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserSubscriptionCycleCreateBulk) OnConflictColumns(columns ...string) *UserSubscriptionCycleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserSubscriptionCycleUpsertBulk{
		create: _c,
	}
}

// UserSubscriptionCycleUpsertBulk is the builder for "upsert"-ing
// a bulk of UserSubscriptionCycle nodes.
type UserSubscriptionCycleUpsertBulk struct {
	create *UserSubscriptionCycleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserSubscriptionCycle.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserSubscriptionCycleUpsertBulk) UpdateNewValues() *UserSubscriptionCycleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usersubscriptioncycle.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserSubscriptionCycle.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserSubscriptionCycleUpsertBulk) Ignore() *UserSubscriptionCycleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserSubscriptionCycleUpsertBulk) DoNothing() *UserSubscriptionCycleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserSubscriptionCycleCreateBulk.OnConflict
// documentation for more info.
func (u *UserSubscriptionCycleUpsertBulk) Update(set func(*UserSubscriptionCycleUpsert)) *UserSubscriptionCycleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserSubscriptionCycleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserSubscriptionCycleUpsertBulk) SetUpdatedAt(v time.Time) *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertBulk) UpdateUpdatedAt() *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *UserSubscriptionCycleUpsertBulk) SetSubscriptionID(v int64) *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertBulk) UpdateSubscriptionID() *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserSubscriptionCycleUpsertBulk) SetStartsAt(v time.Time) *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertBulk) UpdateStartsAt() *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateStartsAt()
	})
}

// SetEndsAt sets the "ends_at" field.
func (u *UserSubscriptionCycleUpsertBulk) SetEndsAt(v time.Time) *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetEndsAt(v)
	})
}

// UpdateEndsAt sets the "ends_at" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertBulk) UpdateEndsAt() *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateEndsAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserSubscriptionCycleUpsertBulk) SetStatus(v string) *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertBulk) UpdateStatus() *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateStatus()
	})
}

// SetSourceType sets the "source_type" field.
func (u *UserSubscriptionCycleUpsertBulk) SetSourceType(v string) *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertBulk) UpdateSourceType() *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceRef sets the "source_ref" field.
func (u *UserSubscriptionCycleUpsertBulk) SetSourceRef(v string) *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetSourceRef(v)
	})
}

// UpdateSourceRef sets the "source_ref" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertBulk) UpdateSourceRef() *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateSourceRef()
	})
}

// ClearSourceRef clears the value of the "source_ref" field.
func (u *UserSubscriptionCycleUpsertBulk) ClearSourceRef() *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.ClearSourceRef()
	})
}

// SetManualBulkQuotaResetEnabled sets the "manual_bulk_quota_reset_enabled" field.
func (u *UserSubscriptionCycleUpsertBulk) SetManualBulkQuotaResetEnabled(v bool) *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetManualBulkQuotaResetEnabled(v)
	})
}

// UpdateManualBulkQuotaResetEnabled sets the "manual_bulk_quota_reset_enabled" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertBulk) UpdateManualBulkQuotaResetEnabled() *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateManualBulkQuotaResetEnabled()
	})
}

// SetFinalUsageUsd sets the "final_usage_usd" field.
func (u *UserSubscriptionCycleUpsertBulk) SetFinalUsageUsd(v float64) *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetFinalUsageUsd(v)
	})
}

// AddFinalUsageUsd adds v to the "final_usage_usd" field.
func (u *UserSubscriptionCycleUpsertBulk) AddFinalUsageUsd(v float64) *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.AddFinalUsageUsd(v)
	})
}

// UpdateFinalUsageUsd sets the "final_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertBulk) UpdateFinalUsageUsd() *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateFinalUsageUsd()
	})
}

// SetFinalManualQuotaResetCount sets the "final_manual_quota_reset_count" field.
func (u *UserSubscriptionCycleUpsertBulk) SetFinalManualQuotaResetCount(v int64) *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetFinalManualQuotaResetCount(v)
	})
}

// AddFinalManualQuotaResetCount adds v to the "final_manual_quota_reset_count" field.
func (u *UserSubscriptionCycleUpsertBulk) AddFinalManualQuotaResetCount(v int64) *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.AddFinalManualQuotaResetCount(v)
	})
}

// UpdateFinalManualQuotaResetCount sets the "final_manual_quota_reset_count" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertBulk) UpdateFinalManualQuotaResetCount() *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateFinalManualQuotaResetCount()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *UserSubscriptionCycleUpsertBulk) SetCompletedAt(v time.Time) *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *UserSubscriptionCycleUpsertBulk) UpdateCompletedAt() *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *UserSubscriptionCycleUpsertBulk) ClearCompletedAt() *UserSubscriptionCycleUpsertBulk {
	return u.Update(func(s *UserSubscriptionCycleUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *UserSubscriptionCycleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserSubscriptionCycleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserSubscriptionCycleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserSubscriptionCycleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
