// Code generated by ent, DO NOT EDIT.

package useraffiliatereversal

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the useraffiliatereversal type in the database.
	Label = "user_affiliate_reversal"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSourceLedgerID holds the string denoting the source_ledger_id field in the database.
	FieldSourceLedgerID = "source_ledger_id"
	// FieldSourceOrderID holds the string denoting the source_order_id field in the database.
	FieldSourceOrderID = "source_order_id"
	// FieldInviterUserID holds the string denoting the inviter_user_id field in the database.
	FieldInviterUserID = "inviter_user_id"
	// FieldInviteeUserID holds the string denoting the invitee_user_id field in the database.
	FieldInviteeUserID = "invitee_user_id"
	// FieldRebateAmount holds the string denoting the rebate_amount field in the database.
	FieldRebateAmount = "rebate_amount"
	// FieldFrozenQuotaDeducted holds the string denoting the frozen_quota_deducted field in the database.
	FieldFrozenQuotaDeducted = "frozen_quota_deducted"
	// FieldAvailableQuotaDeducted holds the string denoting the available_quota_deducted field in the database.
	FieldAvailableQuotaDeducted = "available_quota_deducted"
	// FieldBalanceDeducted holds the string denoting the balance_deducted field in the database.
	FieldBalanceDeducted = "balance_deducted"
	// FieldTotalRechargedDeducted holds the string denoting the total_recharged_deducted field in the database.
	FieldTotalRechargedDeducted = "total_recharged_deducted"
	// FieldBalanceBefore holds the string denoting the balance_before field in the database.
	FieldBalanceBefore = "balance_before"
	// FieldBalanceAfter holds the string denoting the balance_after field in the database.
	FieldBalanceAfter = "balance_after"
	// FieldAffQuotaBefore holds the string denoting the aff_quota_before field in the database.
	FieldAffQuotaBefore = "aff_quota_before"
	// FieldAffQuotaAfter holds the string denoting the aff_quota_after field in the database.
	FieldAffQuotaAfter = "aff_quota_after"
	// FieldAffFrozenQuotaBefore holds the string denoting the aff_frozen_quota_before field in the database.
	FieldAffFrozenQuotaBefore = "aff_frozen_quota_before"
	// FieldAffFrozenQuotaAfter holds the string denoting the aff_frozen_quota_after field in the database.
	FieldAffFrozenQuotaAfter = "aff_frozen_quota_after"
	// FieldAffHistoryQuotaBefore holds the string denoting the aff_history_quota_before field in the database.
	FieldAffHistoryQuotaBefore = "aff_history_quota_before"
	// FieldAffHistoryQuotaAfter holds the string denoting the aff_history_quota_after field in the database.
	FieldAffHistoryQuotaAfter = "aff_history_quota_after"
	// FieldTotalRechargedBefore holds the string denoting the total_recharged_before field in the database.
	FieldTotalRechargedBefore = "total_recharged_before"
	// FieldTotalRechargedAfter holds the string denoting the total_recharged_after field in the database.
	FieldTotalRechargedAfter = "total_recharged_after"
	// FieldSnapshotAvailable holds the string denoting the snapshot_available field in the database.
	FieldSnapshotAvailable = "snapshot_available"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldOperatorUserID holds the string denoting the operator_user_id field in the database.
	FieldOperatorUserID = "operator_user_id"
	// FieldOperationKeyHash holds the string denoting the operation_key_hash field in the database.
	FieldOperationKeyHash = "operation_key_hash"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the useraffiliatereversal in the database.
	Table = "user_affiliate_reversals"
)

// Columns holds all SQL columns for useraffiliatereversal fields.
var Columns = []string{
	FieldID,
	FieldSourceLedgerID,
	FieldSourceOrderID,
	FieldInviterUserID,
	FieldInviteeUserID,
	FieldRebateAmount,
	FieldFrozenQuotaDeducted,
	FieldAvailableQuotaDeducted,
	FieldBalanceDeducted,
	FieldTotalRechargedDeducted,
	FieldBalanceBefore,
	FieldBalanceAfter,
	FieldAffQuotaBefore,
	FieldAffQuotaAfter,
	FieldAffFrozenQuotaBefore,
	FieldAffFrozenQuotaAfter,
	FieldAffHistoryQuotaBefore,
	FieldAffHistoryQuotaAfter,
	FieldTotalRechargedBefore,
	FieldTotalRechargedAfter,
	FieldSnapshotAvailable,
	FieldReason,
	FieldOperatorUserID,
	FieldOperationKeyHash,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSnapshotAvailable holds the default value on creation for the "snapshot_available" field.
	DefaultSnapshotAvailable bool
	// OperationKeyHashValidator is a validator for the "operation_key_hash" field. It is called by the builders before save.
	OperationKeyHashValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserAffiliateReversal queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySourceLedgerID orders the results by the source_ledger_id field.
func BySourceLedgerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceLedgerID, opts...).ToFunc()
}

// BySourceOrderID orders the results by the source_order_id field.
func BySourceOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceOrderID, opts...).ToFunc()
}

// ByInviterUserID orders the results by the inviter_user_id field.
func ByInviterUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviterUserID, opts...).ToFunc()
}

// ByInviteeUserID orders the results by the invitee_user_id field.
func ByInviteeUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteeUserID, opts...).ToFunc()
}

// ByRebateAmount orders the results by the rebate_amount field.
func ByRebateAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRebateAmount, opts...).ToFunc()
}

// ByFrozenQuotaDeducted orders the results by the frozen_quota_deducted field.
func ByFrozenQuotaDeducted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrozenQuotaDeducted, opts...).ToFunc()
}

// ByAvailableQuotaDeducted orders the results by the available_quota_deducted field.
func ByAvailableQuotaDeducted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailableQuotaDeducted, opts...).ToFunc()
}

// ByBalanceDeducted orders the results by the balance_deducted field.
func ByBalanceDeducted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceDeducted, opts...).ToFunc()
}

// ByTotalRechargedDeducted orders the results by the total_recharged_deducted field.
func ByTotalRechargedDeducted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalRechargedDeducted, opts...).ToFunc()
}

// ByBalanceBefore orders the results by the balance_before field.
func ByBalanceBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceBefore, opts...).ToFunc()
}

// ByBalanceAfter orders the results by the balance_after field.
func ByBalanceAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAfter, opts...).ToFunc()
}

// ByAffQuotaBefore orders the results by the aff_quota_before field.
func ByAffQuotaBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffQuotaBefore, opts...).ToFunc()
}

// ByAffQuotaAfter orders the results by the aff_quota_after field.
func ByAffQuotaAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffQuotaAfter, opts...).ToFunc()
}

// ByAffFrozenQuotaBefore orders the results by the aff_frozen_quota_before field.
func ByAffFrozenQuotaBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffFrozenQuotaBefore, opts...).ToFunc()
}

// ByAffFrozenQuotaAfter orders the results by the aff_frozen_quota_after field.
func ByAffFrozenQuotaAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffFrozenQuotaAfter, opts...).ToFunc()
}

// ByAffHistoryQuotaBefore orders the results by the aff_history_quota_before field.
func ByAffHistoryQuotaBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffHistoryQuotaBefore, opts...).ToFunc()
}

// ByAffHistoryQuotaAfter orders the results by the aff_history_quota_after field.
func ByAffHistoryQuotaAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffHistoryQuotaAfter, opts...).ToFunc()
}

// ByTotalRechargedBefore orders the results by the total_recharged_before field.
func ByTotalRechargedBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalRechargedBefore, opts...).ToFunc()
}

// ByTotalRechargedAfter orders the results by the total_recharged_after field.
func ByTotalRechargedAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalRechargedAfter, opts...).ToFunc()
}

// BySnapshotAvailable orders the results by the snapshot_available field.
func BySnapshotAvailable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnapshotAvailable, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByOperatorUserID orders the results by the operator_user_id field.
func ByOperatorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperatorUserID, opts...).ToFunc()
}

// ByOperationKeyHash orders the results by the operation_key_hash field.
func ByOperationKeyHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperationKeyHash, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
