// Code generated by ent, DO NOT EDIT.

package useraffiliate

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the useraffiliate type in the database.
	Label = "user_affiliate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "user_id"
	// FieldAffCode holds the string denoting the aff_code field in the database.
	FieldAffCode = "aff_code"
	// FieldAffCodeCustom holds the string denoting the aff_code_custom field in the database.
	FieldAffCodeCustom = "aff_code_custom"
	// FieldAffRebateRatePercent holds the string denoting the aff_rebate_rate_percent field in the database.
	FieldAffRebateRatePercent = "aff_rebate_rate_percent"
	// FieldInviterID holds the string denoting the inviter_id field in the database.
	FieldInviterID = "inviter_id"
	// FieldAffCount holds the string denoting the aff_count field in the database.
	FieldAffCount = "aff_count"
	// FieldAffQuota holds the string denoting the aff_quota field in the database.
	FieldAffQuota = "aff_quota"
	// FieldAffFrozenQuota holds the string denoting the aff_frozen_quota field in the database.
	FieldAffFrozenQuota = "aff_frozen_quota"
	// FieldAffHistoryQuota holds the string denoting the aff_history_quota field in the database.
	FieldAffHistoryQuota = "aff_history_quota"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the useraffiliate in the database.
	Table = "user_affiliates"
)

// Columns holds all SQL columns for useraffiliate fields.
var Columns = []string{
	FieldID,
	FieldAffCode,
	FieldAffCodeCustom,
	FieldAffRebateRatePercent,
	FieldInviterID,
	FieldAffCount,
	FieldAffQuota,
	FieldAffFrozenQuota,
	FieldAffHistoryQuota,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AffCodeValidator is a validator for the "aff_code" field. It is called by the builders before save.
	AffCodeValidator func(string) error
	// DefaultAffCodeCustom holds the default value on creation for the "aff_code_custom" field.
	DefaultAffCodeCustom bool
	// DefaultAffCount holds the default value on creation for the "aff_count" field.
	DefaultAffCount int
	// DefaultAffQuota holds the default value on creation for the "aff_quota" field.
	DefaultAffQuota float64
	// DefaultAffFrozenQuota holds the default value on creation for the "aff_frozen_quota" field.
	DefaultAffFrozenQuota float64
	// DefaultAffHistoryQuota holds the default value on creation for the "aff_history_quota" field.
	DefaultAffHistoryQuota float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserAffiliate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAffCode orders the results by the aff_code field.
func ByAffCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffCode, opts...).ToFunc()
}

// ByAffCodeCustom orders the results by the aff_code_custom field.
func ByAffCodeCustom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffCodeCustom, opts...).ToFunc()
}

// ByAffRebateRatePercent orders the results by the aff_rebate_rate_percent field.
func ByAffRebateRatePercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffRebateRatePercent, opts...).ToFunc()
}

// ByInviterID orders the results by the inviter_id field.
func ByInviterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviterID, opts...).ToFunc()
}

// ByAffCount orders the results by the aff_count field.
func ByAffCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffCount, opts...).ToFunc()
}

// ByAffQuota orders the results by the aff_quota field.
func ByAffQuota(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffQuota, opts...).ToFunc()
}

// ByAffFrozenQuota orders the results by the aff_frozen_quota field.
func ByAffFrozenQuota(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffFrozenQuota, opts...).ToFunc()
}

// ByAffHistoryQuota orders the results by the aff_history_quota field.
func ByAffHistoryQuota(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffHistoryQuota, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
