// Code generated by ent, DO NOT EDIT.

package useraffiliate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLTE(FieldID, id))
}

// AffCode applies equality check predicate on the "aff_code" field. It's identical to AffCodeEQ.
func AffCode(v string) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldAffCode, v))
}

// AffCodeCustom applies equality check predicate on the "aff_code_custom" field. It's identical to AffCodeCustomEQ.
func AffCodeCustom(v bool) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldAffCodeCustom, v))
}

// AffRebateRatePercent applies equality check predicate on the "aff_rebate_rate_percent" field. It's identical to AffRebateRatePercentEQ.
func AffRebateRatePercent(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldAffRebateRatePercent, v))
}

// InviterID applies equality check predicate on the "inviter_id" field. It's identical to InviterIDEQ.
func InviterID(v int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldInviterID, v))
}

// AffCount applies equality check predicate on the "aff_count" field. It's identical to AffCountEQ.
func AffCount(v int) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldAffCount, v))
}

// AffQuota applies equality check predicate on the "aff_quota" field. It's identical to AffQuotaEQ.
func AffQuota(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldAffQuota, v))
}

// AffFrozenQuota applies equality check predicate on the "aff_frozen_quota" field. It's identical to AffFrozenQuotaEQ.
func AffFrozenQuota(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldAffFrozenQuota, v))
}

// AffHistoryQuota applies equality check predicate on the "aff_history_quota" field. It's identical to AffHistoryQuotaEQ.
func AffHistoryQuota(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldAffHistoryQuota, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldUpdatedAt, v))
}

// AffCodeEQ applies the EQ predicate on the "aff_code" field.
func AffCodeEQ(v string) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldAffCode, v))
}

// AffCodeNEQ applies the NEQ predicate on the "aff_code" field.
func AffCodeNEQ(v string) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNEQ(FieldAffCode, v))
}

// AffCodeIn applies the In predicate on the "aff_code" field.
func AffCodeIn(vs ...string) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldIn(FieldAffCode, vs...))
}

// AffCodeNotIn applies the NotIn predicate on the "aff_code" field.
func AffCodeNotIn(vs ...string) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNotIn(FieldAffCode, vs...))
}

// AffCodeGT applies the GT predicate on the "aff_code" field.
func AffCodeGT(v string) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGT(FieldAffCode, v))
}

// AffCodeGTE applies the GTE predicate on the "aff_code" field.
func AffCodeGTE(v string) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGTE(FieldAffCode, v))
}

// AffCodeLT applies the LT predicate on the "aff_code" field.
func AffCodeLT(v string) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLT(FieldAffCode, v))
}

// AffCodeLTE applies the LTE predicate on the "aff_code" field.
func AffCodeLTE(v string) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLTE(FieldAffCode, v))
}

// AffCodeContains applies the Contains predicate on the "aff_code" field.
func AffCodeContains(v string) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldContains(FieldAffCode, v))
}

// AffCodeHasPrefix applies the HasPrefix predicate on the "aff_code" field.
func AffCodeHasPrefix(v string) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldHasPrefix(FieldAffCode, v))
}

// AffCodeHasSuffix applies the HasSuffix predicate on the "aff_code" field.
func AffCodeHasSuffix(v string) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldHasSuffix(FieldAffCode, v))
}

// AffCodeEqualFold applies the EqualFold predicate on the "aff_code" field.
func AffCodeEqualFold(v string) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEqualFold(FieldAffCode, v))
}

// AffCodeContainsFold applies the ContainsFold predicate on the "aff_code" field.
func AffCodeContainsFold(v string) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldContainsFold(FieldAffCode, v))
}

// AffCodeCustomEQ applies the EQ predicate on the "aff_code_custom" field.
func AffCodeCustomEQ(v bool) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldAffCodeCustom, v))
}

// AffCodeCustomNEQ applies the NEQ predicate on the "aff_code_custom" field.
func AffCodeCustomNEQ(v bool) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNEQ(FieldAffCodeCustom, v))
}

// AffRebateRatePercentEQ applies the EQ predicate on the "aff_rebate_rate_percent" field.
func AffRebateRatePercentEQ(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldAffRebateRatePercent, v))
}

// AffRebateRatePercentNEQ applies the NEQ predicate on the "aff_rebate_rate_percent" field.
func AffRebateRatePercentNEQ(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNEQ(FieldAffRebateRatePercent, v))
}

// AffRebateRatePercentIn applies the In predicate on the "aff_rebate_rate_percent" field.
func AffRebateRatePercentIn(vs ...float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldIn(FieldAffRebateRatePercent, vs...))
}

// AffRebateRatePercentNotIn applies the NotIn predicate on the "aff_rebate_rate_percent" field.
func AffRebateRatePercentNotIn(vs ...float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNotIn(FieldAffRebateRatePercent, vs...))
}

// AffRebateRatePercentGT applies the GT predicate on the "aff_rebate_rate_percent" field.
func AffRebateRatePercentGT(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGT(FieldAffRebateRatePercent, v))
}

// AffRebateRatePercentGTE applies the GTE predicate on the "aff_rebate_rate_percent" field.
func AffRebateRatePercentGTE(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGTE(FieldAffRebateRatePercent, v))
}

// AffRebateRatePercentLT applies the LT predicate on the "aff_rebate_rate_percent" field.
func AffRebateRatePercentLT(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLT(FieldAffRebateRatePercent, v))
}

// AffRebateRatePercentLTE applies the LTE predicate on the "aff_rebate_rate_percent" field.
func AffRebateRatePercentLTE(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLTE(FieldAffRebateRatePercent, v))
}

// AffRebateRatePercentIsNil applies the IsNil predicate on the "aff_rebate_rate_percent" field.
func AffRebateRatePercentIsNil() predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldIsNull(FieldAffRebateRatePercent))
}

// AffRebateRatePercentNotNil applies the NotNil predicate on the "aff_rebate_rate_percent" field.
func AffRebateRatePercentNotNil() predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNotNull(FieldAffRebateRatePercent))
}

// InviterIDEQ applies the EQ predicate on the "inviter_id" field.
func InviterIDEQ(v int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldInviterID, v))
}

// InviterIDNEQ applies the NEQ predicate on the "inviter_id" field.
func InviterIDNEQ(v int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNEQ(FieldInviterID, v))
}

// InviterIDIn applies the In predicate on the "inviter_id" field.
func InviterIDIn(vs ...int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldIn(FieldInviterID, vs...))
}

// InviterIDNotIn applies the NotIn predicate on the "inviter_id" field.
func InviterIDNotIn(vs ...int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNotIn(FieldInviterID, vs...))
}

// InviterIDGT applies the GT predicate on the "inviter_id" field.
func InviterIDGT(v int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGT(FieldInviterID, v))
}

// InviterIDGTE applies the GTE predicate on the "inviter_id" field.
func InviterIDGTE(v int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGTE(FieldInviterID, v))
}

// InviterIDLT applies the LT predicate on the "inviter_id" field.
func InviterIDLT(v int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLT(FieldInviterID, v))
}

// InviterIDLTE applies the LTE predicate on the "inviter_id" field.
func InviterIDLTE(v int64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLTE(FieldInviterID, v))
}

// InviterIDIsNil applies the IsNil predicate on the "inviter_id" field.
func InviterIDIsNil() predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldIsNull(FieldInviterID))
}

// InviterIDNotNil applies the NotNil predicate on the "inviter_id" field.
func InviterIDNotNil() predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNotNull(FieldInviterID))
}

// AffCountEQ applies the EQ predicate on the "aff_count" field.
func AffCountEQ(v int) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldAffCount, v))
}

// AffCountNEQ applies the NEQ predicate on the "aff_count" field.
func AffCountNEQ(v int) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNEQ(FieldAffCount, v))
}

// AffCountIn applies the In predicate on the "aff_count" field.
func AffCountIn(vs ...int) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldIn(FieldAffCount, vs...))
}

// AffCountNotIn applies the NotIn predicate on the "aff_count" field.
func AffCountNotIn(vs ...int) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNotIn(FieldAffCount, vs...))
}

// AffCountGT applies the GT predicate on the "aff_count" field.
func AffCountGT(v int) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGT(FieldAffCount, v))
}

// AffCountGTE applies the GTE predicate on the "aff_count" field.
func AffCountGTE(v int) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGTE(FieldAffCount, v))
}

// AffCountLT applies the LT predicate on the "aff_count" field.
func AffCountLT(v int) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLT(FieldAffCount, v))
}

// AffCountLTE applies the LTE predicate on the "aff_count" field.
func AffCountLTE(v int) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLTE(FieldAffCount, v))
}

// AffQuotaEQ applies the EQ predicate on the "aff_quota" field.
func AffQuotaEQ(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldAffQuota, v))
}

// AffQuotaNEQ applies the NEQ predicate on the "aff_quota" field.
func AffQuotaNEQ(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNEQ(FieldAffQuota, v))
}

// AffQuotaIn applies the In predicate on the "aff_quota" field.
func AffQuotaIn(vs ...float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldIn(FieldAffQuota, vs...))
}

// AffQuotaNotIn applies the NotIn predicate on the "aff_quota" field.
func AffQuotaNotIn(vs ...float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNotIn(FieldAffQuota, vs...))
}

// AffQuotaGT applies the GT predicate on the "aff_quota" field.
func AffQuotaGT(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGT(FieldAffQuota, v))
}

// AffQuotaGTE applies the GTE predicate on the "aff_quota" field.
func AffQuotaGTE(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGTE(FieldAffQuota, v))
}

// AffQuotaLT applies the LT predicate on the "aff_quota" field.
func AffQuotaLT(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLT(FieldAffQuota, v))
}

// AffQuotaLTE applies the LTE predicate on the "aff_quota" field.
func AffQuotaLTE(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLTE(FieldAffQuota, v))
}

// AffFrozenQuotaEQ applies the EQ predicate on the "aff_frozen_quota" field.
func AffFrozenQuotaEQ(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldAffFrozenQuota, v))
}

// AffFrozenQuotaNEQ applies the NEQ predicate on the "aff_frozen_quota" field.
func AffFrozenQuotaNEQ(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNEQ(FieldAffFrozenQuota, v))
}

// AffFrozenQuotaIn applies the In predicate on the "aff_frozen_quota" field.
func AffFrozenQuotaIn(vs ...float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldIn(FieldAffFrozenQuota, vs...))
}

// AffFrozenQuotaNotIn applies the NotIn predicate on the "aff_frozen_quota" field.
func AffFrozenQuotaNotIn(vs ...float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNotIn(FieldAffFrozenQuota, vs...))
}

// AffFrozenQuotaGT applies the GT predicate on the "aff_frozen_quota" field.
func AffFrozenQuotaGT(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGT(FieldAffFrozenQuota, v))
}

// AffFrozenQuotaGTE applies the GTE predicate on the "aff_frozen_quota" field.
func AffFrozenQuotaGTE(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGTE(FieldAffFrozenQuota, v))
}

// AffFrozenQuotaLT applies the LT predicate on the "aff_frozen_quota" field.
func AffFrozenQuotaLT(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLT(FieldAffFrozenQuota, v))
}

// AffFrozenQuotaLTE applies the LTE predicate on the "aff_frozen_quota" field.
func AffFrozenQuotaLTE(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLTE(FieldAffFrozenQuota, v))
}

// AffHistoryQuotaEQ applies the EQ predicate on the "aff_history_quota" field.
func AffHistoryQuotaEQ(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldAffHistoryQuota, v))
}

// AffHistoryQuotaNEQ applies the NEQ predicate on the "aff_history_quota" field.
func AffHistoryQuotaNEQ(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNEQ(FieldAffHistoryQuota, v))
}

// AffHistoryQuotaIn applies the In predicate on the "aff_history_quota" field.
func AffHistoryQuotaIn(vs ...float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldIn(FieldAffHistoryQuota, vs...))
}

// AffHistoryQuotaNotIn applies the NotIn predicate on the "aff_history_quota" field.
func AffHistoryQuotaNotIn(vs ...float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNotIn(FieldAffHistoryQuota, vs...))
}

// AffHistoryQuotaGT applies the GT predicate on the "aff_history_quota" field.
func AffHistoryQuotaGT(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGT(FieldAffHistoryQuota, v))
}

// AffHistoryQuotaGTE applies the GTE predicate on the "aff_history_quota" field.
func AffHistoryQuotaGTE(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGTE(FieldAffHistoryQuota, v))
}

// AffHistoryQuotaLT applies the LT predicate on the "aff_history_quota" field.
func AffHistoryQuotaLT(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLT(FieldAffHistoryQuota, v))
}

// AffHistoryQuotaLTE applies the LTE predicate on the "aff_history_quota" field.
func AffHistoryQuotaLTE(v float64) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLTE(FieldAffHistoryQuota, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserAffiliate) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserAffiliate) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserAffiliate) predicate.UserAffiliate {
	return predicate.UserAffiliate(sql.NotPredicates(p))
}
